### ISSUE TITLE
NPE when start replication

### ISSUE THREAD

**Issue by mtrakal** [couchbase/couchbase-lite-android#1007]
```
    compile 'com.couchbase.lite:couchbase-lite-android:1.3.2-4'
    compile 'com.couchbase.lite:couchbase-lite-android-forestdb:1.3.2-4'
```

```
public static void setAutoReplicate() {
        sCouchDbProvider.clearPreviousReplications();
        sCouchDbProvider.pushReplicate(true);
        sCouchDbProvider.pullReplicate(true);
    }

void pullReplicate(boolean autoReplicate) {
        IReplicable.Replication replication = mOwnerProvider.getReplication();
        IReplicable.Replication.ReplicationEndpoint ownerEndpoint = replication.getOwnerEndpoint();
        mPullReplication = pullReplicate(autoReplicate, false, ownerEndpoint);
    }

   private Replication pullReplicate(boolean autoReplicate, boolean sharing, IReplicable.Replication.ReplicationEndpoint
            replicationEndpoint) {
        Replication pullReplication = mDatabase.createPullReplication(getFullDbUrl(replicationEndpoint));
        addBasicAuth(pullReplication, replicationEndpoint);
        pullReplication.setFilter(sharing ? getPullReplicationFilterName(replicationEndpoint) : NORMAL_REPL_FILTER);
        pullReplication.addChangeListener(new Replication.ChangeListener() {
            @Override
            public void changed(Replication.ChangeEvent changeEvent) {
                notifyChangeEvent(changeEvent);
            }
        });
        pullReplication.setContinuous(autoReplicate);
        pullReplication.start();
        return pullReplication;
    }
```

Pull and push has almost same code (just start pull/push).
It's caused only after create a new userspace on couchDB. On Android 5, 6 (sqlite), N (forest) too.
Same on CBL 1.3.1.

```
09-27 21:07:34.850 W/YablohnCouchDbProvider(12560): cannot create URL object
09-27 21:07:34.850 I/ActivityManager( 663): filter receiver for action = android.intent.action.USER_PRESENT
09-27 21:07:34.860 I/KeyguardFingerprint.Validation( 1064): turn on screen:false
09-27 21:07:34.860 I/KeyguardFingerprint.Validation( 1064): FpUtils.getNeedScreenOn():false
09-27 21:07:34.860 E/Sync (12560): Error creating thread name
09-27 21:07:34.860 E/Sync (12560): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.URL.toExternalForm()' on a null object reference
09-27 21:07:34.860 E/Sync (12560): at com.couchbase.lite.replicator.ReplicationInternal$3.newThread(ReplicationInternal.java:386)
09-27 21:07:34.860 E/Sync (12560): at java.util.concurrent.ThreadPoolExecutor$Worker.(ThreadPoolExecutor.java:582)
09-27 21:07:34.860 E/Sync (12560): at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:895)
09-27 21:07:34.860 E/Sync (12560): at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1553)
09-27 21:07:34.860 E/Sync (12560): at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:306)
09-27 21:07:34.860 E/Sync (12560): at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:503)
09-27 21:07:34.860 E/Sync (12560): at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:602)
09-27 21:07:34.860 E/Sync (12560): at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:593)
09-27 21:07:34.860 E/Sync (12560): at com.couchbase.lite.replicator.ReplicationInternal.fireTrigger(ReplicationInternal.java:232)
09-27 21:07:34.860 E/Sync (12560): at com.couchbase.lite.replicator.ReplicationInternal.triggerStart(ReplicationInternal.java:200)
09-27 21:07:34.860 E/Sync (12560): at com.couchbase.lite.replicator.PusherInternal.triggerStart(PusherInternal.java:53)
09-27 21:07:34.860 E/Sync (12560): at com.couchbase.lite.replicator.Replication.start(Replication.java:229)
09-27 21:07:34.860 E/Sync (12560): at com.yablohn.internal.CouchDbProvider.pushReplicate(CouchDbProvider.java:129)
09-27 21:07:34.860 E/Sync (12560): at com.yablohn.internal.CouchDbProvider.pushReplicate(CouchDbProvider.java:84)
09-27 21:07:34.860 E/Sync (12560): at com.yablohn.internal.Yablohn.setAutoReplicate(Yablohn.java:30)
09-27 21:07:34.860 E/Sync (12560): at com.droid4you.application.wallet.Application.onAppGoingToForeground(Application.java:616)
09-27 21:07:34.860 E/Sync (12560): at com.droid4you.application.wallet.Application.access$900(Application.java:89)
09-27 21:07:34.860 E/Sync (12560): at com.droid4you.application.wallet.Application$8.onActivityStarted(Application.java:576)
09-27 21:07:34.860 E/Sync (12560): at android.app.Application.dispatchActivityStarted(Application.java:205)
09-27 21:07:34.860 E/Sync (12560): at android.app.Activity.onStart(Activity.java:1218)
09-27 21:07:34.860 E/Sync (12560): at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:592)
09-27 21:07:34.860 E/Sync (12560): at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
09-27 21:07:34.860 E/Sync (12560): at roboguice.activity.RoboActionBarActivity.onStart(RoboActionBarActivity.java:106)
09-27 21:07:34.860 E/Sync (12560): at com.droid4you.application.wallet.v3.ui.LoginActivity.onStart(LoginActivity.java:104)
09-27 21:07:34.860 E/Sync (12560): at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1240)
09-27 21:07:34.860 E/Sync (12560): at android.app.Activity.performStart(Activity.java:6097)
09-27 21:07:34.860 E/Sync (12560): at android.app.Activity.performRestart(Activity.java:6154)
09-27 21:07:34.860 E/Sync (12560): at android.app.ActivityThread.handleSleeping(ActivityThread.java:3768)
09-27 21:07:34.860 E/Sync (12560): at android.app.ActivityThread.access$3200(ActivityThread.java:159)
09-27 21:07:34.860 E/Sync (12560): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1568)
09-27 21:07:34.860 E/Sync (12560): at android.os.Handler.dispatchMessage(Handler.java:102)
09-27 21:07:34.860 E/Sync (12560): at android.os.Looper.loop(Looper.java:135)
09-27 21:07:34.860 E/Sync (12560): at android.app.ActivityThread.main(ActivityThread.java:5569)
09-27 21:07:34.860 E/Sync (12560): at java.lang.reflect.Method.invoke(Native Method)
09-27 21:07:34.860 E/Sync (12560): at java.lang.reflect.Method.invoke(Method.java:372)
09-27 21:07:34.860 E/Sync (12560): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
09-27 21:07:34.860 E/Sync (12560): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
09-27 21:07:34.860 W/YablohnCouchDbProvider(12560): cannot create URL object
09-27 21:07:34.870 E/Sync (12560): Error creating thread name
09-27 21:07:34.870 E/Sync (12560): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.URL.toExternalForm()' on a null object reference
09-27 21:07:34.870 E/Sync (12560): at com.couchbase.lite.replicator.ReplicationInternal$3.newThread(ReplicationInternal.java:386)
09-27 21:07:34.870 E/Sync (12560): at java.util.concurrent.ThreadPoolExecutor$Worker.(ThreadPoolExecutor.java:582)
09-27 21:07:34.870 E/Sync (12560): at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:895)
09-27 21:07:34.870 E/Sync (12560): at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1553)
09-27 21:07:34.870 E/Sync (12560): at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:306)
09-27 21:07:34.870 E/Sync (12560): at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:503)
09-27 21:07:34.870 E/Sync (12560): at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:602)
09-27 21:07:34.870 E/Sync (12560): at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:593)
09-27 21:07:34.870 E/Sync (12560): at com.couchbase.lite.replicator.ReplicationInternal.fireTrigger(ReplicationInternal.java:232)
09-27 21:07:34.870 E/Sync (12560): at com.couchbase.lite.replicator.ReplicationInternal.triggerStart(ReplicationInternal.java:200)
09-27 21:07:34.870 E/Sync (12560): at com.couchbase.lite.replicator.PullerInternal.triggerStart(PullerInternal.java:59)
09-27 21:07:34.870 E/Sync (12560): at com.couchbase.lite.replicator.Replication.start(Replication.java:229)
09-27 21:07:34.870 E/Sync (12560): at com.yablohn.internal.CouchDbProvider.pullReplicate(CouchDbProvider.java:145)
09-27 21:07:34.870 E/Sync (12560): at com.yablohn.internal.CouchDbProvider.pullReplicate(CouchDbProvider.java:99)
09-27 21:07:34.870 E/Sync (12560): at com.yablohn.internal.Yablohn.setAutoReplicate(Yablohn.java:31)
09-27 21:07:34.870 E/Sync (12560): at com.droid4you.application.wallet.Application.onAppGoingToForeground(Application.java:616)
09-27 21:07:34.870 E/Sync (12560): at com.droid4you.application.wallet.Application.access$900(Application.java:89)
09-27 21:07:34.870 E/Sync (12560): at com.droid4you.application.wallet.Application$8.onActivityStarted(Application.java:576)
09-27 21:07:34.870 E/Sync (12560): at android.app.Application.dispatchActivityStarted(Application.java:205)
09-27 21:07:34.870 E/Sync (12560): at android.app.Activity.onStart(Activity.java:1218)
09-27 21:07:34.870 E/Sync (12560): at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:592)
09-27 21:07:34.870 E/Sync (12560): at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
09-27 21:07:34.870 E/Sync (12560): at roboguice.activity.RoboActionBarActivity.onStart(RoboActionBarActivity.java:106)
09-27 21:07:34.870 E/Sync (12560): at com.droid4you.application.wallet.v3.ui.LoginActivity.onStart(LoginActivity.java:104)
09-27 21:07:34.870 E/Sync (12560): at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1240)
09-27 21:07:34.870 E/Sync (12560): at android.app.Activity.performStart(Activity.java:6097)
09-27 21:07:34.870 E/Sync (12560): at android.app.Activity.performRestart(Activity.java:6154)
09-27 21:07:34.870 E/Sync (12560): at android.app.ActivityThread.handleSleeping(ActivityThread.java:3768)
09-27 21:07:34.870 E/Sync (12560): at android.app.ActivityThread.access$3200(ActivityThread.java:159)
09-27 21:07:34.870 E/Sync (12560): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1568)
09-27 21:07:34.870 E/Sync (12560): at android.os.Handler.dispatchMessage(Handler.java:102)
09-27 21:07:34.870 E/Sync (12560): at android.os.Looper.loop(Looper.java:135)
09-27 21:07:34.870 E/Sync (12560): at android.app.ActivityThread.main(ActivityThread.java:5569)
09-27 21:07:34.870 E/Sync (12560): at java.lang.reflect.Method.invoke(Native Method)
09-27 21:07:34.870 E/Sync (12560): at java.lang.reflect.Method.invoke(Method.java:372)
09-27 21:07:34.870 E/Sync (12560): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
09-27 21:07:34.870 E/Sync (12560): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
```

Note to self: 1002

**Comment by hideki** [comment]
Hi @mtrakal, 
FYI: 1.3.2 branch was forked from 1.3.1. So current 1.3.2 build is exactly same with 1.3.2. To try latest build from master branch, please use 1.3.1-<highest build number>. Sorry for our confusing version & build numbering.

**Comment by mtrakal** [comment]
Hi @hideki,

thanks, but I still get error:
Error:Could not find couchbase-lite-android.libraries:couchbase-lite-java-core:1.3.1-51.
Required by:
    project :mobile > project :ribeez > project :yablohn > com.couchbase.lite:couchbase-lite-android-forestdb:1.3.1-51

**Comment by hideki** [comment]
Hi @mtrakal,
It seems build 1.3.1-50 and 51 were failed.
`1.3.1-49` is latest.
Thanks!

**Comment by hideki** [comment]
Hi @mtrakal,
Sorry for super late reply.
It seems the application passed `null` value for `URL` when creating push or pull replicators. 
Can you check passed URL value?
Thanks!

**Comment by hideki** [comment]
PR: https://github.com/couchbase/couchbase-lite-java-core/pull/1509

**Comment by mtrakal** [comment]
Hi @hideki,

it's possible. Because it's after create new userspace/profile. So maybe not all data are prepared in time.

Thanks for add check on it.
