### ISSUE TITLE
SQLiteException: no such table: docs (code 1): on Android Nougat 

### ISSUE THREAD

**Issue by AnthonyTTaylor** [couchbase/couchbase-lite-android#1008]
Updating from 1.1.0 to 1.3.1 there seems to be an issue only on Android Nougat where it cannot prepare statements correctly. 

```Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ontimeapp.ontime/com.ontimeapp.ontime.MainActivity}: com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: no such table: docs (code 1): , while compiling: SELECT doc_id, docid FROM docs
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: no such table: docs (code 1): , while compiling: SELECT doc_id, docid FROM docs
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:718)
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:431)
       at com.couchbase.lite.internal.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:595)
       at com.couchbase.lite.internal.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:64)
       at com.couchbase.lite.internal.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:48)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1300)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1239)
       at com.couchbase.lite.storage.SQLiteStorageEngineBase.rawQuery(SQLiteStorageEngineBase.java:183)
       at com.couchbase.lite.DatabaseUpgrade.importData(DatabaseUpgrade.java:109)
       at com.couchbase.lite.Manager.upgradeDatabase(Manager.java:857)
       at com.couchbase.lite.Manager.upgradeOldDatabaseFiles(Manager.java:798)
       at com.couchbase.lite.Manager.<init>(Manager.java:130)
       at com.ontimeapp.ontime.services.imp.CouchDbCacheKt.makeOrBuild(CouchDbCache.kt:59)
       at com.ontimeapp.ontime.services.imp.CouchDbCache.<init>(CouchDbCache.kt:74)
       at com.ontimeapp.ontime.services.CityCache.<init>(CityCache.kt:22)
       at com.ontimeapp.ontime.services.CityCache$Companion.getInstance(CityCache.kt:48)
       at com.ontimeapp.ontime.MainMenuFragment.onStart(MainMenuFragment.kt:70)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2106)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1146)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
       at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2154)
       at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:212)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:610)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
       at com.ontimeapp.ontime.MainActivity.onStart(MainActivity.kt:116)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
       at android.app.Activity.performStart(Activity.java:6681)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)```

And here is the stack

  ```com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativePrepareStatement (SQLiteConnection.java)
com.couchbase.lite.internal.database.sqlite.SQLiteConnection.acquirePreparedStatement (SQLiteConnection.java:718)
com.couchbase.lite.internal.database.sqlite.SQLiteConnection.prepare (SQLiteConnection.java:431)
com.couchbase.lite.internal.database.sqlite.SQLiteSession.prepare (SQLiteSession.java:595)
com.couchbase.lite.internal.database.sqlite.SQLiteProgram.<init> (SQLiteProgram.java:64)
com.couchbase.lite.internal.database.sqlite.SQLiteQuery.<init> (SQLiteQuery.java:37)
com.couchbase.lite.internal.database.sqlite.SQLiteDirectCursorDriver.query (SQLiteDirectCursorDriver.java:48)
com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.rawQueryWithFactory (SQLiteDatabase.java:1300)
com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.rawQuery (SQLiteDatabase.java:1239)
com.couchbase.lite.storage.SQLiteStorageEngineBase.rawQuery (SQLiteStorageEngineBase.java:183)
com.couchbase.lite.DatabaseUpgrade.importData (DatabaseUpgrade.java:109)
com.couchbase.lite.Manager.upgradeDatabase (Manager.java:857)
com.couchbase.lite.Manager.upgradeOldDatabaseFiles (Manager.java:798)
com.couchbase.lite.Manager.<init> (Manager.java:130)```

**Comment by hideki** [comment]
Hi @AnthonyTTaylor,

I have a question.

CBL v1.2.x or earlier version (including v1.1.0) does not work with Android Nougat because Android does not allow applications to access native system libraries. 

How did you encounter this error? Following is my assumption. Is this scenario you faced issue?
1. Application with CBL v1.1.0 was running on Android M or earlier version.
2. Upgraded Android OS to Nougat, then Application with CBL v1.1.0 stopped working.
3. Rebuild Application with CBL v1.3.1, and installed it.
4. Then faced SQLiteException

Thanks,
Hideki

**Comment by hideki** [comment]
Hi @AnthonyTTaylor,

Our Unit test cover database upgrading scenario from V1 (v1.x.x or earlier) schema to V2 (v1.2.x or newer). And I run the test with Android Nougat on Nexus 9 device.  However I could not reproduce the `SQLiteException` error.
Test codes:
https://github.com/couchbase/couchbase-lite-android/blob/master/src/androidTest/java/com/couchbase/lite/ManagerTest.java#L691-L752

From stacktrace, `docs` table does not exist. So database file exists, but `docs` table or all tables don't exist. I can not think about how this could be happens.
`com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: no such table: docs (code 1): , while compiling: SELECT doc_id, docid FROM docs`.

Do you have any additional information?

**Comment by AnthonyTTaylor** [comment]
Sorry, 
I do not have any extra information as to why it does not work on Nougat, I opted to try alpha builds, and on version 0.0.0-766 it works for me.
So it seems to be fixed somewhere between 1.3.1 and 0.0.0-766

**Comment by Pato94** [comment]
Faced this issue today, the assumption of @hideki was exactly what was happening.
The thing is, couchbase **created the a new database file for new Nougat users, but was not allowed to create the table docs**. 
This exception was thrown because the manager tries to import data from a database without a docs table.

[https://github.com/couchbase/couchbase-lite-java-core/blob/ec7c6e3ab65d0632dae9f800bbd6ea1f17f0b301/src/main/java/com/couchbase/lite/Manager.java#L869](url)

I made it work by removing the old database file and retrying in case of failure.

**Comment by hideki** [comment]
Hi @Pato94,
Thank you for your inputs. Can you investigate what causes the error? Do you have any exception or some error message that indicates the failure of table creation?

**Comment by AnthonyTTaylor** [comment]
Hey @Pato94 
Would you get this issue on fresh installs of the app, or only updates.

@hideki I ended up getting the same error on devices that updated from 1.2 to 1.3.1, as well as fresh install devices. 

That being said, I reran a build on gradle, and sent it to my friend who was beta testing on Nougat for me, and it started working for him on 1.3.1/5d96387011ce62d4d75269e4d40d285e8cf94ef8. 

I am still trying to investigate the cause and if it is truly fixed, as it might have been a bug in Nougat, which a subsequent update fixed.

**Comment by Pato94** [comment]
Hi @AnthonyTTaylor 
The problem, (at least for me) comes out if you want to install an app with a version 1.1.X **and then** upgrade to version 1.3.X, I don't get any problems when fresh installing a 1.3.X on Nougat devices.

@hideki I've been digging a little more, there's not an exception being thrown, but a SIGSEGV because the older version tries to load a native library.

While opening the database for the first time, it calls [AndroidSQLiteStorageEngine.open(String path)](https://github.com/couchbase/couchbase-lite-android/blob/release/1.1.0/src/main/java/com/couchbase/lite/android/AndroidSQLiteStorageEngine.java#L38), and after that, if the dbVersion is lower than 1 (The case of a fresh install) [initialises the schema](https://github.com/couchbase/couchbase-lite-java-core/blob/733954834d71d7b15426f4c685c8ff002461bbb1/src/main/java/com/couchbase/lite/Database.java#L1013)

The SIGSEGV happens when couchbase tries to open the database, when the class TDCollateJSON [loads a library which depends on libsqlite.so](https://github.com/couchbase/couchbase-lite-android/blob/release/1.1.0/src/main/java/com/couchbase/touchdb/TDCollateJSON.java#L36), so the schema is never initialized, and the .cblite file, created previously by the Manager, is left without a table DOCS.
