### ISSUE TITLE
attempt to re-open an already-closed object (1.3.1)

### ISSUE THREAD

**Issue by trramsiq** [couchbase/couchbase-lite-android#1009]
I'm getting an error once in a while in an AsyncTask:

`compile 'com.couchbase.lite:couchbase-lite-android:1.3.1'`

```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.app/files/user.cblite2/db.sqlite3
       at com.couchbase.lite.internal.database.sqlite.SQLiteClosable.acquireReference(SourceFile:60)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.beginTransaction(SourceFile:497)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.beginTransaction(SourceFile:410)
       at com.couchbase.lite.storage.SQLiteStorageEngineBase.beginTransaction(SourceFile:150)
       at com.couchbase.lite.store.SQLiteStore.beginTransaction(SourceFile:2309)
       at com.couchbase.lite.store.SQLiteStore.add(SourceFile:1412)
       at com.couchbase.lite.Database.put(SourceFile:1844)
       at com.couchbase.lite.Database.putRevision(SourceFile:1794)
       at com.couchbase.lite.Database.putRevision(SourceFile:1785)
       at com.couchbase.lite.Document.putProperties(SourceFile:523)
       at com.couchbase.lite.Document.putProperties(SourceFile:350)
       at com.app.DevUtilities.Cache.Cache.store(SourceFile:76)
       at com.app.DevUtilities.Cache.CacheObject.apply(SourceFile:46)
       at com.app.Models.Account.Account.save(SourceFile:155)
       at com.app.Models.Account.Account.setOrUpdateAccount(SourceFile:191)
       at com.app.Models.Account.Account.loadApiAccountIntoDb(SourceFile:301)
       at com.app.Fragments.ActivityStream.Controller.ActivityStreamController$ActivityTask.doInBackground(SourceFile:244)
       at com.app.Fragments.ActivityStream.Controller.ActivityStreamController$ActivityTask.doInBackground(SourceFile:215)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by hideki** [comment]
Hi @	trramsiq,

Thank you for reporting issue.  Could you please share code snippet of re-opening database in AsyncTask? We'd like to reproduce this issue first.

Thanks!

**Comment by trramsiq** [comment]
Hi @hideki,

Thanks for getting back at me!
The background method is:
```
protected Void doInBackground(String... urls) {

            // Collect all accounts in data
            ArrayList<Account> accountsToStore = new ArrayList<>();
            for (Tile tile : response.activity) {
                if (tile.account != null) {
                    accountsToStore.add(tile.account);
                } else if (tile.accounts != null) {
                    accountsToStore.addAll(tile.accounts);
                }
            }
            // Load collected accounts into cache
            Account.loadApiAccountIntoDb(accountsToStore); <----- line 244

            return null;
        }
```

The store methods looks like:
```
public static void store(String cache, String id, String content) {

        Document retrievedDocument = null;
        try {
            retrievedDocument = Application.getInstance().getUserDatabaseInstance().getDocument(id);
            Map<String, Object> updatedProperties = new HashMap<String, Object>();
            Map<String, Object> currentProperties = retrievedDocument.getProperties();
            if (currentProperties != null && currentProperties.size() != 0) {
                updatedProperties.putAll(currentProperties);
            }
            updatedProperties.put("1", content);
            retrievedDocument.putProperties(updatedProperties);  <------ line 76
        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
        }
    }
```

The application code:
```
Manager manager = null;
   Database user_database = null;

    public Database getUserDatabaseInstance() throws CouchbaseLiteException {
        if (this.user_database == null) {
            try {
                this.user_database = getManagerInstance().getDatabase(Cache.USER_DB);
            } catch (IOException e) {
                e.printStackTrace();
            }
            if (this.user_database == null && this.manager != null){
                File srcDir = new File(manager.getContext().getFilesDir(), Cache.USER_DB +".cblite2");
                this.manager.replaceDatabase(Cache.USER_DB, srcDir.getAbsolutePath());
            }
        }
        return user_database;
    }

    public Manager getManagerInstance() throws IOException {
        if (manager == null) {
            manager = new Manager(new AndroidContext(this), Manager.DEFAULT_OPTIONS);
        }
        return manager;
    }

```

**Comment by hideki** [comment]
It seems  multiple SQLiteDatabase instances were created.
http://stackoverflow.com/questions/12770092/attempt-to-re-open-an-already-closed-object-sqlitedatabase

But, `Database` and `Manager` instances are held by `Application` instance which is one per application. In general, this should not be happen.

**Comment by trramsiq** [comment]
I have a user_database and a meta_database but only one Manager. The reason for this is that all data that is related to the user needs to be cleared on logout but not the meta.
It isn't an issue when I use the application. I have 6000 user a day resulting in 24000 session but this has only happened twice!?

**Comment by trramsiq** [comment]
Don't know if this help but I'm also getting this exception on the same line:
java.lang.NullPointerException: Attempt to invoke interface method 

```
'void com.couchbase.lite.storage.SQLiteStorageEngine.setTransactionSuccessful()' on a null object reference
       at com.couchbase.lite.store.SQLiteStore.endTransaction(SourceFile:2358)
       at com.couchbase.lite.store.SQLiteStore.add(SourceFile:1607)
       at com.couchbase.lite.Database.put(SourceFile:1844)
       at com.couchbase.lite.Database.putRevision(SourceFile:1794)
       at com.couchbase.lite.Database.putRevision(SourceFile:1785)
       at com.couchbase.lite.Document.putProperties(SourceFile:523)
       at com.couchbase.lite.Document.putProperties(SourceFile:350)
       at com.app.DevUtilities.Cache.Cache.store(SourceFile:76)
```

**Comment by hideki** [comment]
> I have a user_database and a meta_database but only one Manager.

Multiple databases per manager is fine with CBL.

> 'void com.couchbase.lite.storage.SQLiteStorageEngine.setTransactionSuccessful()' on a null object reference

This indicates SQLite database is not opened or closed already. From log message, it seems SQLite database is already closed.

Does the application calls `Manager.close()`, `Database.close()` or `Database.delete()` methods?

**Comment by trramsiq** [comment]
Database.delete() is called on user_database and is set to null after.

**Comment by hideki** [comment]
Could following scenario happen?

- A thread (main or some other thread) calls `Database.dell()`
- Concurrently, AsyncTask calls `doInBackground()`, but database is already closed?

**Comment by trramsiq** [comment]
Yes rarely,
 but the getdatabase() should reopen it now that it has been set to null right?!

**Comment by hideki** [comment]
Unfortunately, it seem there is bug in our codes in terms of thread-safety.

Is it possible to write sample app that reproduce this issue?

**Comment by trramsiq** [comment]
Thank you for your time. 
I will try to code a sample and post the repo here.

Have a nice day!

**Comment by trramsiq** [comment]
Hi @hideki,

I was able to reproduce with this sample:
https://github.com/tristanrichard/couchbase1009.git

**Comment by hideki** [comment]
@trramsiq, Thank you for writing sample app. I could reproduce the issue.

**Comment by hideki** [comment]
Note to Self:

Device: Nexus 9 - Android N
CBL Version: 1.3.1

```
--------- beginning of crash
09-30 15:31:42.719 9997-10251/com.example.tristanrichard.coucbasesample E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
        Process: com.example.tristanrichard.coucbasesample, PID: 9997
        java.lang.RuntimeException: An error occurred while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:318)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
            at java.lang.Thread.run(Thread.java:761)
         Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.couchbase.lite.storage.SQLiteStorageEngine.setTransactionSuccessful()' on a null object reference
            at com.couchbase.lite.store.SQLiteStore.endTransaction(SQLiteStore.java:2358)
            at com.couchbase.lite.store.SQLiteStore.add(SQLiteStore.java:1607)
            at com.couchbase.lite.Database.put(Database.java:1844)
            at com.couchbase.lite.Database.putRevision(Database.java:1794)
            at com.couchbase.lite.Database.putRevision(Database.java:1785)
            at com.couchbase.lite.Document.putProperties(Document.java:523)
            at com.couchbase.lite.Document.putProperties(Document.java:350)
            at com.example.tristanrichard.coucbasesample.MainActivity.store(MainActivity.java:54)
            at com.example.tristanrichard.coucbasesample.MainActivity$ActivityTask.doInBackground(MainActivity.java:91)
            at com.example.tristanrichard.coucbasesample.MainActivity$ActivityTask.doInBackground(MainActivity.java:73)
            at android.os.AsyncTask$2.call(AsyncTask.java:304)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
            at java.lang.Thread.run(Thread.java:761) 
```

**Comment by hideki** [comment]
Hi @trramsiq,

I am curious why the app calls `Manager.replaceDatabase()`? In most of scenario, `Manager.getDatabase(dbname)` does not return `null`. Only if db name is invalid, or db file does not exists.

In `public Database getUserDatabaseInstance() throws CouchbaseLiteException`
```java
            if (this.user_database == null && this.manager != null){
                File srcDir = new File(manager.getContext().getFilesDir(), USER_DB +".cblite2");
                this.manager.replaceDatabase(USER_DB, srcDir.getAbsolutePath());
            }
```
In `public Database getMetaDatabaseInstance() throws CouchbaseLiteException`
```
            if (this.meta_database == null && this.manager != null){
                File srcDir = new File(manager.getContext().getFilesDir(), META_DB +".cblite2");
                this.manager.replaceDatabase(META_DB, srcDir.getAbsolutePath());
            }
```

**Comment by trramsiq** [comment]
I agree! Did not really think about it while writing the code. 
In which cases will it return null?

**Comment by hideki** [comment]
`Manager.replaceDatabase(...)` is provided for supporting pre-populated database.
see http://developer.couchbase.com/documentation/mobile/1.3/develop/guides/couchbase-lite/native-api/database/index.html#installing-a-pre-built-database

**Comment by trramsiq** [comment]
Thanks! Hope to see a fix for this issue soon.

**Comment by hideki** [comment]
[PR](https://github.com/couchbase/couchbase-lite-android/issues/1009)

**Comment by trramsiq** [comment]
Any way I can get my hands on this fix?

**Comment by hideki** [comment]
Currently we are observing unit-test failure on Jenkins server. Could you please wait for a while? Thanks!

**Comment by trramsiq** [comment]
Sure!

**Comment by hideki** [comment]
Hi @trramsiq 

Could you please use 1.3.1-60 which is built from master branch.
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.3.1-60/

NOTE: Database methods could throws RuntimeException (CouchbaseLiteRuntimeException) if database is closed. Please handle this exception for whatever your application requires.

If you don't want other thread to close db, please use Database.runInTransaction(...) for bulk database operations.

Thanks,
Hideki

**Comment by trramsiq** [comment]
Good work! Works as expected... Thanks!
