### ISSUE TITLE
endTransaction() called on NULL pointer

### ISSUE THREAD

**Issue by trramsiq** [couchbase/couchbase-lite-android#1031]
Issue found on 1.3.1-60

```
Fatal Exception: java.lang.RuntimeException: Unable to pause activity {com.app/com.app.activities.main.MainActivity_}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.couchbase.lite.storage.SQLiteStorageEngine.endTransaction()' on a null object reference
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4429)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4388)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4363)
       at android.app.ActivityThread.access$1200(ActivityThread.java:210)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1722)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void com.couchbase.lite.storage.SQLiteStorageEngine.endTransaction()' on a null object reference
       at com.couchbase.lite.store.SQLiteStore.endTransaction(SQLiteStore.java:2391)
       at com.couchbase.lite.store.SQLiteStore.open(SQLiteStore.java:313)
       at com.couchbase.lite.Database.open(Database.java:1330)
       at com.couchbase.lite.Manager.openDatabase(Manager.java:335)
       at com.couchbase.lite.Manager.getDatabase(Manager.java:299)
       at com.app.controllers.Application.getUserDatabaseInstance(Application.java:59)
       at com.app.DevUtilities.Cache.Cache.getDatabase(Cache.java:65)
       at com.app.DevUtilities.Cache.Cache.retreive(Cache.java:99)
       at com.app.DevUtilities.Cache.CacheObject.load(CacheObject.java:64)
       at com.app.Models.User.load(User.java:161)
       at com.app.controllers.SessionController.getUser(SessionController.java:368)
       at com.app.Fragments.Relations.RelationPagerFragment.onPause(RelationPagerFragment.java:103)
       at android.support.v4.app.Fragment.performPause(Fragment.java:2259)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1161)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
       at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:2163)
       at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:234)
       at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:446)
       at com.app.activities.Activity.onPause(Activity.java:133)
       at com.app.activities.main.MainActivity.onPause(MainActivity.java:316)
       at com.app.activities.main.MainActivity_.onPause(MainActivity_.java:155)
       at android.app.Activity.performPause(Activity.java:6731)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1338)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4415)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4388)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4363)
       at android.app.ActivityThread.access$1200(ActivityThread.java:210)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1722)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by hideki** [comment]
Hi @trramsiq,
It seems Database is already closed based on line which causes NPE. Do you have additional information to reproduce this issue? Also NPE happens in rollback operation.  Can you observe any error message in logcat before NPE?
https://github.com/couchbase/couchbase-lite-java-core/blob/561bf61276d87da60a2b19177da6a9d61dc9205e/src/main/java/com/couchbase/lite/store/SQLiteStore.java#L2391

**Comment by trramsiq** [comment]
Unfortunately no, not at this moment. Only that it was introduced by 1.3.1-60.
This is a production error and it has never occurred in development. But I would keep you updated if I am able to reproduce it somehow.

**Comment by trramsiq** [comment]
Hi @hideki,
Just upgrade to 1.3.1-90.
It looks to related to the state of the application. It seems to only happen when the application has been paused! And I know that in some cases the databse gets deleted if the user is logged out by our server.

**Comment by hideki** [comment]
Note to Self:

I reviewed couchbase code and stack trace. It seems there is threading issue. One thread does db operation with transaction, another thread delete database. `delete()` method calls SQLite database close() before deleting database. The `close()` method is just remove reference. The `close()` method is not blocked by if db is in use or it does not fail if db is in use.
