### ISSUE TITLE
couchbase lite p2p attachment replication on android

### ISSUE THREAD

**Issue by Ehsan-Naghipour** [couchbase/couchbase-lite-android#1037]
Hi, 

I'm doing p2p replication between java and android using couchbase lite. Docs without attachment are replicated correctly but when pushing docs with attachment from java to android, I'm facing the issue mentioned here : https://forums.couchbase.com/t/couchbase-lite-p2p-replication-failed/7704 using cbl 1.3.1-90 on android.
error log is:
```
Router unable to route request to do_PUT_Document
java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.couchbase.lite.router.Router.start(Router.java:555)
at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
at java.lang.Thread.run(Thread.java:818)
Caused by: com.couchbase.lite.CouchbaseLiteException, Status: 406 (HTTP 406 not_acceptable)
at com.couchbase.lite.router.Router.getBodyAsDictionary(Router.java:243)
at com.couchbase.lite.router.Router.do_PUT_Document(Router.java:2323)
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.couchbase.lite.router.Router.start(Router.java:555) 
at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:802) 
at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251) 
at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176) 
at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988) 
at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223) 
at java.lang.Thread.run(Thread.java:818) 
```
I posted here since I could not sign up in forums. Is it broken?

Thanks.

**Comment by hideki** [comment]
@sethrosetter Does the functional test cover P2P push replication with attachment?

**Comment by sethrosetter** [comment]
No. Can you file an issue against testkit? I will add one.

**Comment by Ehsan-Naghipour** [comment]
by debugging, I can observe that this code snippet
```
private Map<String, Object> getBodyAsDictionary() throws CouchbaseLiteException {
        // check if content-type is `application/json`
        String contentType = getRequestHeaderContentType();
        if (contentType != null && !contentType.equals(CONTENT_TYPE_JSON))
            throw new CouchbaseLiteException(Status.NOT_ACCEPTABLE);
```
in ~~couchbase-lite-java-core-1.3.1-90\com\couchbase\lite\router\Router.java~~, throws exception as the replication of attachment starts with ~~contentType= "multipart/related"~~. How can I further dig the problem and help debugging?

**Comment by hideki** [comment]
@Ehsan-Naghipour,
Thank you for debugging the issue.
I believe the Replicator sends request with `multipart` formatted body. However, Listener (Router) can not handle `multipart` request. 
Solution could be
-  to implement the parser for multipart body, 
-  Or the replicator should send the attachment embedded JSON as request body if peer is CBL Android.

**Comment by Ehsan-Naghipour** [comment]
In the meanwhile I saw the `p2pfix` branch in `couchbase-lite-java-core` and its 3 commits which were originated from similar issues like [#1218 of couchbase-lite-java-core](https://github.com/couchbase/couchbase-lite-java-core/issues/1218). What is the deal with those commits? Do they implement the first solution you mentioned? I thought of cloning the branch and trying myself but Github indicates that it's 725 commits behind the master, so I was afraid of facing many problems.

**Comment by hideki** [comment]
Hi @Ehsan-Naghipour,
https://github.com/couchbase/couchbase-lite-java-core/issues/1218 was closed because of duplicated ticket with #141. But #141 is not fixed.

**Comment by Ehsan-Naghipour** [comment]
As I could not find any reference to couchbase lite architecture or detailed java docs, I am a bit confused by your explanations, if you can shed more light on this, it would be great. Anyway is there any other workaround for P2P replication of attachments on android and java? I would also be glad to help implementing the `multipart body` support for router, but I need some reference where to start.

Thnaks.

**Comment by hideki** [comment]
ref: https://forums.couchbase.com/t/p2p-replication-fail-with-attachment/10689

**Comment by hideki** [comment]
Note to self:

Replicator should fallback to JSON with embedded attachment if Multipart document is not accepted. Need to figure out.

**Comment by hideki** [comment]
Hi @Ehsan-Naghipour,

You could find basic information about multipart-encoding used by replication.
https://github.com/couchbase/couchbase-lite-ios/wiki/Replication#multipart-encoding

Currently router code can not handle not handle non JSON request.
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/router/Router.java#L2323

Thanks,

**Comment by hideki** [comment]
PR: https://github.com/couchbase/couchbase-lite-java-core/pull/1523
