### ISSUE TITLE
ForestDBStore crash on loadRevisionBody / loadProperties

### ISSUE THREAD

**Issue by mtrakal** [couchbase/couchbase-lite-android#1041]
Crash start after upgrade to latest version `1.3.1-89`. Never seen before.

http://crashes.to/s/8d2cfed5daa

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:318)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
Caused by java.lang.RuntimeException: com.couchbase.lite.CouchbaseLiteException, Status: 404 (HTTP 404 not_found)
       at com.couchbase.lite.SavedRevision.loadProperties(SavedRevision.java:220)
       at com.couchbase.lite.SavedRevision.getProperties(SavedRevision.java:152)
       at com.couchbase.lite.UnsavedRevision.(UnsavedRevision.java)
       at com.couchbase.lite.SavedRevision.createRevision(SavedRevision.java:114)
       at com.yablohn.internal.YablohnBaseDao$1.doInBackground(YablohnBaseDao.java:53)
       at com.yablohn.internal.YablohnBaseDao$1.doInBackground(YablohnBaseDao.java:40)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
Caused by com.couchbase.lite.CouchbaseLiteException
       at com.couchbase.lite.store.ForestDBStore.loadRevisionBody(ForestDBStore.java:383)
       at com.couchbase.lite.Database.loadRevisionBody(Database.java:1568)
       at com.couchbase.lite.SavedRevision.loadProperties(SavedRevision.java:211)
       at com.couchbase.lite.SavedRevision.getProperties(SavedRevision.java:152)
       at com.couchbase.lite.UnsavedRevision.(UnsavedRevision.java)
       at com.couchbase.lite.SavedRevision.createRevision(SavedRevision.java:114)
       at com.yablohn.internal.YablohnBaseDao$1.doInBackground(YablohnBaseDao.java:53)
       at com.yablohn.internal.YablohnBaseDao$1.doInBackground(YablohnBaseDao.java:40)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by hideki** [comment]
Hi @mtrakal,
Thank you for reporting the issue.
It seems specified revision does not exist in the database.
Can you observe any error before this exception?
Thanks!

**Comment by mtrakal** [comment]
Hi @hideki,

I'm so sorry, we don't have more info :(. I tried to search more issues by specified userId's, but users with this crash has not logged any other issues.
