### ISSUE TITLE
UnsatisfiedLinkError: No implementation found for long

### ISSUE THREAD

**Issue by mtrakal** [couchbase/couchbase-lite-android#1044]
http://crashes.to/s/3a667596bca
I have linked to this issue older issue from 1.2.x: #885 (but looks different)

`cbl 1.3.1-90`

```
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for long com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeOpen(java.lang.String, int, java.lang.String, boolean, boolean) (tried Java_com_couchbase_lite_internal_database_sqlite_SQLiteConnection_nativeOpen and Java_com_couchbase_lite_internal_database_sqlite_SQLiteConnection_nativeOpen__Ljava_lang_String_2ILjava_lang_String_2ZZ)
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194)
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:178)
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:461)
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:191)
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:183)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:820)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:803)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:698)
       at com.couchbase.lite.storage.SQLiteStorageEngineBase.open(SQLiteStorageEngineBase.java:70)
       at com.couchbase.lite.store.SQLiteStore.open(SQLiteStore.java:188)
       at com.couchbase.lite.Database.open(Database.java:1329)
       at com.couchbase.lite.Manager.openDatabase(Manager.java:334)
       at com.yablohn.internal.CouchBaseProvider.connectDatabase(CouchBaseProvider.java:296)
       at com.yablohn.internal.CouchBaseProvider.init(CouchBaseProvider.java:269)
       at com.yablohn.internal.CouchBaseProvider.(CouchBaseProvider.java)
       at com.yablohn.internal.CouchBaseModule.initialize(CouchBaseModule.java:22)
       at com.droid4you.application.wallet.Application.initYablohnAndVogel(Application.java:247)
       at com.droid4you.application.wallet.Application.onCreate(Application.java:236)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4911)
       at android.app.ActivityThread.access$1500(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1573)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5691)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

**Comment by hideki** [comment]
Hi @mtrakal,
UnsatisfiedLinkError could occur if native library is not provide, or method signature does not match. To investigate, we need more details. Android version, how app is installed, etc...

**Comment by mtrakal** [comment]
Hi @hideki,

Android versions and devices is visible on crashlytics. 
We don't have a chance how to know how user install apk. Primary it's from google play, a few beta testers install over Beta fabric.io app.

**Comment by hideki** [comment]
hi @mtrakal,

Many users, who face this issue, use Android 4.4.x on arm chip devices. This is typical env. I know you can not get more information than Fabric provides. I have some questions:
- Does this intermittently happen? Does restarting application work?
- Where is application installed on SD-Card?

**Comment by PrabhuKathiresan** [comment]
Hi ,
I also migrated from v-1.0.1 to v-1.3.0,
I am also facing the same issue now,

```
11-30 17:09:45.746 6356-6463/org.apache.cordova.sampleApp E/Database: ERROR: Failed to load CouchbaseLiteJavaForestDB
11-30 17:09:45.747 6356-6463/org.apache.cordova.sampleApp E/Database: Cannot load native library
11-30 17:09:45.749 6356-6463/org.apache.cordova.sampleApp E/Database: Cannot load native library
11-30 17:09:45.751 6356-6463/org.apache.cordova.sampleApp E/art: No implementation found for long com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeOpen(java.lang.String, int, java.lang.String, boolean, boolean) (tried Java_com_couchbase_lite_internal_database_sqlite_SQLiteConnection_nativeOpen and Java_com_couchbase_lite_internal_database_sqlite_SQLiteConnection_nativeOpen__Ljava_lang_String_2ILjava_lang_String_2ZZ)
11-30 17:09:45.753 6356-6463/org.apache.cordova.sampleApp W/Router: Router unable to route request to do_PUT_Database
                                                                    java.lang.reflect.InvocationTargetException
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.couchbase.lite.router.Router.start(Router.java:556)
                                                                        at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
                                                                        at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
                                                                        at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
                                                                        at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
                                                                        at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
                                                                        at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
                                                                        at java.lang.Thread.run(Thread.java:818)
                                                                     Caused by: java.lang.UnsatisfiedLinkError: No implementation found for long com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeOpen(java.lang.String, int, java.lang.String, boolean, boolean) (tried Java_com_couchbase_lite_internal_database_sqlite_SQLiteConnection_nativeOpen and Java_com_couchbase_lite_internal_database_sqlite_SQLiteConnection_nativeOpen__Ljava_lang_String_2ILjava_lang_String_2ZZ)
                                                                        at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                                                                        at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194)
                                                                        at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:178)
                                                                        at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:461)
                                                                        at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:191)
                                                                        at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:183)
                                                                        at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:820)
                                                                        at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:803)
                                                                        at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:698)
                                                                        at com.couchbase.lite.storage.SQLiteStorageEngineBase.open(SQLiteStorageEngineBase.java:70)
                                                                        at com.couchbase.lite.store.SQLiteStore.open(SQLiteStore.java:188)
                                                                        at com.couchbase.lite.Database.open(Database.java:1251)
                                                                        at com.couchbase.lite.Database.open(Database.java:1185)
                                                                        at com.couchbase.lite.router.Router.do_PUT_Database(Router.java:1118)
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                        at com.couchbase.lite.router.Router.start(Router.java:556) 
                                                                        at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141) 
                                                                        at javax.servlet.http.HttpServlet.service(HttpServlet.java:802) 
                                                                        at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251) 
                                                                        at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176) 
                                                                        at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988) 
                                                                        at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223) 
                                                                        at java.lang.Thread.run(Thread.java:818) 
11-30 17:09:45.753 6356-6463/org.apache.cordova.sampleApp V/Listener: RouterCallbackBlock.onResponseReady() START
11-30 17:09:45.753 6356-6463/org.apache.cordova.sampleApp V/Listener: RouterCallbackBlock.onResponseReady() END
11-30 17:09:45.753 6356-6463/org.apache.cordova.sampleApp V/Listener: CountDownLatch.await() START
11-30 17:09:45.753 6356-6463/org.apache.cordova.sampleApp V/Listener: CountDownLatch.await() END
11-30 17:09:45.798 6356-6356/org.apache.cordova.sampleApp D/SystemWebChromeClient: file:///android_asset/www/js/index_1.js: Line 62 : error-xhr: {"readyState":4,"responseText":"{\"error\":\"not_found\",\"status\":404,\"reason\":\"Router unable to route request to do_PUT_Databasejava.lang.reflect.InvocationTargetException\"}","responseJSON":{"error":"not_found","status":404,"reason":"Router unable to route request to do_PUT_Databasejava.lang.reflect.InvocationTargetException"},"status":404,"statusText":"Not found"}
```

**Comment by hideki** [comment]
@PrabhuKathiresan,
Error message indicates the application uses ForestDB as the storage. Do you include ForestDB jar file into your Cordova app?

**Comment by PrabhuKathiresan** [comment]
Hi @hideki 

I have a AAR file of couchbase-lite-android-forestdb-1.3.1.aar

I have extracted the classes.jar from that .aar file and included into my cordova app.

Is there anything am I missing???

**Comment by hideki** [comment]
@PrabhuKathiresan,
Can you confirm if your app contains `couchbase-lite-android-sqlite-custom-x.x.x.aar`? I assume you might accidentally or intentionally delete it from your cordova app. That could cause the link error.

**Comment by PrabhuKathiresan** [comment]
HI @hideki ,

Thanks for the quick response.

Ya I have couchbase-lite-android-sqlite-custom-1.3.1.aar along withcouchbase-lite-android-sqlcipher-1.3.1.aar and i have extracted classes.jar from both this .aar file and included in my app , but I am still getting this error.

**Comment by hideki** [comment]
Hi @PrabhuKathiresan,
Can you test if issue is reproducible with using CBL for PhoneGap v1.3.1 without any customization?
`UnsatisfiedLinkError` indicates application cannot load native library.

**Comment by PrabhuKathiresan** [comment]
Ya the same issue is reproducible through CBL for PhoneGap v1.3.1 .

**Comment by hideki** [comment]
@PrabhuKathiresan,
Sorry for not responding for a while.
Do you have any update on this issue?

**Comment by hideki** [comment]
as we don't have further information. I will close this ticket. If you are still facing this issue. please reopen the ticket.

**Comment by mtrakal** [comment]
`couchBaseVersion = '1.4-38'` cbl+forest

Android 7:
Xperia Z5 Premium Dual (http://www.devicespecifications.com/en/model/b7be3640), 
OnePlus 3 (http://www.devicespecifications.com/en/model/437a3c9b), 
Nexus 5 (http://www.devicespecifications.com/en/model/3dfd2923)

Nexus 5 didn't have officially Anroid 7, user must have some custom rom. But Xperia nad OnePlus

Zperia Z5: ARMv8-A
OnePlus 3: ARMv8-A
Nexus 5: ARMv7
```
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for long com.couchbase.cbforest.Database._open(java.lang.String, int, int, byte[]) (tried Java_com_couchbase_cbforest_Database__1open and Java_com_couchbase_cbforest_Database__1open__Ljava_lang_String_2II_3B)
       at com.couchbase.cbforest.Database._open(Database.java)
       at com.couchbase.cbforest.Database.(Database.java:26)
       at com.couchbase.lite.store.ForestDBStore.open(ForestDBStore.java:158)
       at com.couchbase.lite.Database.open(Database.java:1345)
       at com.couchbase.lite.Manager.openDatabase(Manager.java:341)
```

**Comment by hideki** [comment]
@mtrakal,

It seems Zperia Z5 could load the different native library.
https://talk.sonymobile.com/t5/Xperia-Z5-Z5-Compact-Z5-Premium/Can-t-load-native-library-CPU-arch-invalid-for-this-build/td-p/1110658

The following solution could solve the problem. Can you try this?
Increase minSdkVersion to 16
https://github.com/card-io/card.io-Android-source/commit/1fca8bed0b8bc53b24244835f2445de0f38898d0

**Comment by mtrakal** [comment]
Hi @hideki,

in our app we have `minSdkVersion 16`, we don't support older devices... Sad, but it really looks as problem od specific device.
