### ISSUE TITLE
NPE when set cookie on pull replicator

### ISSUE THREAD

**Issue by vicpinm** [couchbase/couchbase-lite-android#1048]
When I call to setCookie() on my pull replicator, sometimes I get this NPE:
```
java.lang.NullPointerException: Attempt to invoke interface method 'com.couchbase.lite.internal.RevisionInternal com.couchbase.lite.store.Store.getLocalDocument(java.lang.String, java.lang.String)' on a null object reference
     at com.couchbase.lite.Database.getLocalDocument(Database.java:1837)
     at com.couchbase.lite.Database.getExistingLocalDocument(Database.java:407)
     at com.couchbase.lite.support.PersistentCookieStore.addCookie(PersistentCookieStore.java:135)
     at com.couchbase.lite.support.CouchbaseLiteHttpClientFactory.addCookies(CouchbaseLiteHttpClientFactory.java:112)
     at com.couchbase.lite.replicator.ReplicationInternal.setCookie(ReplicationInternal.java:1641)
     at com.couchbase.lite.replicator.PullerInternal.setCookie(PullerInternal.java:48)
     at com.couchbase.lite.replicator.Replication.setCookie(Replication.java:731)
```
Couchbase lite version: 1.2.1

**Comment by hideki** [comment]
@vicpinm,
It seems store variable is null. 
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.2.1/src/main/java/com/couchbase/lite/Database.java#L1837

Can verify if v1.3.1 still has this issue?

Thanks,
Hideki

**Comment by vicpinm** [comment]
I still can't reproduce this error with v1.3.1, it seems to be random. If I get this again, I will let you know. Thanks you very much.

**Comment by djpongh** [comment]
Closing. If you can repro, reopen with the additional info.

**Comment by vicpinm** [comment]
Hi, after a lot of tests, I can verify that the NPE is still present in 1.3.1. It happens when I open my app, and start sincronization process: 

1. I create a Replication object instance with createPullReplication
2. I set some channels to replicator with setChannels() method
3. I set the cookie with setCookie() method -> NullPointerException (stack trace in the first message)

This error happens in the 5% of the cases more o less. When I capture this exception, I retry this process, creating a new pull replicatior object and so on. When I retry this process, then setCookie() method doesn't throw this exception. However, replicator doesn't pull anything. I have observed this behaviour in this second attemp:

PULL replication event. Source: Replication{URL, pull} Transition: INITIAL -> RUNNING Total changes: 0 Completed changes: 0
PULL replication event. Source: Replication{URL, pull} Transition: INITIAL -> RUNNING Total changes: 0 Completed changes: 0
PULL replication event. Source: Replication{URL, pull} Transition: INITIAL -> RUNNING Total changes: 0 Completed changes: 0
PULL replication event. Source: Replication{URL, pull} Transition: INITIAL -> RUNNING Total changes: 0 Completed changes: 0
PULL replication event. Source: Replication{URL, pull} Transition: RUNNING -> STOPPED Total changes: 0 Completed changes: 0
PULL replication event. Source: Replication{URL, pull} Transition: RUNNING -> STOPPED Total changes: 0 Completed changes: 0
PULL replication event. Source: Replication{URL, pull} Transition: RUNNING -> STOPPED Total changes: 0 Completed changes: 0
PULL replication event. Source: Replication{URL, pull} Transition: RUNNING -> STOPPED Total changes: 0 Completed changes: 0
PULL replication event. Source: Replication{URL, pull} Transition: RUNNING -> STOPPED Total changes: 0 Completed changes: 0

As you can see, replicator doesn't pull anything, and It doesn't reach the IDLE state.

**Comment by PaoloneM** [comment]
Same random problem with 1.3.1 as described by @vicpinm

**Comment by pasin** [comment]
I have reviewed the code and the only scenario that the store variable is null is when the database is closed. @vicpinm and @PaoloneM if this issue is still a concern, could you please check if the database has been closed or not. Attaching the log file with Database and Sync Verbose enabled will be really helpful.
