### ISSUE TITLE
ForestDB RegularQuery api throwing CouchbaseLiteException intermittently

### ISSUE THREAD

**Issue by enicolasToast** [couchbase/couchbase-lite-android#1066]
Hi all,

We're using couchbase-lite-android version 1.4-12 & couchbase-lite-android-forestdb version 1.4.-12 and we're getting the following error from crashalytics.  (Crashalytics apparantly didn't catch the exception message).  We also caught this while using 1.3.1-90.  I'm unable to catch a repro of this myself manually unfortunately.

Caused by com.couchbase.lite.CouchbaseLiteException
       at com.couchbase.lite.store.ForestDBViewStore.regularQuery(ForestDBViewStore.java:443)
       at com.couchbase.lite.View.query(View.java:358)
       at com.couchbase.lite.Database.queryViewNamed(Database.java:2457)
       at com.couchbase.lite.Query.run(Query.java:446)

**Comment by hideki** [comment]
@enicolasToast 
Thank you for reporting the issue. 
To identify the issue, we need more detailed information. Does `crashalytics` provide the detailed info?
Thanks!

**Comment by enicolasToast** [comment]
@hideki It does not since we wrap the exception in a generic exception of our own.  I can change the logic to also log the internal couchbaselitexception message to crashalytics as well.  Would that be enough information for further investigation ?

Note: Since we can't reproduce this too easily, we would have to deploy this to our customers and wait for a bit (maybe a week) before we get data.

**Comment by hideki** [comment]
@enicolasToast Thank you for your support!

> Would that be enough information for further investigation?

I can not clearly say yes or no.  Further information could help to investigate the issue.
