### ISSUE TITLE
NPE... Error while waiting for pending futures [1.4-3]

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#1067]
```
E/Batcher: com.couchbase.lite.support.Batcher@41b82ec0: Error while waiting for pending futures
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:223)
    at java.util.concurrent.FutureTask.get(FutureTask.java:82)
    at com.couchbase.lite.support.Batcher.waitForPendingFutures(Batcher.java:256)
    at com.couchbase.lite.replicator.ReplicationInternal.waitBatcherCompleted(ReplicationInternal.java:1965)
    at com.couchbase.lite.replicator.PullerInternal.waitDownloadsToInsertBatcherCompleted(PullerInternal.java:1026)
    at com.couchbase.lite.replicator.PullerInternal.waitForAllTasksCompleted(PullerInternal.java:1021)
    at com.couchbase.lite.replicator.ReplicationInternal.waitForPendingFutures(ReplicationInternal.java:1920)
    at com.couchbase.lite.replicator.PullerInternal$14.run(PullerInternal.java:935)
    at java.lang.Thread.run(Thread.java:856)
 Caused by: java.lang.NullPointerException
    at com.couchbase.lite.replicator.PullerInternal.insertDownloads(PullerInternal.java:560)
    at com.couchbase.lite.replicator.PullerInternal$2.process(PullerInternal.java:127)
    at com.couchbase.lite.support.Batcher.processNow(Batcher.java:396)
    at com.couchbase.lite.support.Batcher.access$300(Batcher.java:29)
    at com.couchbase.lite.support.Batcher$2.run(Batcher.java:330)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856) 
```

**Comment by djpongh** [comment]
Any chance you can get us some logs?

**Comment by npomfret** [comment]
sorry, this hasn't come back since.

**Comment by djpongh** [comment]
OK, closing. Feel free to reopen if you hit it again.
