### ISSUE TITLE
Forest locked when start app (ANR)

### ISSUE THREAD

**Issue by mtrakal** [couchbase/couchbase-lite-android#1068]
CBL + forest: `1.3.1-91`
Now we try to upgrade to latest 1.4-29 but not released yet, so we don't have info...
We have a lot of issues with not synced documents (exists only locally and never synced on servers) with 1.3.1-91.

Note to self: ticket 2034

Some users have issue with app not start:
```
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x7565ba68 self=0x7300295a00
  | sysTid=28649 nice=-10 cgrp=default sched=0/0 handle=0x7304225a98
  | state=D schedstat=( 9129632465 272836487 102281 ) utm=449 stm=462 core=4 HZ=100
  | stack=0x7ffe338000-0x7ffe33a000 stackSize=8MB
  | held mutexes=
  kernel: __switch_to+0x8c/0x98
  kernel: sleep_on_page_killable+0x8/0x44
  kernel: __lock_page_killable+0x6c/0x90
  kernel: generic_file_aio_read+0x42c/0x690
  kernel: do_sync_read+0x8c/0xd4
  kernel: vfs_read+0xa0/0x12c
  kernel: SyS_pread64+0x6c/0xb0
  kernel: cpu_switch_to+0x48/0x4c
  native: #00 pc 000000000006b544  /system/lib64/libc.so (pread+8)
  native: #01 pc 00000000000c0230  /data/app/com.droid4you.application.wallet-1/lib/arm64/libCouchbaseLiteJavaForestDB.so (_Z20_filemgr_linux_preadiPvml+48)
  native: #02 pc 00000000000baadc  /data/app/com.droid4you.application.wallet-1/lib/arm64/libCouchbaseLiteJavaForestDB.so (???)
  native: #03 pc 00000000000ba3b4  /data/app/com.droid4you.application.wallet-1/lib/arm64/libCouchbaseLiteJavaForestDB.so (filemgr_open+1976)
  native: #04 pc 00000000000c1028  /data/app/com.droid4you.application.wallet-1/lib/arm64/libCouchbaseLiteJavaForestDB.so (_fdb_open+536)
  native: #05 pc 00000000000c1e1c  /data/app/com.droid4you.application.wallet-1/lib/arm64/libCouchbaseLiteJavaForestDB.so (_fdb_open+4108)
  native: #06 pc 00000000000c0d84  /data/app/com.droid4you.application.wallet-1/lib/arm64/libCouchbaseLiteJavaForestDB.so (fdb_open+312)
  native: #07 pc 00000000000e6a28  /data/app/com.droid4you.application.wallet-1/lib/arm64/libCouchbaseLiteJavaForestDB.so (_ZN8cbforest8Database6reopenEv+36)
  native: #08 pc 00000000000e6818  /data/app/com.droid4you.application.wallet-1/lib/arm64/libCouchbaseLiteJavaForestDB.so (_ZN8cbforest8DatabaseC2ESsRK10fdb_config+244)
  native: #09 pc 0000000000102850  /data/app/com.droid4you.application.wallet-1/lib/arm64/libCouchbaseLiteJavaForestDB.so (_ZN10c4DatabaseC1ESsRK10fdb_config+64)
  native: #10 pc 0000000000102e34  /data/app/com.droid4you.application.wallet-1/lib/arm64/libCouchbaseLiteJavaForestDB.so (c4db_open+208)
  native: #11 pc 0000000000110c38  /data/app/com.droid4you.application.wallet-1/lib/arm64/libCouchbaseLiteJavaForestDB.so (Java_com_couchbase_cbforest_Database__1open+112)
  native: #12 pc 00000000000793f8  /data/app/com.droid4you.application.wallet-1/oat/arm64/base.odex (Java_com_couchbase_cbforest_Database__1open__Ljava_lang_String_2II_3B+196)
  at com.couchbase.cbforest.Database._open(Native method)
  at com.couchbase.cbforest.Database.<init>(Database.java:26)
  at com.couchbase.lite.store.ForestDBStore.open(ForestDBStore.java:158)
  at com.couchbase.lite.Database.open(Database.java:1329)
  - locked <0x050d3397> (a com.couchbase.lite.Database)
  at com.couchbase.lite.Manager.openDatabase(Manager.java:334)
  at com.yablohn.internal.CouchBaseProvider.connectDatabase(CouchBaseProvider.java:304)
```

[complete_stacktrace.txt](https://github.com/couchbase/couchbase-lite-android/files/734867/complete_stacktrace.txt)

Just freeze on splashscreen. We call openDatabse in `Application.java` at end of `onCreate` method.

**Comment by hideki** [comment]
@mtrakal Could you please provide Android OS version and some other device information?

**Comment by hideki** [comment]
@mtrakal I got some additional info from the attached stacktrace file.

**Comment by hideki** [comment]
Hi @mtrakal,

cc: @hisundar  

I talked with ForestDB engineer. According to the native level stacktrace, the app hangs at Kernel level. It seems other process access disk/map area and locks it. This indicates there is a bug in Android's Linux Kernel.
```
  kernel: sleep_on_page_killable+0x8/0x44
  kernel: __lock_page_killable+0x6c/0x90
```

According to the following page, Linux kernel had the same problem before. It was fixed with 3.0.80. But there is a possibility the same bug resurfaced with latest Kernel Android 7.1 includes.
https://www.suse.com/support/kb/doc?id=7012769

Android OS version and Linux Kernel mapping table.
http://android.stackexchange.com/questions/51651/which-android-runs-which-linux-kernel

We believe OS cache is bad state or inappropriate state. So rebooting Android could clear this state. Also end user might try to clear Application cache.

Thanks,
Hideki

**Comment by mtrakal** [comment]
Restarting phone helped to user. 👍 


Can you post to higher places where they can solve it? I don't have experience with reporting kernel issues :/ :)
