### ISSUE TITLE
"RemoteRequestResponseException: Unauthorised" - but with valid session [cbl 1.3.1-90]

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#1077]
I'm getting a 401 from my pull replication task.  I've tested the session id (see below) and it's valid.

```
02-18 08:35:38.973 28186-28293/? D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry$1@41e1be48: RemoteRequestRetry inner request finished, url: https://pomochat-sg-read-dev.pomocorp.com/sync_gateway/_local/ce695a5eda223b8dff37c80010f4c271ef30a0e6
02-18 08:35:38.973 28186-28293/? D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry@41fa5cd0: isTransientError, httpResponse: Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://pomochat-sg-read-dev.pomocorp.com/sync_gateway/_local/ce695a5eda223b8dff37c80010f4c271ef30a0e6} e: com.couchbase.lite.replicator.RemoteRequestResponseException: Unauthorized
02-18 08:35:38.983 28186-28293/? D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry@41fa5cd0: isTransientError, status code: 401
02-18 08:35:38.983 28186-28293/? D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry@41fa5cd0: isTransientError, return false
02-18 08:35:38.983 28186-28293/? D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry$1@41e1be48: RemoteRequestRetry failed, non-transient error.  NOT retrying. url: https://pomochat-sg-read-dev.pomocorp.com/sync_gateway/_local/ce695a5eda223b8dff37c80010f4c271ef30a0e6
02-18 08:35:39.003 28186-28293/? W/Sync: com.couchbase.lite.replicator.ReplicationInternal$11@41fabac0: error getting remote checkpoint
 com.couchbase.lite.replicator.RemoteRequestResponseException: Unauthorized
     at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:265)
     at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
     at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
     at java.lang.Thread.run(Thread.java:856)
02-18 08:35:39.003 28186-28293/? W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, ce695}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: Unauthorized

```

..but it's valid, and should be for a month:

```
curl -X GET -H "Cookie: SyncGatewaySession=2a7d25722a914a4e23b48da25e166857305ba2d0" "https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/"
{"committed_update_seq":731792,"compact_running":false,"db_name":"sync_gateway","disk_format_version":0,"instance_start_time":1487248961691247,"purge_seq":0,"state":"Online","update_seq":731792}
```

And I see this in the sg logs:

```
2017-02-18T08:42:56.916Z HTTP:  #153737: GET /sync_gateway/_local/ce695a5eda223b8dff37c80010f4c271ef30a0e6
2017-02-18T08:42:56.918Z HTTP: #153737:     --> 401 Login required  (6.4 ms)
```

I've tried creating a new session, but it doesn't help.  And the app also uses the same session to download docs directly from the sync-gateway, which works fine.  I'm starting the continuous replications by using the `Cookie` header.

Any idea what's going on?

I don't recognise the url it's trying to access, what is `.../_local/ce695a5eda223b8dff37c80010f4c271ef30a0e6`?

**Comment by npomfret** [comment]
FYI - i upgraded my client to 1.4 and the error messages changed a little:

```
02-22 10:24:14.987 10245-10357/? V/RemoteRequest: com.couchbase.lite.replicator.RemoteRequest {GET, https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/_local/195629a5aa17f2e27b6bdb06b4b72c8654d3f636}: RemoteRequest called httpClient.execute, url: https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/_local/195629a5aa17f2e27b6bdb06b4b72c8654d3f636
02-22 10:24:14.987 10245-10357/? V/Sync: serverVersion: Couchbase Sync Gateway/1.4
02-22 10:24:14.987 10245-10357/? D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry$1@41e19598: RemoteRequestRetry inner request finished, url: https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/_local/195629a5aa17f2e27b6bdb06b4b72c8654d3f636
02-22 10:24:14.987 10245-10357/? D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry@41f533b8: isTransientError, httpResponse: Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/_local/195629a5aa17f2e27b6bdb06b4b72c8654d3f636} e: com.couchbase.lite.replicator.RemoteRequestResponseException: {code=401, userInfo={AuthChallenge={realm=Couchbase Sync Gateway, WWW-Authenticate=Basic realm="Couchbase Sync Gateway", Scheme=Basic}}, message=Unauthorized}
02-22 10:24:14.987 10245-10357/? D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry@41f533b8: isTransientError, status code: 401
02-22 10:24:14.987 10245-10357/? D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry@41f533b8: isTransientError, return false
02-22 10:24:14.987 10245-10357/? D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry$1@41e19598: RemoteRequestRetry failed, non-transient error.  NOT retrying. url: https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/_local/195629a5aa17f2e27b6bdb06b4b72c8654d3f636
02-22 10:24:14.997 10245-10357/? W/Sync: com.couchbase.lite.replicator.ReplicationInternal$11@41fd4ea8: error getting remote checkpoint
                                         com.couchbase.lite.replicator.RemoteRequestResponseException: {code=401, userInfo={AuthChallenge={realm=Couchbase Sync Gateway, WWW-Authenticate=Basic realm="Couchbase Sync Gateway", Scheme=Basic}}, message=Unauthorized}
                                             at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:276)
                                             at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
                                             at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
                                             at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                             at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                             at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
                                             at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                             at java.lang.Thread.run(Thread.java:856)
02-22 10:24:14.997 10245-10357/? W/Sync: PusherInternal{https://pomochat-sg-write-dev.pomocorp.com/sync_gateway, push, 19562}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=401, userInfo={AuthChallenge={realm=Couchbase Sync Gateway, WWW-Authenticate=Basic realm="Couchbase Sync Gateway", Scheme=Basic}}, message=Unauthorized}
02-22 10:24:14.997 10245-10357/? D/Sync: PusherInternal{https://pomochat-sg-write-dev.pomocorp.com/sync_gateway, push, 19562} [fireTrigger()] => STOP_GRACEFUL         
```

Does this help?

**Comment by hideki** [comment]
REF: https://github.com/couchbase/sync_gateway/issues/1665

**Comment by hideki** [comment]
@npomfret, 
Can you generate valid SG session ID? I will try to reproduce it.
Also, HttpScope (https://www.tuffcode.com/) can not capture encrypted data (HTTPS/SSL). Is it possible to allow HTTP request?

**Comment by hideki** [comment]
Ticket in Sync Gateway is more active. So we could track this issue with SG ticket.

I also tested the scenario that setting SG session id by `POST /_replicate` REST command. I can not reproduce the issue.
https://github.com/couchbase/sync_gateway/issues/1665#issuecomment-281974569

I will close this ticket.

**Comment by npomfret** [comment]
I think it was down to a faulty sync-gateway.  After a restart the problem doesn't appear to be happening.
