### ISSUE TITLE
NPE during replication 1.4-44

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#1078]
Just noticed this NPE my logs during a pull replication:

```
02-22 11:24:27.301 11786-11896/? D/Sync: com.couchbase.lite.replicator.PullerInternal$9@41db93e8 insertDownloads() updating completedChangesCount from 596 -> 696 
02-22 11:24:27.401 11786-11896/? D/Sync: firing trigger: STOP_IMMEDIATE
02-22 11:24:27.401 11786-11896/? D/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, f0b4b}: saveLastSequence() called. lastSequence: 778186:688132 remoteCheckpoint: {_rev=0-6, lastSequence=778186:687955}
02-22 11:24:27.401 11786-11896/? D/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, f0b4b}: start put remote _local document.  checkpointID: f0b4b277b83350b860b6d12a6d02eadebccc86f2 body: {_rev=0-6, lastSequence=778186:688132}
02-22 11:24:27.401 11786-11896/? D/Sync: [sendAsyncRequest()] PUT => https://pomochat-sg-read-dev.pomocorp.com/sync_gateway/_local/f0b4b277b83350b860b6d12a6d02eadebccc86f2
02-22 11:24:27.481 11786-11930/? D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry$1@41dece88: RemoteRequestRetry inner request finished, url: https://pomochat-sg-read-dev.pomocorp.com/sync_gateway/_local/f0b4b277b83350b860b6d12a6d02eadebccc86f2
02-22 11:24:27.481 11786-11930/? D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry$1@41dece88: RemoteRequestRetry was successful, calling callback url: https://pomochat-sg-read-dev.pomocorp.com/sync_gateway/_local/f0b4b277b83350b860b6d12a6d02eadebccc86f2
02-22 11:24:27.481 11786-11930/? D/Sync: com.couchbase.lite.replicator.ReplicationInternal$8@41f27d00: put remote _local document request finished.  checkpointID: f0b4b277b83350b860b6d12a6d02eadebccc86f2 body: {_rev=0-6, lastSequence=778186:688132}
02-22 11:24:27.481 11786-11930/? D/Sync: com.couchbase.lite.replicator.ReplicationInternal$8@41f27d00: saved remote checkpoint, updating local checkpoint. RemoteCheckpoint: {_rev=0-7, lastSequence=778186:688132}
02-22 11:24:27.511 11786-11896/? D/Sync: State transition: STOPPING -> STOPPED (via STOP_IMMEDIATE).  this: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, f0b4b}
02-22 11:24:27.521 11786-11896/? D/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, f0b4b} inserting 84 revisions...
02-22 11:24:27.532 11786-11943/? E/Batcher: com.couchbase.lite.support.Batcher@41f3e000: Error while waiting for pending futures
                                            java.util.concurrent.ExecutionException: java.lang.NullPointerException
                                                at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:223)
                                                at java.util.concurrent.FutureTask.get(FutureTask.java:82)
                                                at com.couchbase.lite.support.Batcher.waitForPendingFutures(Batcher.java:263)
                                                at com.couchbase.lite.replicator.ReplicationInternal.waitBatcherCompleted(ReplicationInternal.java:1964)
                                                at com.couchbase.lite.replicator.PullerInternal.waitDownloadsToInsertBatcherCompleted(PullerInternal.java:1060)
                                                at com.couchbase.lite.replicator.PullerInternal.waitForAllTasksCompleted(PullerInternal.java:1055)
                                                at com.couchbase.lite.replicator.ReplicationInternal.waitForPendingFutures(ReplicationInternal.java:1919)
                                                at com.couchbase.lite.replicator.PullerInternal$14.run(PullerInternal.java:969)
                                                at java.lang.Thread.run(Thread.java:856)
                                             Caused by: java.lang.NullPointerException
                                                at com.couchbase.lite.replicator.PullerInternal.insertDownloads(PullerInternal.java:577)
                                                at com.couchbase.lite.replicator.PullerInternal$2.process(PullerInternal.java:131)
                                                at com.couchbase.lite.support.Batcher.processNow(Batcher.java:403)
                                                at com.couchbase.lite.support.Batcher.access$300(Batcher.java:29)
                                                at com.couchbase.lite.support.Batcher$2.run(Batcher.java:337)
```

**Comment by hideki** [comment]
Hi @npomfret,
Thank you for your report.
I believe `db` variable is `null` at `PullerInternal.java:577`. Could you please share the context of this issue? Did you delete the database, close the database, or stop the pull replication?
https://github.com/couchbase/couchbase-lite-java-core/blob/b688b5ac950cb5d733271fcfad1431cca2ad50da/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L577

**Comment by npomfret** [comment]
> Did you delete the database, close the database, or stop the pull replication?

No, non of the above.  But it might be related to this: https://github.com/couchbase/couchbase-lite-android/issues/1063
