### ISSUE TITLE
1.4.0 NullPointerException com.couchbase.lite.SavedRevision.getId

### ISSUE THREAD

**Issue by trr-amsiq** [couchbase/couchbase-lite-android#1090]
Hi,

Couchbase 1.4.0 seems to be way more stable than 1.3.1.
I'm experiencing a few crashes here and there. ut only on Android 7.0 and higher.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.couchbase.lite.internal.RevisionInternal.getRevID()' on a null object reference
       at com.couchbase.lite.SavedRevision.getId(SavedRevision.java:130)
       at com.couchbase.lite.Document.getRevisionFromRev(Document.java:540)
       at com.couchbase.lite.Document.getRevision(Document.java:310)
       at com.couchbase.lite.Document.getCurrentRevision(Document.java:206)
       at com.couchbase.lite.Document.getProperty(Document.java:331)
       at com.soudfa.DevUtilities.Cache.Cache.retreive(Cache.java:101)
       at com.soudfa.DevUtilities.Cache.CacheObject.load(CacheObject.java:53)
       at com.soudfa.Models.Account.Account.load(Account.java:170)
       at com.soudfa.Models.Account.Account.setOrUpdateAccount(Account.java:196)
       at com.soudfa.Fragments.Relations.RelationListFragment.didSelectRow(RelationListFragment.java:313)
       at com.soudfa.Fragments.Relations.Views.RelationListItem.container(RelationListItem.java:311)
       at com.soudfa.Fragments.Relations.Views.RelationListItem_$2.onClick(RelationListItem_.java:127)
       at android.view.View.performClick(View.java:5657)
       at android.view.View$PerformClick.run(View.java:22314)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:6217)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by djpongh** [comment]
Can you upload logs from when this happen? Thanks!

**Comment by mtrakal** [comment]
https://github.com/couchbase/couchbase-lite-android/issues/1049

Same on latest app versions. Current app version use `cbl +forest 1.4.0`

**Comment by trr-amsiq** [comment]
I do not have any logs. Haven't been able to reproduce it myself!

**Comment by hideki** [comment]
#1049 and #1090 are the same issues. However, from current information, I am not sure what caused this problem. Can you see any error before this NPE?

**Comment by mtrakal** [comment]
I'll try to find a logs that could help to reproduce. But for now I can't reproduce by myself too, just Fabric users. I'll try to spend some time with it.

**Comment by trr-amsiq** [comment]
Here is a bit more data. Huawei and Sony devices seems to be the most unstable with couch base.
[Fabric](http://crashes.to/s/4b392f32f3c)

**Comment by hideki** [comment]
Hi @trr-amsiq,

Thanks for Fabric info. Honestly, Fabric data is same with Exception you shared. We need what happened before this Exception. Also, we don't have enough knowledge about the device specific behaviors or issues.

@mtrakal usually uses the latest version of CBL and he said that he could not reproduce the issue. As we just released `1.4.0`, this issue might be fixed with it.

**Comment by trr-amsiq** [comment]
Hi @hideki,

I know that Fabric data is the same Exception as the one I shared. But I shared the so you have the possibility to see the extend of the issue.
I think you misunderstood @mtrakal, I am running the latest version of CBL as prefixed on this issue.
I think that he means that he also isn't able to reproduce it during tests and that the issue only occurs on production.

**Comment by trr-amsiq** [comment]
Hi guys,

I managed to reduce the impact of this issue by implementing a DocumentUpdater as so:

```
Document retrievedDocument = getDatabase(cache).getDocument(id);
retrievedDocument.update(new Document.DocumentUpdater() {
    @Override
    public boolean update(UnsavedRevision newRevision) {
            Map properties = newRevision.getUserProperties();
            properties.put("account", content);
            newRevision.setUserProperties(properties);
            return true;
    }
});
```

**Comment by trr-amsiq** [comment]
Any bleeding version with a fix? Cheers

**Comment by hideki** [comment]
@trr-amsiq,
We don't know the root cause of this NPE. No progress.

**Comment by Martin-Hogge** [comment]
Is it planned to fix this issue in the 1.x of CBL or should we wait for the release of 2.x? Thank's.

**Comment by hideki** [comment]
Hi @Martin-Hogge 
We don't know the root cause of this issue. If you have any info, please provide us?

CBL 2.x is completely rewritten, this issue should occur with 2.x.
