### ISSUE TITLE
 Database is locked CBL 1.4.0

### ISSUE THREAD

**Issue by trr-amsiq** [couchbase/couchbase-lite-android#1127]
Getting this bug since switching to 1.4.0

The crash happens only in the start up fase of the app.

```
Fatal Exception: com.couchbase.lite.internal.database.sqlite.exception.SQLiteDatabaseLockedException: database is locked (code 5)
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:486)
       at com.couchbase.lite.internal.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:330)
       at com.couchbase.lite.internal.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:305)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:499)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:410)
       at com.couchbase.lite.storage.SQLiteStorageEngineBase.beginTransaction(SQLiteStorageEngineBase.java:150)
       at com.couchbase.lite.store.SQLiteStore.beginTransaction(SQLiteStore.java:2363)
       at com.couchbase.lite.store.SQLiteStore.add(SQLiteStore.java:1427)
       at com.couchbase.lite.Database.put(Database.java:1996)
       at com.couchbase.lite.Database.putRevision(Database.java:1943)
       at com.couchbase.lite.Database.putRevision(Database.java:1934)
       at com.couchbase.lite.Document.putProperties(Document.java:526)
       at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:118)
       at com.couchbase.lite.Document.update(Document.java:380)
       at com.app.DevUtilities.Cache.Cache.store(Cache.java:87)
       at com.app.DevUtilities.Cache.CacheObject.apply(CacheObject.java:35)
       at com.app.Models.AccountMeta.AccountMeta.save(AccountMeta.java:29)
       at com.app.controllers.Account.AccountController$2$1.run(AccountController.java:118)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by hideki** [comment]
Hi @trr-amsiq 

`SQLiteDatabaseLockedException` is thrown if other thread holds the write connection. CBL has re-try logic if SQLite throws the `SQLiteDatabaseLockedException`. See the below link. I assume other thread is busy to write/update document and keeps holding the write connection. CBL has one or zero write SQLite connection, and three or four read connections. maximum total connections is four. Can you check if other threads are busy to write/update?

https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/store/SQLiteStore.java#L2354-L2391

**Comment by trr-amsiq** [comment]
Hi @hideki ,

It seems that another thread is trying to write at the same time. Thanks!

**Comment by betaCode95** [comment]
HI @trr-amsiq ,
Is there a fix for this? I am facing issues due to this as many times data is not getting written to the db. On 1.4.0, the version 2.0.0 has min sdk 19, so can't move to that.

**Comment by trr-amsiq** [comment]
@betaCode95 I had too many issues with Couchbase so I migrated to Realm. Sorry

**Comment by pasin** [comment]
@betaCode95 @hideki's answer is correct. If you can share the log with Database logging, I could confirm if that is the case or not. We may be able to increate the max retry attempts and wait times in CBL if it makes sense.
