### ISSUE TITLE
CBL1.4.1 Unable to resolve host / No address associated with hostname

### ISSUE THREAD

**Issue by mtrakal** [couchbase/couchbase-lite-android#1196]
We have `couchBaseVersion = '1.4.1-63'`, and crashlytics logs a lot of (about 30 000 issues per day) with: `Non-fatal Exception: java.net.UnknownHostException: Unable to resolve host "URL_ADDRESS": No address associated with hostname`. It's just non-fatal, but I think, that replication shouldn't try requests when phone is without internet connection.

Expected behaviour: don't propagate errors about no internet connection (pause replication when no internet?) to upper application levels.

```
com.couchbase.lite.replicator.RemoteRequest.executeRequest (SourceFile:261)
com.couchbase.lite.replicator.RemoteRequest.execute (SourceFile:165)
com.couchbase.lite.replicator.RemoteRequest.run (SourceFile:105)
```

Complete log:
```
Non-fatal Exception: java.net.UnknownHostException: Unable to resolve host "URL": No address associated with hostname
       at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
       at java.net.InetAddress.getAllByName(InetAddress.java:215)
       at okhttp3.Dns$1.lookup(SourceFile:39)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(SourceFile:171)
       at okhttp3.internal.connection.RouteSelector.nextProxy(SourceFile:137)
       at okhttp3.internal.connection.RouteSelector.next(SourceFile:82)
       at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:171)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:121)
       at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:100)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:185)
       at okhttp3.RealCall.execute(SourceFile:69)
       at com.couchbase.lite.replicator.RemoteRequest.executeRequest(SourceFile:261)
       at com.couchbase.lite.replicator.RemoteRequest.execute(SourceFile:165)
       at com.couchbase.lite.replicator.RemoteRequest.run(SourceFile:105)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
       at libcore.io.Posix.android_getaddrinfo(Posix.java)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
       at java.net.InetAddress.getAllByName(InetAddress.java:215)
       at okhttp3.Dns$1.lookup(SourceFile:39)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(SourceFile:171)
       at okhttp3.internal.connection.RouteSelector.nextProxy(SourceFile:137)
       at okhttp3.internal.connection.RouteSelector.next(SourceFile:82)
       at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:171)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:121)
       at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:100)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:185)
       at okhttp3.RealCall.execute(SourceFile:69)
       at com.couchbase.lite.replicator.RemoteRequest.executeRequest(SourceFile:261)
       at com.couchbase.lite.replicator.RemoteRequest.execute(SourceFile:165)
       at com.couchbase.lite.replicator.RemoteRequest.run(SourceFile:105)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by hideki** [comment]
Hi @mtrakal,

Thank you for your feedback.

Both exceptions are caused by disconnection from the network.
- `Non-fatal Exception: java.net.UnknownHostException: Unable to resolve host "URL": No address associated with hostname` -> Device is no longer connected to the network.
- `Non-fatal Exception: java.net.SocketException: Socket operation on non-socket` -> Socket is no longer valid. 

Couchbase Lite for Android uses [ConnectivityManager](https://developer.android.com/reference/android/net/ConnectivityManager.html) to observe network state. Once the device disconnects from the network, the replicator becomes `OFFLINE` sate.

I believe the replicator already sent the request before the replicator becomes `OFFLINE` state because the replicator uses StateMachine which is asynchronous.

We will review `ConnectivityManager` and `OFFLINE/ONLINE` state change.
