### ISSUE TITLE
2.0: Replicator Requires Optional Settings

### ISSUE THREAD

**Issue by eljefe6a** [couchbase/couchbase-lite-android#1280]
If you create a `Replicator` and only set the replication type, you will get two different `NullPointerException`s and both are from `ReplicatorConfiguration.copy`. Full stack trace:
```
Caused by: java.lang.NullPointerException
at com.couchbase.lite.ReplicatorConfiguration.copy(ReplicatorConfiguration.java:180)
at com.couchbase.lite.Replicator.<init>(Replicator.java:199)
at com.couchbase.training.couchbaseevents.ReplicatingActivity.createPushReplication(ReplicatingActivity.java:106)
at com.couchbase.training.couchbaseevents.ReplicatingActivity.replicateCBL(ReplicatingActivity.java:43)
at com.couchbase.training.couchbaseevents.ReplicatingActivity.onCreate(ReplicatingActivity.java:36)
at android.app.Activity.performCreate(Activity.java:5231)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
at android.app.ActivityThread.access$800(ActivityThread.java:135) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:136) 
at android.app.ActivityThread.main(ActivityThread.java:5017) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
at dalvik.system.NativeStart.main(Native Method) 
```

To get work around exceptions, you have to add:
```
configuration.setPinnedServerCertificate(new byte[0]);
configuration.setChannels(new ArrayList<String>(0));
configuration.setDocumentIDs(new ArrayList<String>(0));
```

This will still error out because the server cert isn't valid.

The way `copy` is written, it expects server cert, channels, and document ids to be initialized.

**Comment by eljefe6a** [comment]
@hideki is there a good workaround for this in the meantime? The channels and doc ids seem to handle empty lists, but it doesn't like my empty server cert. Is there a different default server cert I can add?

**Comment by hideki** [comment]
@eljefe6a Can you set null for these parameters? If they are `null`, should not cause NPE.

```java
    public ReplicatorConfiguration copy() {
        return new ReplicatorConfiguration(
                database,
                target,
                replicatorType,
                continuous,
                conflictResolver,
                authenticator,
                pinnedServerCertificate != null ?
                        Arrays.copyOf(pinnedServerCertificate, pinnedServerCertificate.length) :
                        null,
                channels != null ? new ArrayList<>(channels) : null,
                documentIDs != null ? new ArrayList<>(documentIDs) : null);
    }
```

**Comment by hideki** [comment]
Hi @eljefe6a,

DB012 contains this check.
https://github.com/couchbase/couchbase-lite-android/blob/version/2.0.0-DB012/shared/src/main/java/com/couchbase/lite/ReplicatorConfiguration.java#L179-L193

I remembered I released DB012 more than a couple of times. I guess your dev environment has a cached of first one.

Can you delete the local cache files with following commands?
```
rm -rf ~/.gradle
``` 

This removes all cached jar files. Next time you launch Android Studio, Android Studio re-retrieve all required Jar files from the internet. It could take a time.

Hope this solves your problem.

**Comment by eljefe6a** [comment]
Confirmed. The latest version of DB012 doesn't have this issue anymore.
