### ISSUE TITLE
2.0: DocumentTest.testNoCacheNoLive() fails with NPE.

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1287]
```
java.lang.NullPointerException
at com.couchbase.lite.Database.postDatabaseChanged(Database.java:892)
at com.couchbase.lite.Database.access$000(Database.java:57)
at com.couchbase.lite.Database$1$1.run(Database.java:692)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
```

During `postDatabaseChanged()` method is called, the other thread calls `freeC4DBObserver()` method.

**Comment by hideki** [comment]
This issue is no longer reproducible. I will close this.
