### ISSUE TITLE
2.0: Query Math Function Test fails - atan2(y, x)

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1325]
http://uberjenkins.sc.couchbase.com/view/Build/job/couchbase-lite-android/418/console

```
18:28:16 com.couchbase.lite.QueryTest > testMathFunctions[emulator-5556 - 7.0] FAILED 
18:28:16 	java.lang.AssertionError: expected:<0.0066665679038682285> but was:<1.5641297588910283>
18:28:16 	at org.junit.Assert.fail(Assert.java:88)
18:28:32 
18:28:32 com.couchbase.lite.QueryTest > testMathFunctions[emulator-5554 - 4.1.2] FAILED 
18:28:32 	java.lang.AssertionError: expected:<0.0066665679038682285> but was:<1.5641297588910283>
18:28:32 	at org.junit.Assert.fail(Assert.java:88)
18:28:34 
18:28:34 com.couchbase.lite.QueryTest > testMathFunctions[emulator-5558 - 7.0] FAILED 
18:28:34 	java.lang.AssertionError: expected:<0.0066665679038682285> but was:<1.5641297588910283>
18:28:34 	at org.junit.Assert.fail(Assert.java:88)
18:29:49 :CouchbaseLite:connectedDebugAndroidTest FAILED
```

**Comment by hideki** [comment]
Function.atan2() -> Function.atan2(y, x)
