### ISSUE TITLE
Query View group by part of null key throws exception

### ISSUE THREAD

**Issue by linquize** [couchbase/couchbase-lite-android#1368]
Query View group by part of null key throws exception

Such resultset will cause exception.
```
key,value
-----------------
["A", null], 1
["B", "C"], 2
```

couchbase-lite-android 1.4.0
both sqlite and forestdb backends

https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.4.0/src/main/java/com/couchbase/lite/store/SQLiteViewStore.java#L1124
https://github.com/couchbaselabs/couchbase-lite-java-forestdb/blob/release/1.4.0/src/main/java/com/couchbase/lite/store/ForestDBViewStore.java#L802

To handle null, should use `Objects.equals(a, b)`.

**Comment by hideki** [comment]
Unit-Test: https://github.com/couchbase/couchbase-lite-android/pull/1404
PR: https://github.com/couchbaselabs/couchbase-lite-java-forestdb/pull/97
PR: https://github.com/couchbase/couchbase-lite-java-core/pull/1656

**Comment by hideki** [comment]
Info where NPE occurs
```
java.lang.NullPointerException
at com.couchbase.lite.store.SQLiteViewStore.groupTogether(SQLiteViewStore.java:1126)
at com.couchbase.lite.store.SQLiteViewStore.access$500(SQLiteViewStore.java:47)
at com.couchbase.lite.store.SQLiteViewStore$4.onRow(SQLiteViewStore.java:755)
at com.couchbase.lite.store.SQLiteViewStore.runQuery(SQLiteViewStore.java:1025)
at com.couchbase.lite.store.SQLiteViewStore.reducedQuery(SQLiteViewStore.java:748)
at com.couchbase.lite.View.query(View.java:356)
at com.couchbase.lite.ViewsTest.testViewGroupedKeyContainsNull(ViewsTest.java:3932)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:33)
at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:100)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

**Comment by linquize** [comment]
When to release 1.4.1?

**Comment by hideki** [comment]
You could verify the fix with nightly build: http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.4.1-68/

Instruction to install
https://github.com/couchbase/couchbase-lite-android#using-latest-official-release
