### ISSUE TITLE
"Delete error","Update conflict" also happens in DB015

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-android#1375]
Originally filed: https://github.com/couchbaselabs/mobile-training-todo/issues/155

in this project depended DB015, when one item is deleted, the error is "com.couchbase.todo 
```
E/LiteCore [Sync]: {3} Got error response to rev user1.b2fc4cf0-9a70-4243-b8b4-4bbda1ff4654 #2-98d2b4aa00f91b56212ce489855c7a734e9a9d31 (seq 6): HTTP 500 'Internal error: EOF'". when two client devices update the same item,the error is "8-30 12:00:12.836 29117-29117/com.couchbase.todo E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.couchbase.todo, PID: 29117
java.lang.NullPointerException
at com.couchbase.lite.ReadOnlyDocument.setC4Doc(ReadOnlyDocument.java:104)
at com.couchbase.lite.ReadOnlyDocument.selectConflictingRevision(ReadOnlyDocument.java:187)
at com.couchbase.lite.Database.resolveConflictInDocument(Database.java:643)
at com.couchbase.lite.Replicator.documentError(Replicator.java:427)
at com.couchbase.lite.Replicator.access$100(Replicator.java:35)
at com.couchbase.lite.Replicator$1$2.run(Replicator.java:397)
at android.os.Handler.handleCallback(Handler.java:808)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5292)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
at dalvik.system.NativeStart.main(Native Method)"。
```

**Comment by hideki** [comment]
Hi @loongsun,
I can not reproduce the problem with ToDo sample.
Can you provide steps to reproduce the problem?
Thanks!

**Comment by loongsun** [comment]
emailed to you with steps vedio already!

**Comment by hideki** [comment]
Hi @loongsun,
I did not receive the email. Can you resend it to me? Thanks!

**Comment by hideki** [comment]
This ticket could be duplicated with #1242

**Comment by hideki** [comment]
With [LiteCore module's fix](https://github.com/couchbase/couchbase-lite-core/commit/962c4021e431394d068a1b4582edf6565d3be145), this issue is fixed.
