### ISSUE TITLE
2.0: Replicating the conflicted document causes unexpected behavior (crash).

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1393]
```
09-11 15:57:11.014 19396-19396/? E/AndroidRuntime: FATAL EXCEPTION: main
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.couchbase.todo/com.couchbase.todo.ListsActivity}: java.lang.NullPointerException
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
     at android.app.ActivityThread.access$600(ActivityThread.java:141)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loop(Looper.java:137)
     at android.app.ActivityThread.main(ActivityThread.java:5039)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:511)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
     at dalvik.system.NativeStart.main(Native Method)
  Caused by: java.lang.NullPointerException
     at com.couchbase.lite.LiveQuery.run(LiveQuery.java:59)
     at com.couchbase.todo.LiveListsAdapter.<init>(LiveListsAdapter.java:53)
     at com.couchbase.todo.ListsActivity.onCreate(ListsActivity.java:68)
     at android.app.Activity.performCreate(Activity.java:5104)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
     at android.app.ActivityThread.access$600(ActivityThread.java:141) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
     at android.os.Handler.dispatchMessage(Handler.java:99) 
     at android.os.Looper.loop(Looper.java:137) 
     at android.app.ActivityThread.main(ActivityThread.java:5039) 
     at java.lang.reflect.Method.invokeNative(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:511) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
     at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by hideki** [comment]
REF #1394 

This could be caused by replicating conflicting document.

**Comment by hideki** [comment]
Note to Self:

It seems #1394, crash in native library, makes a new instance of `Application` which `database` variable is `null`.

**Comment by hideki** [comment]
It seems that extend the Application is not recommended. Instead, Singleton pattern should be used.

https://developer.android.com/reference/android/app/Application.html

> Note: There is normally no need to subclass Application. In most situations, static singletons can provide the same functionality in a more modular way. If your singleton needs a global context (for example to register broadcast receivers), include Context.getApplicationContext() as a Context argument when invoking your singleton's getInstance() method.
