### ISSUE TITLE
Attachment Push failed."java.io.IOException: Unable to load the blob stream for blobKey"

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-android#1435]
Hi Folks,
1)**CBL 1.4.0 used.**

2)[08/22 09:01:38.993] [30393] CBLite: ---> Added: {s919888880010_ptx1503414316983_a1503414316988_attachment.doc #2-d3a4ef4bd3626eadb271b0e0438076cc @135203} as seq 135203

**Document with attachment added.**

3)@executeRequest() Exception: java.io.IOException: Unable to load the blob stream for blobKey: 87D8CBFF1BCE9EDDC45668905B7D1085D35FE6D9.  url: https://919888880010:340668f75a4b6c18875979ca76168244@syncqc3.company.com/ptxdata/s919888880010_ptx1503414316983_a1503414316988_attachment.doc?new_edits=false
java.io.IOException: Unable to load the blob stream for blobKey: 87D8CBFF1BCE9EDDC45668905B7D1085D35FE6D9
	at com.couchbase.lite.replicator.BlobRequestBody$1.writeTo(SourceFile:81)
	at okhttp3.MultipartBody.writeOrCountBytes(SourceFile:171)
	at okhttp3.MultipartBody.writeTo(SourceFile:113)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(SourceFile:704)
	at okhttp3.internal.http.HttpEngine.readResponse(SourceFile:563)
	at okhttp3.RealCall.getResponse(SourceFile:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(SourceFile:198)
	at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:160)
	at okhttp3.RealCall.execute(SourceFile:57)
	at com.couchbase.lite.replicator.RemoteRequest.executeRequest(SourceFile:261)
	at com.couchbase.lite.replicator.RemoteRequest.execute(SourceFile:165)
	at com.couchbase.lite.replicator.RemoteRequest.run(SourceFile:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)

**java.io.IOException: Unable to load the blob stream for blobKey seen.**

@hideki pls share your thoughts.. Logs attached.

[cbl_log_0_3.txt](https://github.com/couchbase/couchbase-lite-android/files/1437610/cbl_log_0_3.txt)

Thanks
Nithin

**Comment by NitzDKoder** [comment]
Wrong project.
