### ISSUE TITLE
2.0:testMissingHost() fails on Jenkins

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1437]
```
05:08:43 com.couchbase.lite.ReplicatorTest > testMissingHost[hudson_en-US_160_WVGA_android-16_armeabi-v7a(AVD) - 4.1.2] [31mFAILED [0m
05:08:43 	CouchbaseLiteRuntimeException{domain=1, code=11, msg=A database is not open}
05:08:43 	at com.couchbase.lite.Database.mustBeOpen(Database.java:665)
05:08:43 
05:08:43 com.couchbase.lite.ReplicatorTest > testMissingHost[hudson_en-US_160_WVGA_android-16_armeabi-v7a(AVD) - 4.1.2] [31mFAILED [0m
05:08:43 	java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x8000010 (has extras) } in com.couchbase.lite.AndroidNetworkReachabilityManager$NetworkReceiver@410e2c00
05:08:43 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:765)
05:08:43 Tests on hudson_en-US_160_WVGA_android-16_armeabi-v7a(AVD) - 4.1.2 failed: Instrumentation run failed due to 'com.couchbase.lite.CouchbaseLiteRuntimeException'
05:08:47 :CouchbaseLite:connectedDebugAndroidTest FAILED
05:08:47 
05:08:47 FAILURE: Build failed with an exception.
```

**Comment by hideki** [comment]
This test is no longer valid case.
