### ISSUE TITLE
2.0: testWhereMatch() test failure

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1444]
```
01-01 00:38:11.000 3294-3307/com.couchbase.lite.test I/TestRunner: failed: testWhereMatch(com.couchbase.lite.QueryTest)
01-01 00:38:11.000 3294-3307/com.couchbase.lite.test I/TestRunner: ----- begin exception -----
01-01 00:38:11.020 3294-3307/com.couchbase.lite.test I/TestRunner: CouchbaseLiteException{domain=1, code=32, msg=left-hand side of MATCH expression must be a string}
       at com.couchbase.lite.internal.bridge.LiteCoreBridge.convertException(LiteCoreBridge.java:22)
       at com.couchbase.lite.Query.check(Query.java:255)
       at com.couchbase.lite.Query.run(Query.java:128)
       at com.couchbase.lite.QueryTest.verifyQuery(QueryTest.java:60)
       at com.couchbase.lite.QueryTest.verifyQuery(QueryTest.java:78)
       at com.couchbase.lite.QueryTest.testWhereMatch(QueryTest.java:413)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
       at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
       at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
       at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
       at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
       at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
       at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
       at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
       at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
       at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
       at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
       at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
       at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
       at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
       at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
       at org.junit.runners.Suite.runChild(Suite.java:128)
       at org.junit.runners.Suite.runChild(Suite.java:27)
       at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
       at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
       at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
       at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
       at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
       at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
       at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
       at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
       at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
       at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
       at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661)
    Caused by: LiteCoreException{domain=1, code=32, msg=left-hand side of MATCH expression must be a string}
       at com.couchbase.litecore.C4Query.init(Native Method)
       at com.couchbase.litecore.C4Query.<init>(C4Query.java:27)
       at com.couchbase.litecore.C4Database.createQuery(C4Database.java:255)
       at com.couchbase.lite.Query.check(Query.java:253)
       at com.couchbase.lite.Query.run(Query.java:128) 
       at com.couchbase.lite.QueryTest.verifyQuery(QueryTest.java:60) 
       at com.couchbase.lite.QueryTest.verifyQuery(QueryTest.java:78) 
       at com.couchbase.lite.QueryTest.testWhereMatch(QueryTest.java:413) 
       at java.lang.reflect.Method.invokeNative(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:511) 
       at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) 
       at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) 
       at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) 
       at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) 
       at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) 
       at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) 
       at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) 
       at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) 
       at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) 
       at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) 
       at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) 
       at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) 
       at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) 
       at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) 
       at org.junit.runners.ParentRunner.run(ParentRunner.java:363) 
       at org.junit.runners.Suite.runChild(Suite.java:128) 
       at org.junit.runners.Suite.runChild(Suite.java:27) 
       at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) 
       at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) 
       at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) 
       at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) 
       at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) 
       at org.junit.runners.ParentRunner.run(ParentRunner.java:363) 
       at org.junit.runner.JUnitCore.run(JUnitCore.java:137) 
       at org.junit.runner.JUnitCore.run(JUnitCore.java:115) 
       at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59) 
       at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262) 
       at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661) 
01-01 00:38:11.020 3294-3307/com.couchbase.lite.test I/TestRunner: ----- end exception -----
01-01 00:38:11.050 3294-3307/com.couchbase.lite.test I/TestRunner: finished: testWhereMatch(com.couchbase.lite.QueryTest)
```

**Comment by hideki** [comment]
duplicated with #1445 
close this ticket
