### ISSUE TITLE
Deleting a document from Database API, doesn't delete the reference of the doc

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-android#1449]
I've delete a document using delete(Document document) method. The method executed properly. However, when running the getDocument(String) method with the deleted document name, I got the reference to the document instead of null, as mentioned in API doc.
```
public void delete(Document document)
            throws CouchbaseLiteException
Delete the givin document. All properties are removed, and subsequent calls to getDocument(String) will return null. Deletion adds a special "tombstone" revision to the database, as bookkeeping so that the change can be replicated to other databases. Thus, it does not free up all of the disk space occupied by the document. To delete a document entirely (but without the ability to replicate this), use purge(Document).
Parameters:
document -
Throws:
CouchbaseLiteException
```

**Comment by hideki** [comment]
Issue is not reproducible with master branch
Following test covers this scenario.
https://github.com/couchbase/couchbase-lite-android/commit/7a751c206ec78e5cedf3ddf3f4ba5c002a1f491c

**Comment by hrajput89** [comment]
I'm still facing this issue. The problem arises when I tries to delete a mutable document.

This is the way I'm creating a mutable doc 

> public MutableDocument create(Args args) {
>         String id = args.get("id");
>         Map<String, Object> dictionary = args.get("dictionary");
> 
>         if (id != null) {
>             if (dictionary == null) {
>                 return new MutableDocument(id);
>             } else {
>                 return new MutableDocument(id, dictionary);
>             }
>         } else {
>             if (dictionary == null) {
>                 return new MutableDocument();
>             } else {
>                 return new MutableDocument(dictionary);
>             }
>         }
>     }

and this is my delete method 

>     public void delete(Args args) throws CouchbaseLiteException {
>         Database database = args.get("database");
>         Document document = args.get("document");
>         database.delete(document);
>    }
>

Error:

> I/LiteCore [DB]: Opening DataFile /data/user/0/com.example.hemant.coucbaselitesampleapp/files/3.cblite2/db.sqlite3
> I/System.out: java.lang.reflect.InvocationTargetException
> I/System.out:     at java.lang.reflect.Method.invoke(Native Method)
> I/System.out:     at com.couchbase.CouchbaseLiteServ.server.Server.handle(Server.java:169)
> I/System.out:     at org.nanohttpd.protocols.http.HTTPSession.execute(HTTPSession.java:421)
> I/System.out:     at org.nanohttpd.protocols.http.ClientHandler.run(ClientHandler.java:75)
> I/System.out:     at java.lang.Thread.run(Thread.java:761)
> I/System.out: Caused by: CouchbaseLiteException{domain=1000, code=404, msg=null}
> I/System.out:     at com.couchbase.lite.Database.save(Database.java:1121)
> I/System.out:     at com.couchbase.lite.Database.delete(Database.java:274)
> I/System.out:     at com.couchbase.CouchbaseLiteServ.server.RequestHandler.DatabaseRequestHandler.delete(DatabaseRequestHandler.java:122)
> I/System.out: 	... 5 more

however, if I retrieve the doc using below method, I'm able to delete the doc.

> public void delete(Args args) throws CouchbaseLiteException {
>         Database database = args.get("database");
>         Document document = args.get("document");
>         Document doc = database.getDocument(document.getId());
>         database.delete(doc);
>    }

**Comment by snej** [comment]
This is likely the same as couchbase/couchbase-lite-ios/issues/2003 — you haven't shown the code that saves the document, but in that code you need to update your Document reference to the Document returned by the Database.save method. The original Document instance does not reflect the save.
