### ISSUE TITLE
Delete database method works inconsitently 

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-android#1451]
After creating a database, if I delete DB immediately, sometimes It failed with below error.
```
I/LiteCore [DB]: Opening DataFile /data/user/0/com.example.hemant.coucbaselitesampleapp/files/foo.cblite2/db.sqlite3
I/System.out: java.lang.reflect.InvocationTargetException
I/System.out:     at java.lang.reflect.Method.invoke(Native Method)
I/System.out:     at com.couchbase.CouchbaseLiteServ.server.Server.handle(Server.java:100)
I/System.out:     at org.nanohttpd.protocols.http.HTTPSession.execute(HTTPSession.java:421)
I/System.out:     at org.nanohttpd.protocols.http.ClientHandler.run(ClientHandler.java:75)
I/System.out:     at java.lang.Thread.run(Thread.java:761)
I/System.out: Caused by: CouchbaseLiteException{domain=1, code=24, msg=database busy/locked}
I/System.out:     at com.couchbase.lite.internal.bridge.LiteCoreBridge.convertException(LiteCoreBridge.java:22)
I/System.out:     at com.couchbase.lite.Database.deleteC4DB(Database.java:893)
I/System.out:     at com.couchbase.lite.Database.delete(Database.java:441)
I/System.out:     at com.couchbase.CouchbaseLiteServ.server.DatabaseRequestHandler.deleteDB(DatabaseRequestHandler.java:88)
I/System.out: 	... 5 more
I/System.out: Caused by: LiteCoreException{domain=1, code=24, msg=database busy/locked}
I/System.out:     at com.couchbase.litecore.C4Database.delete(Native Method)
I/System.out:     at com.couchbase.litecore.C4Database.delete(C4Database.java:56)
I/System.out:     at com.couchbase.lite.Database.deleteC4DB(Database.java:891)
I/System.out: 	... 7 more
```

**Comment by hideki** [comment]
Hi @hrajput89,
Can you capture` CouchbaseLiteException{domain=1, code=24, msg=database busy/locked}` exception? As error message tell, database file is busy.  please retry later?
