### ISSUE TITLE
Push replication in peer to peer 

### ISSUE THREAD

**Issue by shwetankb11** [couchbase/couchbase-lite-android#1478]
Connection type: Peer to Peer

Sometimes when I change a document in a device it says push is Active and it doesn't come back to Idle.

and i am getting below error: 

12-15 13:02:56.435 16685-17331/com.android.***** W/RemoteRequest: com.couchbase.lite.replicator.RemoteRequest {GET, http://192.168.43.1:55000/localdb/_local/a1b9fc127fcf41699825f278d45a08120a8bd44a}: executeRequest() Exception: java.net.SocketTimeoutException.  url: http://192.168.43.1:55000/localdb/_local/a1b9fc127fcf41699825f278d45a08120a8bd44a
                                                                    java.net.SocketTimeoutException
                                                                        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
                                                                        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                                        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                        at okio.Okio$2.read(Okio.java:139)
                                                                        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
                                                                        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
                                                                        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
                                                                        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
                                                                        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
                                                                        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                        at okhttp3.RealCall.execute(RealCall.java:69)
                                                                        at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:261)
                                                                        at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
                                                                        at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                        at java.lang.Thread.run(Thread.java:818)
12-15 13:02:56.435 16685-17331/com.android.***** W/Sync: PusherInternal{http://192.168.43.1:55000/localdb, push, a1b9f}: Progress: set error = java.net.SocketTimeoutException

**Comment by hideki** [comment]
@shwetankb11,
Do you test Peer to Peer with good network condition? or not?
It seems a connection between two devices is disconnected. But push replicator (Socket) cannot detect it till SocketTimeoutException is thrown.

**Comment by shwetankb11** [comment]
Yes both the replication were working at that moment.

**Comment by shwetankb11** [comment]
I think if pull replication is working fine then the connection is good.
Please correct me if i am wrong.

**Comment by hideki** [comment]
Can you observe any error on another device?

**Comment by shwetankb11** [comment]
No there is no error on the other device.

**Comment by hideki** [comment]
> there is no error on the other device.

There are two possibilities:
- From the stack trace, I believe the socket connection for push replication is disconnected, but push replicator could not detect disconnection till Exception is thrown.
- On the other device, Listener (Router) is running to handle the request from the replicator. It could hang or causes the problem without printing error. Then it does not send the response.

NOTE: We need the reproducible environment to diagnose this problem.
