### ISSUE TITLE
Sync with Https not working

### ISSUE THREAD

**Issue by RobinJespersen** [couchbase/couchbase-lite-android#1481]
I tried to sync to a remote db using https and got this error:
```

Sync error: java.net.ProtocolException: Expected ':status' header not present
  java.net.ProtocolException: Expected ':status' header not present
      at okhttp3.internal.http.Http2xStream.readHttp2HeadersList(Http2xStream.java:267)
      at okhttp3.internal.http.Http2xStream.readResponseHeaders(Http2xStream.java:150)
      at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
      at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
      at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
      at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
      at okhttp3.RealCall.getResponse(RealCall.java:244)
      at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
      at okhttp3.RealCall.execute(RealCall.java:57)
      at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:250)
      at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
      at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
      at java.lang.Thread.run(Thread.java:761)

```

My remote db is behind a proxy server (https://github.com/jwilder/nginx-proxy) so I assume this is the reason:
https://trac.nginx.org/nginx/ticket/1397

Is there a reason why okhttp version is set to 3.3.1 or can it be updated to 3.9.1 (latest)?

(original issue)
https://github.com/couchbaselabs/nativescript-couchbase/issues/72

**Comment by hideki** [comment]
@RobinJespersen,
As you consider, the proxy could strip the header in the response.

> Is there a reason why okhttp version is set to 3.3.1 or can it be updated to 3.9.1 (latest)?

you could update to the latest. It might require recompiling with the latest version of okhttp.

**Comment by djpongh** [comment]
Hideki's suggestion should work for you.
