### ISSUE TITLE
1.4: P2P - Socket timeout error - make syncing slow

### ISSUE THREAD

**Issue by pkjvit** [couchbase/couchbase-lite-android#1487]
In P2P Connection, I am getting continuos warning for socket time out while pull/push replication, after this warning replication automatically starts retrying but It makes syncing very slow.

Please refer following logs.

**Android Monitor Log**
java.net.SocketTimeoutException: timeout
                                      at okio.Okio$4.newTimeoutException(Okio.java:230)
                                      at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
                                      at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
                                      at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
                                      at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
                                      at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
                                      at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
                                      at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                      at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                      at okhttp3.RealCall.execute(RealCall.java:69)
                                      at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:261)
                                      at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
                                      at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                      at java.lang.Thread.run(Thread.java:762)
                                   Caused by: java.net.SocketException: Socket closed
                                      at java.net.SocketInputStream.socketRead0(Native Method)
                                      at java.net.SocketInputStream.read(SocketInputStream.java:151)
                                      at java.net.SocketInputStream.read(SocketInputStream.java:120)
                                      at okio.Okio$2.read(Okio.java:139)
                                      at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
                                      at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345) 
                                      at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217) 
                                      at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211) 
                                      at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189) 
                                      at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75) 
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                      at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) 
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) 
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) 
                                      at okhttp3.RealCall.execute(RealCall.java:69) 
                                      at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:261) 
                                      at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165) 
                                      at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105) 
                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                      at java.lang.Thread.run(Thread.java:762)

**Comment by hideki** [comment]
`java.net.SocketTimeoutException: timeout` is usually caused by the other device disconnects the connection. But the device, which encounters an error, did not recognize it. 
Was connection well between two devices?

**Comment by pkjvit** [comment]
Thanks for quick response!!
I have checked in other application it's work fine so I think connection between both devices are good. and If connection issue then replication status should be **OFFLINE** but in my case replication status is **ACTIVE** it means connection is good. Correct me If I am wrong.

**Comment by pkjvit** [comment]
This time warning comes with change tracker and don't know why it's give **OneShot** status as we are running **Continuous** replication.
After this warning syncing start again if I changes in server device(hotspot) cause of that changes client device(wifi) request for pull and sync but in slow way.

please refer following 
**Android monitor Log**
12-20 19:50:10.165 28886-29732/com.android.gangway W/ChangeTracker: ChangeTracker{http://192.168.43.1:55000/nclqagangway, OneShot, @aba463f}: Exception in change tracker
                                                                    java.net.SocketTimeoutException
                                                                        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
                                                                        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                                        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                        at okio.Okio$2.read(Okio.java:139)
                                                                        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
                                                                        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
                                                                        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
                                                                        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
                                                                        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
                                                                        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                        at okhttp3.RealCall.execute(RealCall.java:69)
                                                                        at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:336)
                                                                        at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:246)
                                                                        at java.lang.Thread.run(Thread.java:818)

**Comment by hideki** [comment]
@pkjvit 
In general, Listener, which is on another device, sends heart-beat, which is CRLF, to the replicator before socket timeout occurs. Theoretically, the replicator does not cause `SocketTimeoutException`.
I wonder if another device has dead-lock, crash, or something. And it might cause this problem.
Can you observe any error message on the other device?
