### ISSUE TITLE
Not able to connect to SG over blip protocol  

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-android#1495]
I'm using android APIs(DB21) to connect to SG for replication over blip protocol. After setting the configuration of Replicator, when I call start function of replicator API, I got below error code.

> I/LiteCore [BLIP]: {N8litecore4blip10ConnectionE#3}==> N8litecore4blip10ConnectionE ->blip:172.16.1.163:4985/db/_blipsync
I/LiteCore [BLIP]: {N8litecore4blip10ConnectionE#3} Opening connection...
I/LiteCoreJNI: [NATIVE] C4Replicator.create() repl -> 0x0xd22f2580
I/LiteCoreJNI: [NATIVE] C4Replicator.getStatus() repl -> 0xd22f2580
E/C4Socket: C4Socket.callback.open() socket -> 0xd39455a8, scheme -> blip, hostname -> 172.16.1.163, port -> 4985, path -> /db/_blipsync
E/C4Socket: optionsFleece: not null
E/C4Socket: options = {channels=[ABC], auth={username=autotest, type=Basic, password=password}, headers={User-Agent=CouchbaseLite/2.0.0-231 (Java; Android 7.1.1; Google Pixel XL - 7.1.0 - API 25 - 1440x2560) Build/0 Commit/08db03d}, WS-Protocols=BLIP}
E/Sync: Replicator[<-> blip://172.16.1.163:4985/db] is connecting, progress 0/0, error: null
I/LiteCoreJNI: [NATIVE] C4Replicator.getResponseHeaders() repl -> 0xd22f2580
E/Sync: statusChanged() c4Status -> C4ReplicatorStatus{activityLevel=2, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=0, errorCode=0, errorInternalInfo=0}
E/Sync: Replicator[<-> blip://172.16.1.163:4985/db] is connecting, progress 0/0, error: null
E/WebSocket: WebSocketListener.onFailure() response -> Response{protocol=http/1.1, code=404, message=Not Found, url=http://172.16.1.163:4985/db/_blipsync}
             java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
                 at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:219)
                 at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:186)
                 at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
                 at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                 at java.lang.Thread.run(Thread.java:761)
W/LiteCore [WS]: {N8litecore9websocket12C4SocketImplE#2}==> N8litecore9websocket12C4SocketImplE blip:172.16.1.163:4985/db/_blipsync
W/LiteCore [WS]: {N8litecore9websocket12C4SocketImplE#2} WebSocket closed abnormally with status 404
I/LiteCore [WS]: {N8litecore9websocket12C4SocketImplE#2} sent 0 bytes, rcvd 0, in 0.000 sec (-nan/sec, -nan/sec)
I/LiteCore [BLIP]: {N8litecore4blip10ConnectionE#3} Closed with WebSocket status 404: (unknown WebSocket status)
I/LiteCore [Sync]: {Repl#4}==> N8litecore4repl10ReplicatorE ->blip:172.16.1.163:4985/db/_blipsync
I/LiteCore [Sync]: {Repl#4} Connection closed with WebSocket status 404: "(unknown WebSocket status)"
E/LiteCore [Sync]: {Repl#4} Got LiteCore error: (unknown WebSocket status) (7/404)
I/LiteCore [Sync]: {Repl#4} now stopped
I/LiteCore [Sync]: {DBWorker#5}==> N8litecore4repl8DBWorkerE ->blip:172.16.1.163:4985/db/_blipsync
I/LiteCore [Sync]: {DBWorker#5} now idle
I/LiteCore [Sync]: {Push#6}==> N8litecore4repl6PusherE ->blip:172.16.1.163:4985/db/_blipsync
I/LiteCore [Sync]: {Push#6} now stopped
I/LiteCore [BLIP]: {N8litecore4blip6BLIPIOE#4}==> N8litecore4blip6BLIPIOE 0xd3945620
I/LiteCore [BLIP]: {N8litecore4blip6BLIPIOE#4} ~BLIPIO: Max outbox depth was 0, avg -nan
I/LiteCore [Sync]: {Pull#7}==> N8litecore4repl6PullerE ->blip:172.16.1.163:4985/db/_blipsync
I/LiteCore [Sync]: {Pull#7} now busy
I/LiteCore [DB]: Closing DataFile
I/LiteCoreJNI: [NATIVE] C4Replicator.statusChangedCallback() repl -> 0x0xd22f2580 status -> 0
E/C4Replicator: statusChangedCallback() handle -> 3526305152, status -> C4ReplicatorStatus{activityLevel=0, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=7, errorCode=404, errorInternalInfo=1001}
I/LiteCoreJNI: [NATIVE] C4Replicator.getResponseHeaders() repl -> 0xd22f2580
E/Sync: statusChanged() c4Status -> C4ReplicatorStatus{activityLevel=0, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=7, errorCode=404, errorInternalInfo=1001}
E/Sync: Replicator[<-> blip://172.16.1.163:4985/db] is stopped, progress 0/0, error: CouchbaseLiteException{domain=7, code=404, msg=null}
I/LiteCoreJNI: [NATIVE] C4Replicator.free() repl -> 0xd22f2580

Also, this is the response of url -  http://172.16.1.163:4985/db/_blipsync
{"error":"not_found","reason":"feature not enabled"}.

I'm using below configuration to start replicator.
1. Setting channels to ["ABC"]
2. ReplicatorType to "PUSH"
3. isContinous to "True"
4. authenticator to Basic Authenticator with username - "autotest" and password - "password"

I've checked that the user exist at SG site from this url - http://172.16.1.163:4985/db/_user/
>["autotest"]

I'm getting the same error on SG version 1.5.0-555 and 2.0.0-705

**Comment by hrajput89** [comment]
got the issue. There was a problem with authenticator. Able to start replicator now.
