### ISSUE TITLE
2.0: Repl Bad URL returns 19 instead of 15 on API 24 ARM emulator

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1499]
```java
    public void testBadURL() throws InterruptedException {
        ReplicatorConfiguration config = makeConfig(false, true, false, "blxp://localhost/db");
        run(config, 15, "LiteCore");
    }
```

stack trace
```
java.lang.AssertionError: expected:<15> but was:<19>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at com.couchbase.lite.BaseReplicatorTest$1.changed(BaseReplicatorTest.java:104)
at com.couchbase.lite.internal.replicator.ReplicatorChangeListenerToken$1.run(ReplicatorChangeListenerToken.java:26)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by hideki** [comment]
We don't support API 15.
And error code 19 is IO error. This could be same error that Jenkins sometimes fails
