### ISSUE TITLE
todo app not able to open db files for SQLCipher storage mode

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-android#1506]
REF: https://docs.google.com/document/d/1U1ZxM30e1cRMzpLluBDdcVh3v_CmLpw9ItDcYy1Gcfk/edit

I'm migrating todo app from 1.4.1 SQLCipher to todo2.0 SQLCipher. I'm getting below error .
```
W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
I/LiteCore [DB]: Opening DataFile /data/user/0/com.couchbase.todo/files/hemant.cblite2/db.sqlite3
W/LiteCore: SQLite error (code 26): file is encrypted or is not a database
W/LiteCore: SQLite error (code 11): database corruption at line 61620 of [edb4e819b0]
E/Application: Failed to create Database instance: hemant - com.couchbase.lite.DatabaseConfiguration@5eb95f1
               CouchbaseLiteException{domain=1, code=29, msg=file is encrypted or is not a database}
                   at com.couchbase.lite.internal.bridge.LiteCoreBridge.convertException(LiteCoreBridge.java:22)
                   at com.couchbase.lite.Database.open(Database.java:830)
                   at com.couchbase.lite.Database.<init>(Database.java:151)
                   at com.couchbase.todo.Application.openDatabase(Application.java:115)
                   at com.couchbase.todo.Application.startSession(Application.java:69)
                   at com.couchbase.todo.Application.login(Application.java:86)
                   at com.couchbase.todo.LoginActivity.login(LoginActivity.java:35)
                   at com.couchbase.todo.LoginActivity.access$000(LoginActivity.java:10)
                   at com.couchbase.todo.LoginActivity$1.onClick(LoginActivity.java:26)
                   at android.view.View.performClick(View.java:5637)
                   at android.view.View.onKeyUp(View.java:10661)
                   at android.widget.TextView.onKeyUp(TextView.java:6436)
                   at android.view.KeyEvent.dispatch(KeyEvent.java:2712)
                   at android.view.View.dispatchKeyEvent(View.java:9960)
                   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                   at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:405)
                   at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1798)
                   at android.app.Activity.dispatchKeyEvent(Activity.java:3021)
                   at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
                   at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
                   at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
                   at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:319)
                   at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4331)
                   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4032)
                   at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4193)
                   at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2400)
                   at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1964)
                   at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1955)
                   at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2377)
                   at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
E/Application:     at android.os.MessageQueue.nativePollOnce(Native Method)
                   at android.os.MessageQueue.next(MessageQueue.java:323)
                   at android.os.Looper.loop(Looper.java:136)
                   at android.app.ActivityThread.main(ActivityThread.java:6119)
                   at java.lang.reflect.Method.invoke(Native Method)
                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                Caused by: LiteCoreException{domain=1, code=29, msg=file is encrypted or is not a database}
                   at com.couchbase.litecore.C4Database.open(Native Method)
                   at com.couchbase.litecore.C4Database.<init>(C4Database.java:21)
                   at com.couchbase.lite.Database.open(Database.java:823)
                   	... 55 more
E/InputEventSender: Exception dispatching finished signal.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'com.couchbase.litecore.C4Database com.couchbase.lite.Database.getC4Database()' on a null object reference
                        at com.couchbase.lite.Replicator._start(Replicator.java:330)
                        at com.couchbase.lite.Replicator.start(Replicator.java:229)
                        at com.couchbase.todo.Application.startReplication(Application.java:194)
                        at com.couchbase.todo.Application.startSession(Application.java:71)
                        at com.couchbase.todo.Application.login(Application.java:86)
                        at com.couchbase.todo.LoginActivity.login(LoginActivity.java:35)
                        at com.couchbase.todo.LoginActivity.access$000(LoginActivity.java:10)
                        at com.couchbase.todo.LoginActivity$1.onClick(LoginActivity.java:26)
                        at android.view.View.performClick(View.java:5637)
                        at android.view.View.onKeyUp(View.java:10661)
                        at android.widget.TextView.onKeyUp(TextView.java:6436)
                        at android.view.KeyEvent.dispatch(KeyEvent.java:2712)
                        at android.view.View.dispatchKeyEvent(View.java:9960)
                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:405)
                        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1798)
                        at android.app.Activity.dispatchKeyEvent(Activity.java:3021)
                        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
                        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
                        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
                        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:319)
                        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4331)
                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4032)
                        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4193)
                        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2400)
                        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1964)
                        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1955)
                        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2377)
                        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                        at android.os.MessageQueue.nativePollOnce(Native Method)
                        at android.os.MessageQueue.next(MessageQueue.java:323)
                    	at android.os.Looper.loop(Looper.java:13
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.couchbase.todo, PID: 11693
                  java.lang.NullPointerException: Attempt to invoke virtual method 'com.couchbase.litecore.C4Database com.couchbase.lite.Database.getC4Database()' on a null object reference
                      at com.couchbase.lite.Replicator._start(Replicator.java:330)
                      at com.couchbase.lite.Replicator.start(Replicator.java:229)
                      at com.couchbase.todo.Application.startReplication(Application.java:194)
                      at com.couchbase.todo.Application.startSession(Application.java:71)
                      at com.couchbase.todo.Application.login(Application.java:86)
                      at com.couchbase.todo.LoginActivity.login(LoginActivity.java:35)
                      at com.couchbase.todo.LoginActivity.access$000(LoginActivity.java:10)
                      at com.couchbase.todo.LoginActivity$1.onClick(LoginActivity.java:26)
                      at android.view.View.performClick(View.java:5637)
                      at android.view.View.onKeyUp(View.java:10661)
                      at android.widget.TextView.onKeyUp(TextView.java:6436)
                      at android.view.KeyEvent.dispatch(KeyEvent.java:2712)
                      at android.view.View.dispatchKeyEvent(View.java:9960)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                      at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:405)
                      at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1798)
                      at android.app.Activity.dispatchKeyEvent(Activity.java:3021)
                      at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
                      at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
                      at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:319)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4331)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4032)
                      at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4193)
                      at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2400)
                      at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1964)
                      at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1955)
                      at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2377)
                      at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                      at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime:     at android.os.MessageQueue.next(MessageQueue.java:323)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Disconnected from the target VM, address: 'localhost:8663', transport: 'socket'
  ```

**Comment by djpongh** [comment]
works now
