### ISSUE TITLE
2.0: ReplicatorTest > testPullDoc fails

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1512]
```
java.lang.AssertionError: expected:<2> but was:<1>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at com.couchbase.lite.ReplicatorTest.testPullDoc(ReplicatorTest.java:92)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
```

**Comment by hideki** [comment]
Replicator[<- com.couchbase.lite.DatabaseEndpoint@a6a99f] is stopped, progress 0/0, error: CouchbaseLiteException{domain=1, code=19, msg=null}
```
01-18 05:44:03.657 19000-19018/com.couchbase.lite.test W/LiteCore: SQLite error (code 522): disk I/O error
01-18 05:44:03.657 19000-19018/com.couchbase.lite.test E/Sync: Replicator[<- com.couchbase.lite.DatabaseEndpoint@a6a99f] is stopped, progress 0/0, error: CouchbaseLiteException{domain=1, code=19, msg=null}
01-18 05:44:03.657 19000-19018/com.couchbase.lite.test I/Sync: C4ReplicatorListener.statusChanged() status -> C4ReplicatorStatus{activityLevel=0, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=1, errorCode=19, errorInternalInfo=0}
01-18 05:44:03.657 19000-19000/com.couchbase.lite.test E/Sync: statusChanged() c4Status -> C4ReplicatorStatus{activityLevel=0, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=1, errorCode=19, errorInternalInfo=0}
01-18 05:44:03.658 19000-19000/com.couchbase.lite.test E/Sync: Replicator[<- com.couchbase.lite.DatabaseEndpoint@a6a99f] is stopped, progress 0/0, error: CouchbaseLiteException{domain=1, code=19, msg=null}
01-18 05:44:03.658 19000-19000/com.couchbase.lite.test E/BaseTest: ---Status: stopped (0 / 0), lastError = CouchbaseLiteException{domain=1, code=19, msg=null}
01-18 05:44:03.658 19000-19018/com.couchbase.lite.test I/Database: Closing com.couchbase.lite.Database@d44ebf9[otherdb] at path /data/data/com.couchbase.lite.test/files/CouchbaseLite/otherdb.cblite2/
01-18 05:44:03.659 19000-19018/com.couchbase.lite.test I/LiteCore [DB]: Closing DataFile
01-18 05:44:03.664 19000-19018/com.couchbase.lite.test I/Database: Closing com.couchbase.lite.Database@23752c0[testdb] at path /data/data/com.couchbase.lite.test/files/CouchbaseLite/testdb.cblite2/
01-18 05:44:03.664 19000-19018/com.couchbase.lite.test I/LiteCore [DB]: Closing DataFile
01-18 05:44:03.675 19000-19018/com.couchbase.lite.test I/Database: delete(): path=/data/data/com.couchbase.lite.test/files/CouchbaseLite/testdb.cblite2
01-18 05:44:03.676 19000-19018/com.couchbase.lite.test I/TestRunner: failed: testPullDoc(com.couchbase.lite.ReplicatorTest)
01-18 05:44:03.676 19000-19018/com.couchbase.lite.test I/TestRunner: ----- begin exception -----
01-18 05:44:03.676 19000-19018/com.couchbase.lite.test I/TestRunner: java.lang.AssertionError: expected:<2> but was:<1>
                                                                         at org.junit.Assert.fail(Assert.java:88)
                                                                         at org.junit.Assert.failNotEquals(Assert.java:834)
                                                                         at org.junit.Assert.assertEquals(Assert.java:645)
                                                                         at org.junit.Assert.assertEquals(Assert.java:631)
                                                                         at com.couchbase.lite.ReplicatorTest.testPullDoc(ReplicatorTest.java:96)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
                                                                         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                                                                         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
                                                                         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                                                                         at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
                                                                         at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
                                                                         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
                                                                         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
                                                                         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
                                                                         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                                                                         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                                                                         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                                                                         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                                                                         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                                                                         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                                                                         at org.junit.runners.Suite.runChild(Suite.java:128)
                                                                         at org.junit.runners.Suite.runChild(Suite.java:27)
                                                                         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                                                                         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                                                                         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                                                                         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                                                                         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                                                                         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                                                                         at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                                                                         at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                                                                         at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
                                                                         at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
                                                                         at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
01-18 05:44:03.676 19000-19018/com.couchbase.lite.test I/TestRunner: ----- end exception -----
```

**Comment by hideki** [comment]
duplicate with #1503
