### ISSUE TITLE
Editing tasks concurrently fails with LiteCoreException Failed to selectNextLeaf

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-android#1529]
### Steps
1. Compiled ToDo app.
2. Installed on a Nexus 6p device.
3. Login to the ToDo app.
4. Edit tasks concurrently across multiple devices

```
01-17 15:14:42.153 13961-13961/com.couchbase.todo E/Database: Failed to selectNextLeaf: doc -> com.couchbase.litecore.C4Document@5b6504
   LiteCoreException{domain=315433240, code=0, msg=null}
	at com.couchbase.litecore.C4Document.selectNextLeafRevision(Native Method)
	at com.couchbase.litecore.C4Document.selectNextLeafRevision(C4Document.java:130)
	at com.couchbase.lite.Document.selectConflictingRevision(Document.java:475)
	at com.couchbase.lite.Database.resolveConflictInDocument(Database.java:794)
	at com.couchbase.lite.Replicator.documentError(Replicator.java:447)
	at com.couchbase.lite.Replicator.access$100(Replicator.java:43)
	at com.couchbase.lite.Replicator$1$2.run(Replicator.java:415)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by hideki** [comment]
Hi @raghusarangapani,
Once we solved conflict resolver issue with replication, I can not see this problem.
Can we retest this scenario tomorrow's test fest
Thanks

**Comment by hideki** [comment]
This error message is not error. I should change log level.
```java
    boolean selectConflictingRevision() {
        try {
            _c4doc.selectNextLeafRevision(false, true);
            setC4Document(_c4doc); // self.c4Doc = _c4Doc; // This will update to the selected revision
        } catch (LiteCoreException e) {
            Log.e(TAG, "Failed to selectNextLeaf: doc -> %s", e, _c4doc);
            return false;
        }
        return true;
    }
```
