### ISSUE TITLE
1.4 : P2P connection : not syncing on multiple connection with hotspot

### ISSUE THREAD

**Issue by pkjvit** [couchbase/couchbase-lite-android#1599]
I have following devices
 - DeviceA - act as Hotspot 
 - DeviceB - act as Wifi
 - DeviceC - act as Wifi

I have connected DeviceB to DeviceA through P2P connection, Couchbase p2p sync is working fine.

when I create DeviceC(wifi) to DeviceA(hotspot), which is already connected and syncing with DeviceB, now after connected with DeviceA, syncing not working on all devices.

Could you please help me in following issues-
1. P2P syncing between multiple devices with Couchbase?
2. Why syncing is not working on multiple connections, Is this issue cause of LiteListener as it's created on same port "55000"?

**Comment by pkjvit** [comment]
Hi hideki,

I need your help in one to many device connections and syncing between them through couchbase-lite.

As you move this ticket to 1.4.x milestone, I want to know that Is it possible in current version 1.4.1 or it's an issue. So I can go further and find out the solution for the same as I have to do multi-device syncing. Please suggest me, I need your precious advice in this.

Thanks & Regards!
Pankaj

**Comment by hideki** [comment]
Hi @pkjvit,

I believe CBL 1.4.1 works fine with multiple P2P connections. your configuration is a star topology.
One master and multiple slaves. In your example, Device A runs Couchbase Listener, and Device B and Device C run Push & Pull replicators. All device should be synchronized as we expected.

**Comment by pkjvit** [comment]
Thanks for the response. 
Glad to know it's working on star topology.
Thank you so much.

**Comment by pawanm** [comment]
Thanks @hideki for confirmation that P2P will work on start topology. Do we have any way to find out how many clients are connected to master & can we get some event when any client tries to connect on master.

**Comment by pkjvit** [comment]
Hi @hideki 
When we connect DeviceC to DeviceA it's replicator goes in ACTIVE state and not syncing anything. and gives socket timeout error.

**Please find Android monitor logs below.**

```
com.couchbase.lite.replicator.RemoteRequest {GET, http://192.168.43.1:55000/ncl_dev_status_v12/_local/59c71969f87fd0f02d94aed54069eae1e4412fe2}: executeRequest() Exception: java.net.SocketTimeoutException: connect timed out.  url: http://192.168.43.1:55000/ncl_dev_status_v12/_local/59c71969f87fd0f02d94aed54069eae1e4412fe2
                                                                     java.net.SocketTimeoutException: connect timed out
                                                                         at java.net.PlainSocketImpl.socketConnect(Native Method)
                                                                         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
                                                                         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
                                                                         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
                                                                         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
                                                                         at java.net.Socket.connect(Socket.java:605)
                                                                         at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:63)
                                                                         at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:223)
                                                                         at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
                                                                         at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
                                                                         at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
                                                                         at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
                                                                         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                         at okhttp3.RealCall.execute(RealCall.java:69)
                                                                         at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:261)
                                                                         at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
                                                                         at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                         at java.lang.Thread.run(Thread.java:761)
02-19 07:10:06.630 12327-12963/com.android.validate W/Sync: com.couchbase.lite.replicator.ReplicationInternal$11@26aea26: error getting remote checkpoint
                                                            java.net.SocketTimeoutException: connect timed out
                                                                at java.net.PlainSocketImpl.socketConnect(Native Method)
                                                                at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
                                                                at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
                                                                at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
                                                                at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
                                                                at java.net.Socket.connect(Socket.java:605)
                                                                at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:63)
                                                                at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:223)
                                                                at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
                                                                at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
                                                                at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
                                                                at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
                                                                at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                at okhttp3.RealCall.execute(RealCall.java:69)
                                                                at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:261)
                                                                at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
                                                                at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                at java.lang.Thread.run(Thread.java:761)
```

**Comment by hideki** [comment]
Hi @pawanm  
Couchbase Listener is configured with fixed size with a maximum number of threads. If my memory is correct, it is around 20. With continuous pull replication, it keeps open 1 socket to detect changes. On the listener side, 1 thread is used for this.  With the default configuration, CBL cannot handle many clients. Also, memory for listener is limited, from memory point of view, Listener cannot handle many clients.

**Comment by hideki** [comment]
Hi @pkjvit,
There are two possibilities.  Device C can not connect Device A by the network issue. Or all threads or all sockets are exhausted on Device A, then Device A cannot process the connection request from Device C.

**Comment by pawanm** [comment]
Thanks @hideki for confirming.
