### ISSUE TITLE
2.0: memory leak in save(MutableDocument)

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1632]
With updating document with reusing `MutableDocument`, `Database.save(MutableDocument)` operation causes memory leak
```java
    @Override
    protected void test() {
        final int revs = 10000;
        Log.i(TAG, String.format("--- Creating %d revisions ---", revs));
        measure(revs, "revision", new Runnable() {
            @Override
            public void run() {
                addRevisions(revs);
            }
        });
    }

    void addRevisions(final int revisions){
        try {
            db.inBatch(new Runnable() {
                @Override
                public void run() {
                    try {
                        MutableDocument mDoc = new MutableDocument("doc");
                        updateDoc(mDoc, revisions);
                        //updateDocWithGetDocument(mDoc, revisions);
                    }catch (CouchbaseLiteException e) {
                        e.printStackTrace();
                    }

                }
            });
        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
        }
    }
    void updateDoc(MutableDocument doc, final int revisions) throws CouchbaseLiteException {
        for(int i = 0; i < revisions; i++){
            doc.setValue("count", i);
            db.save(doc);
        }
    }

    void updateDocWithGetDocument(MutableDocument doc, final int revisions) throws CouchbaseLiteException {
        for(int i = 0; i < revisions; i++){
            doc.setValue("count", i);
            db.save(doc);
            doc = db.getDocument("doc").toMutable();
        }
    }

```

Log:
``` Caught unexpected C++ bad_alloc("std::bad_alloc")```
```
03-05 17:01:34.521 24495-24618/com.couchbase.perftest W/LiteCore: Caught unexpected C++ bad_alloc("std::bad_alloc")
03-05 17:01:34.522 24495-24618/com.couchbase.perftest W/System.err: 25.928  CouchbaseLiteException{domain='CouchbaseLite', code=17, msg=std::bad_alloc}
03-05 17:01:34.523 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:47)
03-05 17:01:34.523 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:53)
03-05 17:01:34.523 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:1063)
03-05 17:01:34.523 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:237)
03-05 17:01:34.523 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.Database.save(Database.java:25)
03-05 17:01:34.523 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:219)
03-05 17:01:34.523 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.Database.save(Database.java:25)
03-05 17:01:34.524 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest.updateDoc(DocPerfTest.java:49)
03-05 17:01:34.524 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest$2.run(DocPerfTest.java:34)
03-05 17:01:34.524 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.inBatch(AbstractDatabase.java:327)
03-05 17:01:34.524 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.Database.inBatch(Database.java:25)
03-05 17:01:34.524 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest.addRevisions(DocPerfTest.java:29)
03-05 17:01:34.524 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest$1.run(DocPerfTest.java:22)
03-05 17:01:34.525 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.PerfTest.measure(PerfTest.java:55)
03-05 17:01:34.525 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest.test(DocPerfTest.java:19)
03-05 17:01:34.525 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.PerfTest$1.doInBackground(PerfTest.java:34)
03-05 17:01:34.525 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.PerfTest$1.doInBackground(PerfTest.java:29)
03-05 17:01:34.525 24495-24618/com.couchbase.perftest W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-05 17:01:34.525 24495-24618/com.couchbase.perftest W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-05 17:01:34.525 24495-24618/com.couchbase.perftest W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
03-05 17:01:34.526 24495-24618/com.couchbase.perftest W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-05 17:01:34.526 24495-24618/com.couchbase.perftest W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-05 17:01:34.526 24495-24618/com.couchbase.perftest W/System.err:     at java.lang.Thread.run(Thread.java:761)
03-05 17:01:34.526 24495-24618/com.couchbase.perftest W/System.err: Caused by: LiteCoreException{domain=1, code=17, msg=std::bad_alloc}
03-05 17:01:34.526 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.litecore.C4Document.update2(Native Method)
03-05 17:01:34.527 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.litecore.C4Document.update(C4Document.java:182)
03-05 17:01:34.527 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:1132)
03-05 17:01:34.527 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:1059)
03-05 17:01:34.527 24495-24618/com.couchbase.perftest W/System.err: 	... 20 more
03-05 17:01:34.528 24495-24618/com.couchbase.perftest I/LiteCore [DB]: Closing DataFile
03-05 17:01:34.545 24495-24618/com.couchbase.perftest I/LiteCore [DB]: Deleting database file /data/user/0/com.couchbase.perftest/files/perfdb.cblite2/db.sqlite3 (with -wal and -shm)
03-05 17:01:34.551 24495-24618/com.couchbase.perftest I/LiteCore [DB]: Opening DataFile /data/user/0/com.couchbase.perftest/files/perfdb.cblite2/db.sqlite3
03-05 17:01:41.073 24495-24618/com.couchbase.perftest W/LiteCore: Caught unexpected C++ bad_alloc("std::bad_alloc")
03-05 17:01:41.074 24495-24618/com.couchbase.perftest W/System.err: 18.054  CouchbaseLiteException{domain='CouchbaseLite', code=17, msg=std::bad_alloc}
03-05 17:01:41.074 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:47)
03-05 17:01:41.075 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:53)
03-05 17:01:41.075 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:1063)
03-05 17:01:41.075 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:237)
03-05 17:01:41.075 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.Database.save(Database.java:25)
03-05 17:01:41.075 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:219)
03-05 17:01:41.075 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.Database.save(Database.java:25)
03-05 17:01:41.075 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest.updateDoc(DocPerfTest.java:49)
03-05 17:01:41.075 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest$2.run(DocPerfTest.java:34)
03-05 17:01:41.075 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.inBatch(AbstractDatabase.java:327)
03-05 17:01:41.076 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.Database.inBatch(Database.java:25)
03-05 17:01:41.076 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest.addRevisions(DocPerfTest.java:29)
03-05 17:01:41.076 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest$1.run(DocPerfTest.java:22)
03-05 17:01:41.076 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.PerfTest.measure(PerfTest.java:55)
03-05 17:01:41.076 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest.test(DocPerfTest.java:19)
03-05 17:01:41.076 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.PerfTest$1.doInBackground(PerfTest.java:34)
03-05 17:01:41.076 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.PerfTest$1.doInBackground(PerfTest.java:29)
03-05 17:01:41.076 24495-24618/com.couchbase.perftest W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-05 17:01:41.076 24495-24618/com.couchbase.perftest W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-05 17:01:41.076 24495-24618/com.couchbase.perftest W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
03-05 17:01:41.076 24495-24618/com.couchbase.perftest W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-05 17:01:41.076 24495-24618/com.couchbase.perftest W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-05 17:01:41.076 24495-24618/com.couchbase.perftest W/System.err:     at java.lang.Thread.run(Thread.java:761)
03-05 17:01:41.077 24495-24618/com.couchbase.perftest W/System.err: Caused by: LiteCoreException{domain=1, code=17, msg=std::bad_alloc}
03-05 17:01:41.077 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.litecore.C4Document.update2(Native Method)
03-05 17:01:41.077 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.litecore.C4Document.update(C4Document.java:182)
03-05 17:01:41.077 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:1132)
03-05 17:01:41.077 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:1059)
03-05 17:01:41.077 24495-24618/com.couchbase.perftest W/System.err: 	... 20 more
03-05 17:01:41.079 24495-24618/com.couchbase.perftest I/LiteCore [DB]: Closing DataFile
03-05 17:01:41.096 24495-24618/com.couchbase.perftest I/LiteCore [DB]: Deleting database file /data/user/0/com.couchbase.perftest/files/perfdb.cblite2/db.sqlite3 (with -wal and -shm)
03-05 17:01:41.099 24495-24618/com.couchbase.perftest I/LiteCore [DB]: Opening DataFile /data/user/0/com.couchbase.perftest/files/perfdb.cblite2/db.sqlite3
03-05 17:01:41.099 24495-24618/com.couchbase.perftest W/LiteCore: SQLite error (code 7): failed to allocate 120000 bytes of memory
03-05 17:01:43.123 24495-24618/com.couchbase.perftest W/LiteCore: Caught unexpected C++ bad_alloc("std::bad_alloc")
03-05 17:01:43.124 24495-24618/com.couchbase.perftest W/System.err: 6.500  CouchbaseLiteException{domain='CouchbaseLite', code=17, msg=std::bad_alloc}
03-05 17:01:43.124 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:47)
03-05 17:01:43.124 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:53)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:1063)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:237)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.Database.save(Database.java:25)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:219)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.Database.save(Database.java:25)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest.updateDoc(DocPerfTest.java:49)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest$2.run(DocPerfTest.java:34)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.inBatch(AbstractDatabase.java:327)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.Database.inBatch(Database.java:25)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest.addRevisions(DocPerfTest.java:29)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest$1.run(DocPerfTest.java:22)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.PerfTest.measure(PerfTest.java:55)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest.test(DocPerfTest.java:19)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.PerfTest$1.doInBackground(PerfTest.java:34)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.PerfTest$1.doInBackground(PerfTest.java:29)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-05 17:01:43.125 24495-24618/com.couchbase.perftest W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
03-05 17:01:43.126 24495-24618/com.couchbase.perftest W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-05 17:01:43.126 24495-24618/com.couchbase.perftest W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-05 17:01:43.126 24495-24618/com.couchbase.perftest W/System.err:     at java.lang.Thread.run(Thread.java:761)
03-05 17:01:43.126 24495-24618/com.couchbase.perftest W/System.err: Caused by: LiteCoreException{domain=1, code=17, msg=std::bad_alloc}
03-05 17:01:43.126 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.litecore.C4Document.update2(Native Method)
03-05 17:01:43.126 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.litecore.C4Document.update(C4Document.java:182)
03-05 17:01:43.126 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:1132)
03-05 17:01:43.126 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:1059)
03-05 17:01:43.126 24495-24618/com.couchbase.perftest W/System.err: 	... 20 more
03-05 17:01:43.129 24495-24618/com.couchbase.perftest I/LiteCore [DB]: Closing DataFile
03-05 17:01:43.172 24495-24618/com.couchbase.perftest I/LiteCore [DB]: Deleting database file /data/user/0/com.couchbase.perftest/files/perfdb.cblite2/db.sqlite3 (with -wal and -shm)
03-05 17:01:43.177 24495-24618/com.couchbase.perftest I/LiteCore [DB]: Opening DataFile /data/user/0/com.couchbase.perftest/files/perfdb.cblite2/db.sqlite3
03-05 17:01:43.189 24495-24618/com.couchbase.perftest W/LiteCore: SQLite error (code 7): failed to allocate 120000 bytes of memory
03-05 17:01:44.311 24495-24618/com.couchbase.perftest W/LiteCore: Caught unexpected C++ bad_alloc("std::bad_alloc")
03-05 17:01:44.311 24495-24618/com.couchbase.perftest W/System.err: 2.008  CouchbaseLiteException{domain='CouchbaseLite', code=17, msg=std::bad_alloc}
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:47)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:53)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:1063)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:237)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.Database.save(Database.java:25)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:219)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.Database.save(Database.java:25)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest.updateDoc(DocPerfTest.java:49)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest$2.run(DocPerfTest.java:34)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.inBatch(AbstractDatabase.java:327)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.Database.inBatch(Database.java:25)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest.addRevisions(DocPerfTest.java:29)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest$1.run(DocPerfTest.java:22)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.PerfTest.measure(PerfTest.java:55)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.DocPerfTest.test(DocPerfTest.java:19)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.PerfTest$1.doInBackground(PerfTest.java:34)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.perftest.PerfTest$1.doInBackground(PerfTest.java:29)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-05 17:01:44.312 24495-24618/com.couchbase.perftest W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
03-05 17:01:44.313 24495-24618/com.couchbase.perftest W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-05 17:01:44.313 24495-24618/com.couchbase.perftest W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-05 17:01:44.313 24495-24618/com.couchbase.perftest W/System.err:     at java.lang.Thread.run(Thread.java:761)
03-05 17:01:44.313 24495-24618/com.couchbase.perftest W/System.err: Caused by: LiteCoreException{domain=1, code=17, msg=std::bad_alloc}
03-05 17:01:44.313 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.litecore.C4Document.update2(Native Method)
03-05 17:01:44.313 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.litecore.C4Document.update(C4Document.java:182)
03-05 17:01:44.313 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:1132)
03-05 17:01:44.313 24495-24618/com.couchbase.perftest W/System.err:     at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:1059)
03-05 17:01:44.313 24495-24618/com.couchbase.perftest W/System.err: 	... 20 more
03-05 17:01:44.324 24495-24618/com.couchbase.perftest I/LiteCore [DB]: Closing DataFile
03-05 17:01:44.346 24495-24618/com.couchbase.perftest I/LiteCore [DB]: Deleting database file /data/user/0/com.couchbase.perftest/files/perfdb.cblite2/db.sqlite3 (with -wal and -shm)
03-05 17:01:44.348 24495-24618/com.couchbase.perftest I/LiteCore [DB]: Opening DataFile /data/user/0/com.couchbase.perftest/files/perfdb.cblite2/db.sqlite3
03-05 17:01:44.348 24495-24618/com.couchbase.perftest W/LiteCore: SQLite error (code 7): failed to allocate 120000 bytes of memory
03-05 17:01:44.442 24495-24506/com.couchbase.perftest E/libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
03-05 17:01:44.442 24495-24506/com.couchbase.perftest A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 24506 (HeapTaskDaemon)
                                                              
                                                              [ 03-05 17:01:44.444   273:  273 W/         ]
                                                              debuggerd: handling request: pid=24495 uid=10258 gid=10258 tid=24506

```

**Comment by hideki** [comment]
Probably `C4Document` is not freed.
![screen shot 2018-03-05 at 5 25 44 pm](https://user-images.githubusercontent.com/15889/37009146-78f16f04-209a-11e8-932b-11cc58f82fc7.png)
