### ISSUE TITLE
Issue with attachments. PusherInterval.java. uploadMultipartRevision.

### ISSUE THREAD

**Issue by VasuInukollu** [couchbase/couchbase-lite-android#1719]
## Issue with Replication

I have the following code which fails while replication. The uploadMultipartRevision method tries to access the _attachments property but it is coming as null. 

`
                    try {
                        profile.update(new Document.DocumentUpdater() {
                            @Override
                            public boolean update(UnsavedRevision newRevision) {
                                Map<String, Object> properties = newRevision.getProperties();
                                properties.put("refreshStatus", Calendar.getInstance().getTime().toString());
                                newRevision.setUserProperties(properties);
                                return true;
                            }
                        });
                    } catch (CouchbaseLiteException e) {
                        e.printStackTrace();
                    }

`

04-16 18:16:05.640 2031-2144/in.kdms.app V/Sync: com.couchbase.lite.replicator.PusherInternal$5@18cd522: got /_revs_diff response
04-16 18:16:05.672 2031-2144/in.kdms.fleetapp E/RemoteRequest: RemoteRequestCompletionBlock throw Exception
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Set java.util.Map.keySet()' on a null object reference
        at com.couchbase.lite.replicator.PusherInternal.uploadMultipartRevision(PusherInternal.java:594)
        at com.couchbase.lite.replicator.PusherInternal.access$600(PusherInternal.java:54)
        at com.couchbase.lite.replicator.PusherInternal$5.onCompletion(PusherInternal.java:478)
        at com.couchbase.lite.replicator.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:351)

**Comment by VasuInukollu** [comment]
## Version details if required

couchbase-lite-android:1.4.1 
==== Couchbase Sync Gateway/1.5.1(4;cb9522c) ====

**Comment by hideki** [comment]
Ref: https://github.com/couchbase/couchbase-lite-java-core/issues/693#issuecomment-381598232
