### ISSUE TITLE
CBL doesn't support replication on IPv6 to SG

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-android#1721]
CBL app is not able to connect to SG on IPv6 address. I'm getting ConnectException when trying to start replication over IPv6 to SG.

Below are the logs from CBL Android - 

```
I/DB: CouchbaseLite/2.0.0-457 (Java; Android 8.0.0; Google) Build/0 Commit/82609b6 LiteCore/ (457)
I/DB: Opening Database@a3f3e1e{name='suite_db'} at path /data/user/0/com.couchbase.TestServerApp/files/suite_db.cblite2
I/LiteCore [DB]: Opening database /data/user/0/com.couchbase.TestServerApp/files/suite_db.cblite2/db.sqlite3
I/DB: CouchbaseLite/2.0.0-457 (Java; Android 8.0.0; Google) Build/0 Commit/82609b6 LiteCore/ (457)
I/DB: Opening Database@e269ccc{name='test_db1523962737.83'} at path /data/user/0/com.couchbase.TestServerApp/files/test_db1523962737.83.cblite2
I/LiteCore [DB]: Opening database /data/user/0/com.couchbase.TestServerApp/files/test_db1523962737.83.cblite2/db.sqlite3
I/System.out: com.couchbase.CouchbaseLiteServ.server.Args@312d41b
I/zygote: Do full code cache collection, code=121KB, data=81KB
I/zygote: After code cache collection, code=118KB, data=69KB
I/Sync: Replicator[<*> Database@e269ccc{name='test_db1523962737.83'} URLEndpoint{url=ws://[fc00::12]:4984/db}]: Starting
I/LiteCoreJNI: [NATIVE] C4Replicator.create()
I/LiteCore [DB]: Opening database /data/user/0/com.couchbase.TestServerApp/files/test_db1523962737.83.cblite2/db.sqlite3
I/LiteCore [BLIP]: {N8litecore4blip10ConnectionE#6}==> N8litecore4blip10ConnectionE ->ws:[fc00::12]:4984/db/_blipsync
I/LiteCore [BLIP]: {N8litecore4blip10ConnectionE#6} Opening connection...
I/LiteCore [Sync]: {Repl#10}==> N8litecore4repl10ReplicatorE /data/user/0/com.couchbase.TestServerApp/files/test_db1523962737.83.cblite2/ ->ws:[fc00::12]:4984/db/_blipsync
I/LiteCore [Sync]: {Repl#10} Push=continuous, Pull=continuous, Options={"WS-Protocols":"BLIP_3+CBMobile_2",channels:["ABC"],cookies:"SyncGatewaySession=c184dd3f8e02ad5567253cc45476b853e77e089e",headers:{"User-Agent":"CouchbaseLite/2.0.0-457 (Java; Android 8.0.0; Google) Build/0 Commit/82609b6 LiteCore/ (457)"}}
I/LiteCoreJNI: [NATIVE] C4Replicator.create() repl -> 0x0xc9beb080
I/LiteCoreJNI: [NATIVE] C4Replicator.getStatus() repl -> 0xc9beb080
I/Sync: Replicator[<*> Database@e269ccc{name='test_db1523962737.83'} URLEndpoint{url=ws://[fc00::12]:4984/db}] is connecting, progress 0/0, error: null
I/Sync: C4ReplicatorListener.statusChanged() status -> C4ReplicatorStatus{activityLevel=2, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=0, errorCode=0, errorInternalInfo=0}
V/WS: CBLWebSocket connecting to ws://[fc00::12]:4984/db/_blipsync...
I/LiteCoreJNI: [NATIVE] C4Replicator.getResponseHeaders() repl -> 0xc9beb080
I/Sync: statusChanged() c4Status -> C4ReplicatorStatus{activityLevel=2, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=0, errorCode=0, errorInternalInfo=0}
I/Sync: Replicator[<*> Database@e269ccc{name='test_db1523962737.83'} URLEndpoint{url=ws://[fc00::12]:4984/db}] is connecting, progress 0/0, error: null
I/LiteCore [Sync]: {Repl#10} activityLevel=connecting: connectionState=1
W/WS: WebSocketListener.onFailure() response -> null
      java.net.ConnectException: Failed to connect to /fc00::12:4984
          at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
          at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
          at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
          at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
          at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
          at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
          at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
          at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
          at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
          at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
          at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
          at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
          at java.lang.Thread.run(Thread.java:764)
       Caused by: java.net.ConnectException: failed to connect to /fc00::12 (port 4984) from /:: (port 0) after 10000ms: connect failed: ENETUNREACH (Network is unreachable)
          at libcore.io.IoBridge.connect(IoBridge.java:138)
          at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
          at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
          at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
          at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
          at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
          at java.net.Socket.connect(Socket.java:616)
          at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:70)
          at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
          at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158) 
          at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256) 
          at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134) 
          at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113) 
          at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
          at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
          at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
          at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) 
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
          at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) 
          at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147) 
          at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
          at java.lang.Thread.run(Thread.java:764) 
       Caused by: android.system.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
          at libcore.io.Linux.connect(Native Method)
          at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:126)
          at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
          at libcore.io.IoBridge.connect(IoBridge.java:130)
          at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129) 
          at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356) 
          at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) 
          at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) 
          at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356) 
          at java.net.Socket.connect(Socket.java:616) 
          at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:70) 
          at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238) 
          at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158) 
          at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256) 
          at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134) 
          at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113) 
          at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
          at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
          at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
          at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) 
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
          at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) 
          at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147) 
          at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
          at java.lang.Thread.run(Thread.java:764) 
I/LiteCore [WS]: {N8litecore9websocket12C4SocketImplE#3}==> N8litecore9websocket12C4SocketImplE ws:[fc00::12]:4984/db/_blipsync
I/LiteCore [WS]: {N8litecore9websocket12C4SocketImplE#3} Socket disconnected! (reason=1, code=101)
I/LiteCore [WS]: {N8litecore9websocket12C4SocketImplE#3} sent 0 bytes, rcvd 0, in 0.000 sec (-nan/sec, -nan/sec)
I/LiteCore [BLIP]: {N8litecore4blip10ConnectionE#6} Closed with errno 101: Network is unreachable
I/LiteCore [Sync]: {Repl#10} Connection closed with errno 101: "Network is unreachable" (state=1)
E/LiteCore [Sync]: {Repl#10} Got LiteCore error: Network is unreachable (2/101)
I/LiteCore [Sync]: {Repl#10} activityLevel=stopped: connectionState=-1
I/LiteCore [Sync]: {Repl#10} now stopped
I/LiteCore [Sync]: {DBWorker#11}==> N8litecore4repl8DBWorkerE ->ws:[fc00::12]:4984/db/_blipsync
I/LiteCore [Sync]: {DBWorker#11} activityLevel=idle: pendingResponseCount=0, eventCount=1
I/LiteCore [Sync]: {Push#12}==> N8litecore4repl6PusherE ->ws:[fc00::12]:4984/db/_blipsync
I/LiteCore [Sync]: {Push#12} activityLevel=idle: pendingResponseCount=0, caughtUp=0, changeLists=0, revsInFlight=0, blobsInFlight=0, awaitingReply=0, revsToSend=0, pendingSequences=0
I/LiteCore [Sync]: {Repl#10} activityLevel=stopped: connectionState=-1
I/LiteCore [Sync]: {Repl#10} activityLevel=stopped: connectionState=-1
I/LiteCore [BLIP]: {N8litecore4blip6BLIPIOE#7}==> N8litecore4blip6BLIPIOE 0xdcba7a40
I/LiteCore [BLIP]: {N8litecore4blip6BLIPIOE#7} ~BLIPIO: Sent 0 bytes, rcvd 0. Max outbox depth was 0, avg -nan
I/LiteCore [Sync]: {Pull#13}==> N8litecore4repl6PullerE ->ws:[fc00::12]:4984/db/_blipsync
I/LiteCore [Sync]: {Pull#13} activityLevel=busy: pendingResponseCount=0, _caughtUp=0, _waitingForChangesCallback=0, _pendingRevMessages=0, _activeIncomingRevs=0
I/LiteCore [DB]: Closing database /data/user/0/com.couchbase.TestServerApp/files/test_db1523962737.83.cblite2/db.sqlite3
I/LiteCore [Sync]: {Repl#10} activityLevel=stopped: connectionState=-1
I/LiteCoreJNI: [NATIVE] C4Replicator.statusChangedCallback() repl -> 0x0xc9beb080 status -> 0
I/Sync: C4ReplicatorListener.statusChanged() status -> C4ReplicatorStatus{activityLevel=0, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=2, errorCode=101, errorInternalInfo=1003}
I/LiteCore [Sync]: {Repl#10} activityLevel=stopped: connectionState=-1
I/LiteCoreJNI: [NATIVE] C4Replicator.getResponseHeaders() repl -> 0xc9beb080
I/Sync: statusChanged() c4Status -> C4ReplicatorStatus{activityLevel=0, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=2, errorCode=101, errorInternalInfo=1003}
I/LiteCoreJNI: [NATIVE] C4Replicator.free() repl -> 0xc9beb080
I/Sync: Replicator[<*> Database@e269ccc{name='test_db1523962737.83'} URLEndpoint{url=ws://[fc00::12]:4984/db}]: Network error (C4Error{domain=2, code=101, internalInfo=1003}); will retry when network changes...
V/Sync: com.couchbase.lite.AndroidNetworkReachabilityManager@8f0d0fc: startListening() registering com.couchbase.lite.AndroidNetworkReachabilityManager$NetworkReceiver@d1df385 with context android.app.Application@413d844
I/LiteCore [Sync]: {Repl#10} activityLevel=stopped: connectionState=-1
I/Sync: Replicator[<*> Database@e269ccc{name='test_db1523962737.83'} URLEndpoint{url=ws://[fc00::12]:4984/db}] is offline, progress 0/0, error: CouchbaseLiteException{domain='POSIXErrorDomain', code=101, msg=null}
```

One can start a CBL cluster with following steps.
1. Install CBS 5.5.0-2368 on machine with IPv6 n/w interface enabled  and then follow the steps given in the link to enable IPv6 -https://developer.couchbase.com/documentation/server/5.5/install/ipv6-setup.html
2. Create a bucket 'travel-sample' in CBS and user (travel-sample@password) with admin access
3. Install SG 2.1.0-23 on a machine with IPv6 enable. Use the below sync_gateway.json config to start the SG.
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["*"],
    "logFilePath": "/home/sync_gateway/logs",
    
    
    "databases":{
        "db":{
            
            
            
            "num_index_replicas": 0,
            "server":"http://[fc00::11]:8091",
            "bucket":"travel-sample",
            "username":"travel-sample",
            "password": "password"
        }
    }
}
```
4. Start any app CBL (mobile-testkit android) which connect to SG over IPv6. For example: use ws:[fc00::12]:4984/ as URLEndpoint for Replication.

PS - To create VM with IPv6, please refer this documentation - https://docs.google.com/document/d/1DcWvbDi7raH7ZsE2_q6eii476nCAtXdw8Atc29nUFK0/edit#

**Comment by hideki** [comment]
Hi @hrajput89,

Log message tells "fc00::12:4984" is not reachable from Android. I wonder if "fc00::12:4984" is accessible from a browser or curl command. And also if it is accessible from Android device. Can you verify it?
```
java.net.ConnectException: Failed to connect to /fc00::12:4984

Caused by: java.net.ConnectException: failed to connect to /fc00::12 (port 4984) from /:: (port 0) after 10000ms: connect failed: ENETUNREACH (Network is unreachable)
       
Caused by: android.system.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
```

**Comment by hideki** [comment]
I tested the replication with IPv6 under the following condition:
- Installed Sync Gateway 2.1.0-35 on OSX. Following two IPv6 address is my computer's IPv6 Address.
```
fd63:6f75:6368:1075:b3:d1e3:555c:d145
fd63:6f75:6368:1075:2c48:b5b9:26cb:6721 
```
- Use SG wraus mode (No Couchbase Server involved) as the problem was connection issue from Android to SG.
- Use Nexus 6 (real device) with Android 7.1.1 API 25.
- Use Todo sample application for testing

Tests I conducted:
- Access from Browser on the same computer
  - WORKS: http://[fd63:6f75:6368:1075:2c48:b5b9:26cb:6721]:4984/todo/
- Access from Browser on the Android device
  - WORKS: http://[fd63:6f75:6368:1075:2c48:b5b9:26cb:6721]:4984/todo/
- Replication test with Todo sample
  - WORKS `ws://[fd63:6f75:6368:1075:2c48:b5b9:26cb:6721]:4984/todo/`

Result/Conclusion:
- I believe CBL 2.x for Android works fine with iPv6. And I believe CBL 1.x, which uses same communication library with 2.x, could pass the IPv6 test.
- I believe the problem is in a test environment. QE might use an emulator which might not support IPv6?

@hrajput89,
Could you please share your test environment, especially Android setting.

Thanks!

**Comment by hideki** [comment]
FYI:

It seems that Virtual Box, that Genymotion uses, does not work with IPv6 if using NAT.
https://superuser.com/questions/76970/using-ipv6-with-virtualbox

Please select `Bridge` instead of `NAT` in Network mode configuration. With this, IPv6 should work!
![screen shot 2018-04-18 at 12 40 02 pm](https://user-images.githubusercontent.com/15889/38954109-a71a8f2c-4305-11e8-89f3-0b938009b403.png)
`

**Comment by hideki** [comment]
FYI: 

Android Stack Emulator works fine with IPv6

**Comment by pasin** [comment]
@hrajput89 @sridevi-15 @raghusarangapani Please use the Android Emulator instead of Genymotion. If the issue still exists, we could reopen the issue. Thanks.
