### ISSUE TITLE
1.4 : Getting Exception in setExpirationDate

### ISSUE THREAD

**Issue by verma171** [couchbase/couchbase-lite-android#1724]
```
Fatal Exception: java.lang.IllegalStateException: Timer already cancelled.
       at java.util.Timer.sched(Timer.java:397)
       at java.util.Timer.schedule(Timer.java:193)
       at com.couchbase.lite.Database.scheduleDocumentExpiration(Database.java:2579)
       at com.couchbase.lite.Database.setExpirationDate(Database.java:2563)
       at com.couchbase.lite.Document.setExpirationDate(Document.java:161)
       at 
```

**Comment by verma171** [comment]
Hi @hideki  need your assistance on this.

**Comment by hideki** [comment]
This could be multi-threading issue.

Following two lines executed concurrently.
https://github.com/couchbase/couchbase-lite-java-core/blob/17a6159e731d2c1c112f5354c08e15d96a4dc26a/src/main/java/com/couchbase/lite/Database.java#L1500
https://github.com/couchbase/couchbase-lite-java-core/blob/17a6159e731d2c1c112f5354c08e15d96a4dc26a/src/main/java/com/couchbase/lite/Database.java#L2579

Solution:
- `scheduleDocumentExpiration(long)` should return immediately if `closing` variable is `true` or `isOpen()` is `false`
