### ISSUE TITLE
Getting Crash When i am swtiching off internet network

### ISSUE THREAD

**Issue by ervijjusty** [couchbase/couchbase-lite-android#1736]
Couchbase lite is getting crash while I am turning off the internet connection. I am getting this same issue since last 6 months. I am using couchbase lite 2.o.

    05-31 18:10:36.295 20836-20884/in.digiscribe A/libc: heap corruption detected by dlfree
    05-31 18:10:36.295 20836-20884/in.digiscribe A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 20884 (Thread-35829)
    05-31 18:10:36.445 1270-3746/? E/LocSvc_LBSApiV02: E/virtual int lbs_core::LBSApiV02::wifiEnabledStatusInject(int):670]: Error : st = 11, ind.status = -1525540988
    05-31 18:10:36.507 446-499/? E/XTCC-5.0.0.4: [PredUnit] handleConnectivtyStatusChange, no information for active_network_info
    05-31 18:10:36.508 446-499/? E/XTCC-5.0.0.4: [PredUnit] handleConnectivtyStatusChange failed
    05-31 18:10:36.529 446-501/? E/XTCC-5.0.0.4: [CSMgr] handleConnectivtyStatusChange, no information for active_network_info
    05-31 18:10:36.529 446-501/? E/XTCC-5.0.0.4: [CSMgr] handleConnectivtyStatusChange failed
    05-31 18:10:36.548 446-499/? E/XTCC-5.0.0.4: [PredUnit] handleConnectivtyStatusChange, no information for active_network_info
     05-31 18:10:36.548 446-499/? E/XTCC-5.0.0.4: [PredUnit] handleConnectivtyStatusChange failed
     05-31 18:10:36.567 446-501/? E/XTCC-5.0.0.4: [CSMgr] handleConnectivtyStatusChange, no information for active_network_info
    05-31 18:10:36.567 446-501/? E/XTCC-5.0.0.4: [CSMgr] handleConnectivtyStatusChange failed
    05-31 18:10:37.547 22435-22456/? E/ExternalAccountType: Unsupported attribute readOnly
    05-31 18:10:38.546 1270-3518/? E/NativeCrashListener: Exception dealing with report
                                                      android.system.ErrnoException: read failed: EAGAIN (Try again)
                                                          at libcore.io.Posix.readBytes(Native Method)
                                                          at libcore.io.Posix.read(Posix.java:165)
                                                          at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
                                                          at android.system.Os.read(Os.java:350)
                                                          at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
                                                          at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)
     05-31 18:10:38.970 22521-22521/? E/ContactPhotoManager: No contact photo service in context: com.android.mms.MmsApp@bd34197
     05-31 18:10:39.352 1270-3962/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!

Please let me know how it can be sort. I am using Lenovo yoga tab 2. 

Quickstep:- 
1) Start replication on the database
2) Now Just turn off WIFI connectivity.
3) Once wifi connection is dropped the application will get crashed.

Regards,
Achint Sarkar

**Comment by ervijjusty** [comment]
More Logs For better understanding

        05-31 19:22:50.486 30866-30995/in.digiscribe E/LiteCore [Sync]: {Repl#5}==> N8litecore4repl10ReplicatorE /data/data/in.digiscribe/files/billing.cblite2/ ->ws:sync.digiscribe.in:4984/profile/_blipsync
    05-31 19:22:50.487 30866-30995/in.digiscribe E/LiteCore [Sync]: {Repl#5} Got LiteCore error: Connection reset by peer (2/104)
    05-31 19:22:50.487 30866-30995/in.digiscribe I/LiteCoreJNI: [NATIVE] C4Replicator.statusChangedCallback() repl -> 0x0xb8ba1268 status -> 0
    05-31 19:22:50.487 30866-30998/in.digiscribe I/LiteCoreJNI: [NATIVE] C4Replicator.free() repl -> 0xb8b33d90
    05-31 19:22:50.487 30866-31010/in.digiscribe W/WS: WebSocketListener.onFailure() response -> null
                                                   java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
                                                       at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:592)
                                                       at libcore.io.IoBridge.recvfrom(IoBridge.java:556)
                                                       at java.net.PlainSocketImpl.read(PlainSocketImpl.java:487)
                                                       at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:38)
                                                       at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:238)
                                                       at okio.Okio$2.read(Okio.java:139)
                                                       at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
                                                       at okio.RealBufferedSource.request(RealBufferedSource.java:67)
                                                       at okio.RealBufferedSource.require(RealBufferedSource.java:60)
                                                       at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
                                                       at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
                                                       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
                                                       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
                                                       at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: android.system.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
                                                       at libcore.io.Posix.recvfromBytes(Native Method)
                                                       at libcore.io.Posix.recvfrom(Posix.java:185)
                                                       at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
                                                       at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
                                                       at java.net.PlainSocketImpl.read(PlainSocketImpl.java:487) 
                                                       at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:38) 
                                                       at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:238) 
                                                       at okio.Okio$2.read(Okio.java:139) 
                                                       at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) 
                                                       at okio.RealBufferedSource.request(RealBufferedSource.java:67) 
                                                       at okio.RealBufferedSource.require(RealBufferedSource.java:60) 
                                                       at okio.RealBufferedSource.readByte(RealBufferedSource.java:73) 
                                                       at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113) 
                                                       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97) 
                                                       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265) 
                                                       at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204) 
                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) 
                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                       at java.lang.Thread.run(Thread.java:818) 
    05-31 19:22:50.488 30866-31023/in.digiscribe W/WS: WebSocketListener.onFailure() response -> null
                                                   java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
                                                       at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:592)
                                                       at libcore.io.IoBridge.recvfrom(IoBridge.java:556)
                                                       at java.net.PlainSocketImpl.read(PlainSocketImpl.java:487)
                                                       at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:38)
                                                       at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:238)
                                                       at okio.Okio$2.read(Okio.java:139)
                                                       at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
                                                       at okio.RealBufferedSource.request(RealBufferedSource.java:67)
                                                       at okio.RealBufferedSource.require(RealBufferedSource.java:60)
                                                       at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
                                                       at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
                                                       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
                                                       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
                                                       at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: android.system.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
                                                       at libcore.io.Posix.recvfromBytes(Native Method)
                                                       at libcore.io.Posix.recvfrom(Posix.java:185)
                                                       at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
                                                       at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
                                                       at java.net.PlainSocketImpl.read(PlainSocketImpl.java:487) 
                                                       at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:38) 
                                                       at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:238) 
                                                       at okio.Okio$2.read(Okio.java:139) 
                                                       at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) 
                                                       at okio.RealBufferedSource.request(RealBufferedSource.java:67) 
                                                       at okio.RealBufferedSource.require(RealBufferedSource.java:60) 
                                                       at okio.RealBufferedSource.readByte(RealBufferedSource.java:73) 
                                                       at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113) 
                                                       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97) 
                                                       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265) 
                                                       at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204) 
                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) 
                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                       at java.lang.Thread.run(Thread.java:818) 
    05-31 19:22:50.488 30866-31006/in.digiscribe W/WS: WebSocketListener.onFailure() response -> null
                                                   java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
                                                       at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:592)
                                                       at libcore.io.IoBridge.recvfrom(IoBridge.java:556)
                                                       at java.net.PlainSocketImpl.read(PlainSocketImpl.java:487)
                                                       at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:38)
                                                       at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:238)
                                                       at okio.Okio$2.read(Okio.java:139)
                                                       at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
                                                       at okio.RealBufferedSource.request(RealBufferedSource.java:67)
                                                       at okio.RealBufferedSource.require(RealBufferedSource.java:60)
                                                       at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
                                                       at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
                                                       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
                                                       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
                                                       at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: android.system.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
                                                       at libcore.io.Posix.recvfromBytes(Native Method)
                                                       at libcore.io.Posix.recvfrom(Posix.java:185)
                                                       at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
                                                       at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
                                                       at java.net.PlainSocketImpl.read(PlainSocketImpl.java:487) 
                                                       at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:38) 
                                                       at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:238) 
                                                       at okio.Okio$2.read(Okio.java:139) 
                                                       at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) 
                                                       at okio.RealBufferedSource.request(RealBufferedSource.java:67) 
                                                       at okio.RealBufferedSource.require(RealBufferedSource.java:60) 
                                                       at okio.RealBufferedSource.readByte(RealBufferedSource.java:73) 
                                                       at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113) 
                                                       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97) 
                                                       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265) 
                                                       at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204) 
                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) 
                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                       at java.lang.Thread.run(Thread.java:818) 
    05-31 19:22:50.488 30866-31019/in.digiscribe I/LiteCoreJNI: [NATIVE] C4Replicator.free() repl -> 0xb8bc1990
    05-31 19:22:50.492 30866-31000/in.digiscribe I/LiteCoreJNI: [NATIVE] C4Replicator.free() repl -> 0xb8b574a0
    05-31 19:22:50.492 30866-31007/in.digiscribe I/LiteCoreJNI: [NATIVE] C4Replicator.free() repl -> 0xb8ba1268
    05-31 19:22:50.493 30866-30995/in.digiscribe E/LiteCore [Sync]: {Repl#6}==> N8litecore4repl10ReplicatorE /data/data/in.digiscribe/files/case.cblite2/ ->ws:sync.digiscribe.in:4984/case/_blipsync
    05-31 19:22:50.493 30866-30995/in.digiscribe E/LiteCore [Sync]: {Repl#6} Got LiteCore error: Connection reset by peer (2/104)
    05-31 19:22:50.493 30866-30995/in.digiscribe I/LiteCoreJNI: [NATIVE] C4Replicator.statusChangedCallback() repl -> 0x0xb8b69d90 status -> 0
    05-31 19:22:50.495 30866-30996/in.digiscribe E/LiteCore [Sync]: {Repl#7}==> N8litecore4repl10ReplicatorE /data/data/in.digiscribe/files/event.cblite2/ ->ws:sync.digiscribe.in:4984/events/_blipsync
    05-31 19:22:50.495 30866-30996/in.digiscribe E/LiteCore [Sync]: {Repl#7} Got LiteCore error: Connection reset by peer (2/104)
    05-31 19:22:50.495 30866-30996/in.digiscribe I/LiteCoreJNI: [NATIVE] C4Replicator.statusChangedCallback() repl -> 0x0xb8b8fee8 status -> 0
    05-31 19:22:50.495 30866-30999/in.digiscribe I/LiteCoreJNI: [NATIVE] C4Replicator.free() repl -> 0xb8b465e8
    05-31 19:22:50.497 30866-30997/in.digiscribe E/LiteCore [Sync]: {Repl#8}==> N8litecore4repl10ReplicatorE /data/data/in.digiscribe/files/schedular.cblite2/ ->ws:sync.digiscribe.in:4984/schedular/_blipsync
    05-31 19:22:50.498 30866-30997/in.digiscribe E/LiteCore [Sync]: {Repl#8} Got LiteCore error: Connection reset by peer (2/104)
    05-31 19:22:50.498 30866-30997/in.digiscribe I/LiteCoreJNI: [NATIVE] C4Replicator.statusChangedCallback() repl -> 0x0xb8b7af50 status -> 0
    05-31 19:22:50.498 30866-30995/in.digiscribe E/LiteCore [Sync]: {Repl#9}==> N8litecore4repl10ReplicatorE /data/data/in.digiscribe/files/genericDatabase.cblite2/ ->ws:sync.digiscribe.in:4984/generic/_blipsync
    05-31 19:22:50.498 30866-30995/in.digiscribe E/LiteCore [Sync]: {Repl#9} Got LiteCore error: Connection reset by peer (2/104)
    05-31 19:22:50.498 30866-30995/in.digiscribe I/LiteCoreJNI: [NATIVE] C4Replicator.statusChangedCallback() repl -> 0x0xb8bd30d0 status -> 0
    05-31 19:22:50.498 30866-31001/in.digiscribe I/LiteCoreJNI: [NATIVE] C4Replicator.free() repl -> 0xb8b69d90
    05-31 19:22:50.500 30866-31002/in.digiscribe I/LiteCoreJNI: [NATIVE] C4Replicator.free() repl -> 0xb8b7af50
    05-31 19:22:50.501 30866-31003/in.digiscribe I/LiteCoreJNI: [NATIVE] C4Replicator.free() repl -> 0xb8b8fee8
    05-31 19:22:50.501 30866-30996/in.digiscribe A/libc: heap corruption detected by dlfree
    05-31 19:22:50.502 30866-30996/in.digiscribe A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 30996 (Thread-35490)

**Comment by borrrden** [comment]
This is another heap corruption as with #1738 so it is impossible to know what happened just from this report, but as I mentioned on the other ticket I have made a lot of progress combatting these types of errors for the 2.1 release.  Furthermore, I was unable to reproduce this on my device so unless you have some more information this is going to be iceboxed.

**Comment by borrrden** [comment]
FYI @ervijjusty We are freezing 2.1 at the end of this week and this will not make it in barring some more information and/or reproduction case because this is the kind of thing that needs to be run with an address sanitizer to track down (I am not sure that is even possible on Android, but I will look into it if need be) since by the time the issue happens it is already too late to find out what is wrong.

**Comment by djpongh** [comment]
Haven't heard back. Assuming fixed with work from @borrrden
