### ISSUE TITLE
Can not delete database in testing

### ISSUE THREAD

**Issue by nuxzero** [couchbase/couchbase-lite-android#1753]
I tried to delete the database after test in `@TearDown` but doesn't work. I didn't use Sync Gateway I think should not have the problem with `Replication `.

 Error log:

```
CouchbaseLiteException{domain='CouchbaseLite', code=16, msg=Can't delete db file while other connections are open}
at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:49)
at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:55)
at com.couchbase.lite.AbstractDatabase.deleteC4DB(AbstractDatabase.java:871)
at com.couchbase.lite.AbstractDatabase.delete(AbstractDatabase.java:489)
at com.couchbase.lite.Database.delete(Database.java:25)
```

My code:

``` 
try {
            database.delete()
            database.close()
            this.database = null
        } catch (e: CouchbaseLiteException) {

        }
```
--------
* Version:   2.0.0
* Client OS: Android
* Server:    -

**Comment by pasin** [comment]
@nuxzero I'm not able to use the code snippet above to reproduce the issue. The error generally means that there are some other components/processes/threads holding the (SQLite) database connections. Can you provide reproducible database usage scenario that causes the error when deleting the database in tear down?
