### ISSUE TITLE
CouchbaseLiteException while adding data

### ISSUE THREAD

**Issue by betaCode95** [couchbase/couchbase-lite-android#1757]
`Exception: com.couchbase.lite.CouchbaseLiteException
       at com.couchbase.lite.store.SQLiteStore.add(SourceFile:1468)
       at com.couchbase.lite.Database.put(SourceFile:1996)
       at com.couchbase.lite.Database.putRevision(SourceFile:1943)
       at com.couchbase.lite.Database.putRevision(SourceFile:1934)
       at com.couchbase.lite.Document.putProperties(SourceFile:526)
       at com.couchbase.lite.UnsavedRevision.save(SourceFile:118)
       at com.couchbase.lite.Document.update(SourceFile:380)
       at couchbase.CouchBaseDBHelper.updateDoc(SourceFile:203)
       at couchbase.CouchBaseDBHelper.addTask(SourceFile:139)
       at com.pharmeasy.logistic.local.LocalRepoImpl.saveTasks(SourceFile:80)
       at com.pharmeasy.logistic.local.LocalRepoImpl$$Lambda$0.subscribe(Unknown Source)
       at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(SourceFile:40)
       at io.reactivex.Observable.subscribe(SourceFile:10981)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(SourceFile:96)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call(SourceFile:38)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call(SourceFile:26)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)`

Any ideas? On Version 1.4.0

**Comment by pasin** [comment]
@betaCode95 Can you provide reproducible steps? Normally CouchbaseLiteException has status code and message; could you share that as well? Thanks!

**Comment by djpongh** [comment]
@betaCode95, any more info on this?

**Comment by betaCode95** [comment]
Currently, this is the only thing that is getting reported. It happens while inserting data into Couchbase, and occurs sometimes, when this exception is thrown data is not getting thrown. I am actually trying to insert an object which has an XML format with various unusual characters, I am not getting this exception all the time though
