### ISSUE TITLE
No serializer found for class com.couchbase.lite.Blob$BlobInputStream

### ISSUE THREAD

**Issue by brije111** [couchbase/couchbase-lite-android#1759]
I'm using couchbase lite 2.1.0, I posted data on server with an attachment as Blob and I try to read & convert it to POJO, I get this error

`java.lang.IllegalArgumentException: No serializer found for class com.couchbase.lite.Blob$BlobInputStream and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) ) (through reference chain: java.util.HashMap["img_0"]->com.couchbase.lite.Blob["contentStream"])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3512)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3431)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6239)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
     Caused by: com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class com.couchbase.lite.Blob$BlobInputStream and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) ) (through reference chain: java.util.HashMap["img_0"]->com.couchbase.lite.Blob["contentStream"])
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:68)
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:32)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:672)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:616)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:519)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:31)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3490)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3431) 
        at android.os.Handler.handleCallback(Handler.java:754) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6239) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794) `

**Comment by pasin** [comment]
I'm not familiar with Jackson but think Blob class requires to have a custom serializer. I just googled it and found this [link](https://www.baeldung.com/jackson-custom-serialization) on the first result.

**Comment by pasin** [comment]
As this is not an issue, I will close the issue. You can ask questions on https://forums.couchbase.com.
