### ISSUE TITLE
Crash on document save with 2.1.2

### ISSUE THREAD

**Issue by fijemax** [couchbase/couchbase-lite-android#1818]
I recently update CouchbaseLite from 2.1.0 to 2.1.2.
Sometime and randomly a CouchbaseLiteException appear on document save action.

```
Caused by: CouchbaseLiteException{domain='CouchbaseLite.SQLite', code=1, msg=cannot rollback - no transaction is active}
        at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:51)
        at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:55)
        at com.couchbase.lite.AbstractDatabase.endTransaction(AbstractDatabase.java:714)
        at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:1049)
        at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:236)
        at com.couchbase.lite.Database.save(Database.java:25)
        at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:218)
        at com.couchbase.lite.Database.save(Database.java:25)
        ...

When this bug appear one time on a document, it seems corrupt and I can not anymore update and save this document.

**Comment by fijemax** [comment]
I get this logs before the previously backtrace:
```
2019-01-14 15:58:43.993 29312-29312/com.mapotempo.mapotempo_fleet_android.debug I/DB: CouchbaseLite/2.1.2-2 (Java; Android 8.1.0; Nexus 5X) Build/0 Commit/b72e27e LiteCore/ (2)
2019-01-14 15:58:43.994 29312-29312/com.mapotempo.mapotempo_fleet_android.debug I/DB: Opening Database@5c16a66{name='database2_8ee748b9ee'} at path /data/user/0/com.mapotempo.mapotempo_fleet_android.debug/files/database2_8ee748b9ee.cblite2
2019-01-14 15:58:44.000 29312-29312/com.mapotempo.mapotempo_fleet_android.debug I/LiteCore [DB]: Opening database /data/user/0/com.mapotempo.mapotempo_fleet_android.debug/files/database2_8ee748b9ee.cblite2/db.sqlite3
2019-01-14 15:58:44.016 29312-29312/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.DatabaseHandler: wss://mobile.fleet.mapotempo.com:4984/db
2019-01-14 15:58:44.570 29312-29312/com.mapotempo.mapotempo_fleet_android.debug W/LiteCore: SQLite error (code 6410): statement aborts at 123: [UPDATE kv_default SET version=?, body=?, flags=?, sequence=? WHERE key=? AND sequence=?] disk I/O error
2019-01-14 15:58:44.865 29312-29312/com.mapotempo.mapotempo_fleet_android.debug I/LiteCore [DB]: DataFile: abort transaction
2019-01-14 15:58:44.865 29312-29312/com.mapotempo.mapotempo_fleet_android.debug W/LiteCore: SQLite error (code 1): statement aborts at 1: [ROLLBACK] cannot rollback - no transaction is active
2019-01-14 15:58:44.867 29312-29312/com.mapotempo.mapotempo_fleet_android.debug D/AndroidRuntime: Shutting down VM
```
From [SQLite documentation](https://www.sqlite.org/rescode.html#ioerr_gettemppath) this error is due to :
```
(6410) SQLITE_IOERR_GETTEMPPATH
The SQLITE_IOERR_GETTEMPPATH error code is an extended error code for SQLITE_IOERR indicating that the VFS is unable to determine a suitable directory in which to place temporary files.

**Comment by pasin** [comment]
Can you enable verbose log level on the database domain and share the log after reproducing the issue?

**Comment by fijemax** [comment]
Hello,
I had this logs with this option :
```
Database.setLogLevel(LogDomain.DATABASE, LogLevel.VERBOSE);
```
```
2019-01-17 10:02:49.275 22350-22350/com.mapotempo.mapotempo_fleet_android.debug W/System.err: NumberParseException was thrown: Error type: NOT_A_NUMBER. The string supplied did not seem to be a phone number.
2019-01-17 10:02:49.301 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: SELECT fl_result(key), fl_result(fl_root(body)) FROM kv_default WHERE (fl_value(body, 'previous_mission_status_type_id') = 'mission_status_type-dZlxU7evZ2' AND fl_value(body, 'type') = 'mission_action_type') AND (flags & 1) = 0 ORDER BY fl_root(body)
    0|0|0| SEARCH TABLE kv_default USING INDEX mission_status_type (<expr>=?)
    0|0|0| USE TEMP B-TREE FOR ORDER BY
2019-01-17 10:02:49.302 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: {database2_8ee748b9ee={company_id=company-dZlxU3EX91, previous_mission_status_type_id=mission_status_type-dZlxU7evZ2, next_mission_status_type_id=mission_status_type-dZlxU6fBaK, label=null, type=mission_action_type, touched_at=null, group=null}, id=mission_action_type-dZlxUGddFy}
2019-01-17 10:02:49.303 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: {database2_8ee748b9ee={company_id=company-dZlxU3EX91, previous_mission_status_type_id=mission_status_type-dZlxU7evZ2, next_mission_status_type_id=mission_status_type-dZlxU8V-Z8, label=null, type=mission_action_type, touched_at=null, group=null}, id=mission_action_type-dZlxUEYAux}
2019-01-17 10:02:49.304 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: {database2_8ee748b9ee={company_id=company-dZlxU3EX91, previous_mission_status_type_id=mission_status_type-dZlxU7evZ2, next_mission_status_type_id=mission_status_type-dZlxU9OPaK, label=null, type=mission_action_type, touched_at=null, group=null}, id=mission_action_type-dZlxUI2Mcy}
2019-01-17 10:02:49.366 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: SELECT fl_result(key), fl_result(fl_root(body)) FROM kv_default WHERE (fl_value(body, 'previous_mission_status_type_id') = 'mission_status_type-dZlxU7evZ2' AND fl_value(body, 'type') = 'mission_action_type') AND (flags & 1) = 0 ORDER BY fl_root(body)
    0|0|0| SEARCH TABLE kv_default USING INDEX mission_action_type (<expr>=?)
    0|0|0| USE TEMP B-TREE FOR ORDER BY
2019-01-17 10:02:49.367 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: {database2_8ee748b9ee={company_id=company-dZlxU3EX91, previous_mission_status_type_id=mission_status_type-dZlxU7evZ2, next_mission_status_type_id=mission_status_type-dZlxU6fBaK, label=null, type=mission_action_type, touched_at=null, group=null}, id=mission_action_type-dZlxUGddFy}
2019-01-17 10:02:49.368 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: {database2_8ee748b9ee={company_id=company-dZlxU3EX91, previous_mission_status_type_id=mission_status_type-dZlxU7evZ2, next_mission_status_type_id=mission_status_type-dZlxU8V-Z8, label=null, type=mission_action_type, touched_at=null, group=null}, id=mission_action_type-dZlxUEYAux}
2019-01-17 10:02:49.369 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: {database2_8ee748b9ee={company_id=company-dZlxU3EX91, previous_mission_status_type_id=mission_status_type-dZlxU7evZ2, next_mission_status_type_id=mission_status_type-dZlxU9OPaK, label=null, type=mission_action_type, touched_at=null, group=null}, id=mission_action_type-dZlxUI2Mcy}
2019-01-17 10:02:49.445 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.model.ModelBase: Dateless Route for mission-2ecf46f60
2019-01-17 10:02:49.447 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.model.ModelBase: Dateless Route for mission-2ecf46f60
2019-01-17 10:02:49.450 22350-22350/com.mapotempo.mapotempo_fleet_android.debug W/System.err: NumberParseException was thrown: Error type: NOT_A_NUMBER. The string supplied did not seem to be a phone number.
2019-01-17 10:02:49.470 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: SELECT fl_result(key), fl_result(fl_root(body)) FROM kv_default WHERE (fl_value(body, 'previous_mission_status_type_id') = 'mission_status_type-dZlxU6fBaK' AND fl_value(body, 'type') = 'mission_action_type') AND (flags & 1) = 0 ORDER BY fl_root(body)
    0|0|0| SEARCH TABLE kv_default USING INDEX mission_status_type (<expr>=?)
    0|0|0| USE TEMP B-TREE FOR ORDER BY
2019-01-17 10:02:49.471 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: {database2_8ee748b9ee={company_id=company-dZlxU3EX91, previous_mission_status_type_id=mission_status_type-dZlxU6fBaK, next_mission_status_type_id=mission_status_type-dZlxU7evZ2, label=null, type=mission_action_type, touched_at=null, group=null}, id=mission_action_type-dZlxUAgbP6}
2019-01-17 10:02:49.472 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: {database2_8ee748b9ee={company_id=company-dZlxU3EX91, previous_mission_status_type_id=mission_status_type-dZlxU6fBaK, next_mission_status_type_id=mission_status_type-dZlxU9OPaK, label=null, type=mission_action_type, touched_at=null, group=null}, id=mission_action_type-dZlxUCS_Ok}
2019-01-17 10:02:49.517 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: SELECT fl_result(key), fl_result(fl_root(body)) FROM kv_default WHERE (fl_value(body, 'previous_mission_status_type_id') = 'mission_status_type-dZlxU6fBaK' AND fl_value(body, 'type') = 'mission_action_type') AND (flags & 1) = 0 ORDER BY fl_root(body)
    0|0|0| SEARCH TABLE kv_default USING INDEX mission_action_type (<expr>=?)
    0|0|0| USE TEMP B-TREE FOR ORDER BY
2019-01-17 10:02:49.518 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: {database2_8ee748b9ee={company_id=company-dZlxU3EX91, previous_mission_status_type_id=mission_status_type-dZlxU6fBaK, next_mission_status_type_id=mission_status_type-dZlxU7evZ2, label=null, type=mission_action_type, touched_at=null, group=null}, id=mission_action_type-dZlxUAgbP6}
2019-01-17 10:02:49.519 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: {database2_8ee748b9ee={company_id=company-dZlxU3EX91, previous_mission_status_type_id=mission_status_type-dZlxU6fBaK, next_mission_status_type_id=mission_status_type-dZlxU9OPaK, label=null, type=mission_action_type, touched_at=null, group=null}, id=mission_action_type-dZlxUCS_Ok}
2019-01-17 10:02:49.730 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.lib.utils.StaticMapURLHelper$TileHostingURLBuilder: https://maps.tilehosting.com/styles/basic/static/-0.398080,43.302047,18/500x182.png?key=LLRxrAW8qh4LHSzTw6qo
2019-01-17 10:02:49.743 22350-22350/com.mapotempo.mapotempo_fleet_android.debug W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
2019-01-17 10:02:49.757 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.lib.utils.StaticMapURLHelper$TileHostingURLBuilder: https://maps.tilehosting.com/styles/basic/static/-0.398080,43.302047,18/500x182.png?key=LLRxrAW8qh4LHSzTw6qo
2019-01-17 10:02:49.790 22350-22350/com.mapotempo.mapotempo_fleet_android.debug I/Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
2019-01-17 10:02:51.900 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: SELECT fl_result(key), fl_result(fl_root(body)) FROM kv_default WHERE (fl_value(body, 'type') = 'company') AND (flags & 1) = 0 ORDER BY fl_value(body, 'date')
    0|0|0| SEARCH TABLE kv_default USING INDEX mission_status_type (<expr>=?)
    0|0|0| USE TEMP B-TREE FOR ORDER BY
2019-01-17 10:02:51.901 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: {database2_8ee748b9ee={name=Mapotempo - Cynthia, default_mission_status_type_id=mission_status_type-dZlxU6fBaK, type=company, touched_at=null}, id=company-dZlxU3EX91}
2019-01-17 10:02:51.903 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/com.mapotempo.fleet.core.accessor.AccessBase: Create new instance of type:mission_action
2019-01-17 10:02:51.917 22350-22433/com.mapotempo.mapotempo_fleet_android.debug W/C4Socket: C4Socket.write() handle -> 532211315888
2019-01-17 10:02:51.918 22350-22433/com.mapotempo.mapotempo_fleet_android.debug W/C4Socket: completedWrite(long) handle -> 532211315888, byteCount -> 86
2019-01-17 10:02:51.921 22350-22433/com.mapotempo.mapotempo_fleet_android.debug W/C4Socket: C4Socket.write() handle -> 532211318576
2019-01-17 10:02:51.922 22350-22433/com.mapotempo.mapotempo_fleet_android.debug W/C4Socket: completedWrite(long) handle -> 532211318576, byteCount -> 87
2019-01-17 10:02:51.928 22350-22350/com.mapotempo.mapotempo_fleet_android.debug W/LiteCore: SQLite error (code 6410): statement aborts at 123: [UPDATE kv_default SET version=?, body=?, flags=?, sequence=? WHERE key=? AND sequence=?] disk I/O error
2019-01-17 10:02:51.932 22350-22350/com.mapotempo.mapotempo_fleet_android.debug I/LiteCore [DB]: DataFile: abort transaction
2019-01-17 10:02:51.932 22350-22350/com.mapotempo.mapotempo_fleet_android.debug W/LiteCore: SQLite error (code 1): statement aborts at 1: [ROLLBACK] cannot rollback - no transaction is active
2019-01-17 10:02:51.934 22350-22350/com.mapotempo.mapotempo_fleet_android.debug D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2019-01-17 10:02:51.937 22350-22350/com.mapotempo.mapotempo_fleet_android.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapotempo.mapotempo_fleet_android.debug, PID: 22350
    java.lang.RuntimeException: CouchbaseLiteException{domain='CouchbaseLite.SQLite', code=1, msg=cannot rollback - no transaction is active}
        at com.mapotempo.fleet.core.model.ModelBase.save(ModelBase.java:77)
        at com.mapotempo.lib.fragments.mission.MissionDetailsFragment.doAction(MissionDetailsFragment.java:644)
        at com.mapotempo.lib.fragments.mission.MissionDetailsFragment.access$600(MissionDetailsFragment.java:78)
        at com.mapotempo.lib.fragments.mission.MissionDetailsFragment$7.onClick(MissionDetailsFragment.java:603)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: CouchbaseLiteException{domain='CouchbaseLite.SQLite', code=1, msg=cannot rollback - no transaction is active}
        at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:51)
        at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:55)
        at com.couchbase.lite.AbstractDatabase.endTransaction(AbstractDatabase.java:714)
        at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:1049)
        at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:236)
        at com.couchbase.lite.Database.save(Database.java:25)
        at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:218)
        at com.couchbase.lite.Database.save(Database.java:25)
        at com.mapotempo.fleet.core.model.ModelBase.save(ModelBase.java:68)
        at com.mapotempo.lib.fragments.mission.MissionDetailsFragment.doAction(MissionDetailsFragment.java:644) 
        at com.mapotempo.lib.fragments.mission.MissionDetailsFragment.access$600(MissionDetailsFragment.java:78) 
        at com.mapotempo.lib.fragments.mission.MissionDetailsFragment$7.onClick(MissionDetailsFragment.java:603) 
        at android.view.View.performClick(View.java:6294) 
        at android.view.View$PerformClick.run(View.java:24770) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: LiteCoreException{domain=3, code=1, msg=cannot rollback - no transaction is active}
        at com.couchbase.litecore.C4Database.endTransaction(Native Method)
        at com.couchbase.litecore.C4Database.endTransaction(C4Database.java:112)
        at com.couchbase.lite.AbstractDatabase.endTransaction(AbstractDatabase.java:712)
        at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:1049) 
        at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:236) 
        at com.couchbase.lite.Database.save(Database.java:25) 
        at com.couchbase.lite.AbstractDatabase.save(AbstractDatabase.java:218) 
        at com.couchbase.lite.Database.save(Database.java:25) 
        at com.mapotempo.fleet.core.model.ModelBase.save(ModelBase.java:68) 
        at com.mapotempo.lib.fragments.mission.MissionDetailsFragment.doAction(MissionDetailsFragment.java:644) 
        at com.mapotempo.lib.fragments.mission.MissionDetailsFragment.access$600(MissionDetailsFragment.java:78) 
        at com.mapotempo.lib.fragments.mission.MissionDetailsFragment$7.onClick(MissionDetailsFragment.java:603) 
        at android.view.View.performClick(View.java:6294) 
        at android.view.View$PerformClick.run(View.java:24770) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by fijemax** [comment]
When I come back on 2.1.0 version, this bug not appear.

**Comment by fijemax** [comment]
I'am not sure but 2.1.2 integrate this commit :
https://github.com/couchbase/couchbase-lite-core/pull/579
Do you thing there is the cause of 
```
(6410) SQLITE_IOERR_GETTEMPPATH ?

**Comment by pasin** [comment]
@fijemax sorry for delay response. I don't think couchbase/couchbase-lite-core#579 is related to this issue as it's a tmp part used for different purposes (for database upgrading or copying).

**Comment by pasin** [comment]
@borrrden @snej Do we change a configuration for `SQLITE_TEMP_STORE` or something related to that in 2.1.2?

**Comment by pasin** [comment]
@fijemax Are you using CE or EE version?

**Comment by pasin** [comment]
Note: 

From https://github.com/couchbase/couchbase-lite-core/blob/650c27df206fcc62167a5e0a6a8769da4d700bdd/CMakeLists.txt#L52, we are setting the SQLITE_TEMP_STORE=2 for EE edition.

**Comment by pasin** [comment]
@fijemax Can you switch to use Enterprise Edition to see if the issue is gone?

**Comment by fijemax** [comment]
We use
com.couchbase.lite:couchbase-lite-android:2.1.2@aar the http://mobile.maven.couchbase.com/maven2/dev/ repository

**Comment by borrrden** [comment]
EE is com.couchbase.lite:couchbase-lite-android-ee (note -ee on the end)

**Comment by fijemax** [comment]
From same maven repo ?

Fail with this gradle config:
```
repositories {
  jcenter()
  maven { url "http://mobile.maven.couchbase.com/maven2/dev/" }
}

dependencies {
  implementation 'com.couchbase.lite:couchbase-lite-android-ee:2.1.2@aar'
}

**Comment by fijemax** [comment]
Hello @pasin and thank you,
The bug don't appear with EE edition.

**Comment by borrrden** [comment]
There seems to even be precedent for setting it to 3 on Android (from Mozilla).  So I think we should work on an appropriate set of defaults (2 might be good everywhere, but need to confirm about iOS).

**Comment by borrrden** [comment]
We’ve had loads of trouble with c++ and c code not being able to reliably find a temp path that is writable on Android. It’s just so fragmented with various vendors doing whatever they want even if it doesn’t make sense. The only truly reliable way is from Java and the Android context object which is not available outside of a Java application.   My guess is that the same factors are at play here.

**Comment by snej** [comment]
Why don't we add a LiteCore function, like `c4_useTempDir`, that the app can use to tell LiteCore where the writeable temp directory is?

(I'm a bit squeamish about using SQLITE_TEMP_STORE=2 because it will increase RAM usage during queries. I don't know about Android, but on iOS this can lead to the app being killed for hogging RAM.)

**Comment by pasin** [comment]
I have just created an issue on Lite Core before noticing that we have more discussion here. Let's continue discussion in LiteCore issue.
