### ISSUE TITLE
testDocumentChangeOnDocumentPurged is failing

### ISSUE THREAD

**Issue by jayahariv** [couchbase/couchbase-lite-android#1834]
```
testDocumentChangeOnDocumentPurged[test(AVD) - 4.4.2] FAILED 
        CouchbaseLiteException{domain='CouchbaseLite', code=18, msg=transaction not closed}
        at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:51)
```

**Comment by pasin** [comment]
I was not able to reproduce the issue on my mac even using arm api19 emulator and the stacktrace on travis env is not helpful as it's cutoff.

**Comment by jayahariv** [comment]
It seldom happens in local machine, but travis PR failure is frequent.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pasin** [comment]
Finally I was able to get the full stacktrace.

```
CouchbaseLiteException{domain='CouchbaseLite', code=18, msg=transaction not closed}
I/TestRunner( 1696): 	at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:51)
I/TestRunner( 1696): 	at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:55)
I/TestRunner( 1696): 	at com.couchbase.lite.AbstractDatabase.closeC4DB(AbstractDatabase.java:973)
I/TestRunner( 1696): 	at com.couchbase.lite.AbstractDatabase.close(AbstractDatabase.java:552)
I/TestRunner( 1696): 	at com.couchbase.lite.Database.close(Database.java:25)
I/TestRunner( 1696): 	at com.couchbase.lite.BaseTest.closeDB(BaseTest.java:182)
I/TestRunner( 1696): 	at com.couchbase.lite.BaseTest.tearDown(BaseTest.java:130)
I/TestRunner( 1696): 	at com.couchbase.lite.DocumentTest.tearDown(DocumentTest.java:124)
I/TestRunner( 1696): 	at java.lang.reflect.Method.invokeNative(Native Method)
I/TestRunner( 1696): 	at java.lang.reflect.Method.invoke(Method.java:515)
I/TestRunner( 1696): 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
I/TestRunner( 1696): 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
I/TestRunner( 1696): 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
I/TestRunner( 1696): 	at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:80)
I/TestRunner( 1696): 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
I/TestRunner( 1696): 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
I/TestRunner( 1696): 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
I/TestRunner( 1696): 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
I/TestRunner( 1696): 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
I/TestRunner( 1696): 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
I/TestRunner( 1696): 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
I/TestRunner( 1696): 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
I/TestRunner( 1696): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
I/TestRunner( 1696): 	at org.junit.runners.Suite.runChild(Suite.java:128)
I/TestRunner( 1696): 	at org.junit.runners.Suite.runChild(Suite.java:27)
I/TestRunner( 1696): 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
I/TestRunner( 1696): 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
I/TestRunner( 1696): 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
I/TestRunner( 1696): 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
I/TestRunner( 1696): 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
I/TestRunner( 1696): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
I/TestRunner( 1696): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
I/TestRunner( 1696): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
I/TestRunner( 1696): 	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
I/TestRunner( 1696): 	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
I/TestRunner( 1696): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
I/TestRunner( 1696): Caused by: LiteCoreException{domain=1, code=18, msg=transaction not closed}
I/TestRunner( 1696): 	at com.couchbase.litecore.C4Database.close(Native Method)
I/TestRunner( 1696): 	at com.couchbase.litecore.C4Database.close(C4Database.java:66)
I/TestRunner( 1696): 	at com.couchbase.lite.AbstractDatabase.closeC4DB(AbstractDatabase.java:971)
I/TestRunner( 1696): 	... 33 more
```

**Comment by pasin** [comment]
I think the behavior is similar to what we found in iOS but the failure is different. It's a race condition between getting the document change notification and transaction close. For Android, the test itself was done and passed before the transaction was actually closed.
