### ISSUE TITLE
Query crashes on empty database after index removal

### ISSUE THREAD

**Issue by nantoka69** [couchbase/couchbase-lite-android#1849]
I am currently renewing an old project that was originally using Couchbase Lite for Android version 1.0.4.

When I upgraded it to 1.4.4 (as the old version did not work with Oreo) I got an exception when executing a query on a view whose index has been deleted if the database is an empty database.

I have created a small sample function below which reproduces the crash. Removing the comments from the code that creates a first document results in avoiding the crash. I have attached the stack trace below as well.

I understand that the circumstances are a bit "exotic" but for my feeling the database should not throw an exception in this situation or at least provide a clear message in the exception.

Can you please have a look at this?

Cheers

Joerg

==============================================

Database database;
    Manager manager;
    com.couchbase.lite.View myView;

    private void loadDatabase() {

        try {
            manager = new Manager(new AndroidContext(getApplicationContext()), Manager.DEFAULT_OPTIONS);
        } catch (IOException e) {
            e.printStackTrace();
        }

        try {
            database = manager.getDatabase("couchdb");
        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
        }

        Map<String, Object> properties = new HashMap<>();
        properties.put("key2", "value2");

        myView = database.getView("myview");
        myView.setMap(
                new Mapper() {
                    @Override
                    public void map(Map<String, Object> document, Emitter emitter) {
                        if (document.get("key1") == "value1"){
                            emitter.emit("key1", "value1");
                        }
                    }
                },
                "1"
        );

        /*
        Document document = database.createDocument();
        try {
            document.putProperties(properties);
        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
        }
        */

        myView.deleteIndex();

        try {
            myView.createQuery().run();
        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
        }
    }

======

2019-01-28 22:11:48.271 21982-21982/de.nantoka.couchbase_test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.nantoka.couchbase_test, PID: 21982
    java.lang.RuntimeException: Unable to start activity ComponentInfo{de.nantoka.couchbase_test/de.nantoka.couchbase_test.MainActivity}: com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: no such table: maps_1 (code 1): , while compiling: SELECT key, value, docid, revs.sequence FROM 'maps_1', revs, docs WHERE 1 AND revs.sequence = 'maps_1'.sequence AND docs.doc_id = revs.doc_id ORDER BY key, docid LIMIT ? OFFSET ?
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3297)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3405)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: no such table: maps_1 (code 1): , while compiling: SELECT key, value, docid, revs.sequence FROM 'maps_1', revs, docs WHERE 1 AND revs.sequence = 'maps_1'.sequence AND docs.doc_id = revs.doc_id ORDER BY key, docid LIMIT ? OFFSET ?
        at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:718)
        at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:431)
        at com.couchbase.lite.internal.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:595)
        at com.couchbase.lite.internal.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:64)
        at com.couchbase.lite.internal.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at com.couchbase.lite.internal.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:48)
        at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1300)
        at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1239)
        at com.couchbase.lite.storage.SQLiteStorageEngineBase.rawQuery(SQLiteStorageEngineBase.java:183)
        at com.couchbase.lite.store.SQLiteViewStore.runQuery(SQLiteViewStore.java:1017)
        at com.couchbase.lite.store.SQLiteViewStore.regularQuery(SQLiteViewStore.java:629)
        at com.couchbase.lite.View.query(View.java:359)
        at com.couchbase.lite.Database.queryViewNamed(Database.java:2455)
        at com.couchbase.lite.Query.run(Query.java:446)
        at de.nantoka.couchbase_test.MainActivity.loadDatabase(MainActivity.java:113)
        at de.nantoka.couchbase_test.MainActivity.onCreate(MainActivity.java:42)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3250)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3405) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by pasin** [comment]
Yes, deleting the index and re-query shouldn't cause the exception. This sounds like a bug.
