### ISSUE TITLE
java.lang.ClassCastException: com.couchbase.lite.Attachment cannot be cast to java.util.Map

### ISSUE THREAD

**Issue by PankaJJakhar** [couchbase/couchbase-lite-android#343]
This is the intermittent issue that I encountered with while saving attachment to a document.

Here is the full stack trace:

```
06-13 15:23:09.458: E/RemoteRequest(19355): java.lang.ClassCastException: com.couchbase.lite.Attachment cannot be cast to java.util.Map
06-13 15:23:09.458: E/RemoteRequest(19355): 	at com.couchbase.lite.internal.RevisionInternal.mutateAttachments(RevisionInternal.java:273)
06-13 15:23:09.458: E/RemoteRequest(19355): 	at com.couchbase.lite.Database.stubOutAttachmentsInRevBeforeRevPos(Database.java:2832)
06-13 15:23:09.458: E/RemoteRequest(19355): 	at com.couchbase.lite.replicator.Pusher$2.onCompletion(Pusher.java:342)
06-13 15:23:09.458: E/RemoteRequest(19355): 	at com.couchbase.lite.support.RemoteRequest$2.run(RemoteRequest.java:315)
06-13 15:23:09.458: E/RemoteRequest(19355): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
06-13 15:23:09.458: E/RemoteRequest(19355): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
06-13 15:23:09.458: E/RemoteRequest(19355): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
06-13 15:23:09.458: E/RemoteRequest(19355): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
06-13 15:23:09.458: E/RemoteRequest(19355): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
06-13 15:23:09.458: E/RemoteRequest(19355): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
06-13 15:23:09.458: E/RemoteRequest(19355): 	at java.lang.Thread.run(Thread.java:856)
06-13 15:23:09.503: W/dalvikvm(19355): threadid=12: thread exiting with uncaught exception (group=0x41859930)
06-13 15:23:09.508: E/AndroidRuntime(19355): FATAL EXCEPTION: AsyncTask #2
06-13 15:23:09.508: E/AndroidRuntime(19355): java.lang.RuntimeException: An error occured while executing doInBackground()
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at java.lang.Thread.run(Thread.java:856)
06-13 15:23:09.508: E/AndroidRuntime(19355): Caused by: java.lang.NullPointerException
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at com.couchbase.lite.Database.generateIDForRevision(Database.java:3179)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at com.couchbase.lite.Database.putRevision(Database.java:3587)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at com.couchbase.lite.Database.putRevision(Database.java:3421)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at com.couchbase.lite.Document.putProperties(Document.java:415)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:102)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at com.innotion.protean.cblite.CBLiteConnector.pushAttachments(CBLiteConnector.java:1249)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at com.innotion.protean.controllerfactory.ResultController.pushAttachments(ResultController.java:68)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at com.innotion.protean.formsubmission.ChecklistActivity$4.doInBackground(ChecklistActivity.java:604)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at com.innotion.protean.formsubmission.ChecklistActivity$4.doInBackground(ChecklistActivity.java:1)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
06-13 15:23:09.508: E/AndroidRuntime(19355): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
```

**Comment by tleyden** [comment]
Closing this as not reproducible
