### ISSUE TITLE
Replace default Android storage engine to support JSON docs > 2Meg

### ISSUE THREAD

**Issue by ajres** [couchbase/couchbase-lite-android#357]
The default android storage engine, that wraps SQLite has a CursorWindow class that limits content of a single row to 2MBytes. This results in errors for large JSON documents.

CursorWindow is specific to the Android storage engine framework, the issue is not seen on iOS or Portable Java.

Need a strategy for replacing the default Android storage engine to fix this.

1) Is it possible to access the embedded android SQLite directly via our own storage engine, can we cope with different SQLite versions on different devices?

2) Provide an optional external SQLite native library (i.e. from Portable Java) with our own storage engine. Can we cover all Android target architectures (ARM/Intel?) using a custom build.

**Comment by cesine** [comment]
hi @tleyden do you know if the ForestDB team tried LevelDB  https://github.com/google/leveldb  and why that wasn't the choice for replacing the storage engine on mobile? https://issues.couchbase.com/issues/?jql=text%20~%20%22LevelDB%22 

context: we just hit an SQLite error in Android 5.0 which was fixed in cblite so we are trying to decide what would be the best upgrade plan for our old touchdb app (we haven't tried couchbase yet, we are still using couchdb with REST bolted on for image upload)

**Comment by tleyden** [comment]
The idea behind forestdb is to build something more performant than leveldb or the other kvstores available.  

Here are the [published benchmarks](https://github.com/couchbase/forestdb/wiki/Performance-Results)

**Comment by tleyden** [comment]
> we haven't tried couchbase yet, we are still using couchdb with REST bolted on for image upload

cblite *should* still be compatible with couchdb -- although if you search the issue tracker for "couchdb" you might find some outstanding issues.  It's not in our release test matrix, so is more likely to have issues than couchbase server + sync gw.

**Comment by zgramana** [comment]
We're going to be providing an optional, custom SQLite binary as part of our upcoming 1.2 release which should resolve this issue.

**Comment by hideki** [comment]
Notes for testing:
- Inserting document does not have issue with the doc size > 2MB.
- Reading document which size is larger than 2MB causes this issue.

```
java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetString(Native Method)
at android.database.CursorWindow.getString(CursorWindow.java:434)
at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
at com.couchbase.lite.android.SQLiteCursorWrapper.getString(SQLiteCursorWrapper.java:27)
at com.couchbase.lite.store.SQLiteStore.getDocument(SQLiteStore.java:692)
at com.couchbase.lite.Database.getDocument(Database.java:1283)
at com.couchbase.lite.Document.getRevision(Document.java:219)
at com.couchbase.lite.Document.getCurrentRevision(Document.java:112)
at com.couchbase.lite.Document.getProperties(Document.java:165)
at com.couchbase.lite.performance.Test3_ReadDocs.testReadDocsPerformance(Test3_ReadDocs.java:84)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

**Comment by NitzDKoder** [comment]
@hideki ForestDb supports doc more than 2mb?

**Comment by hideki** [comment]
@NitzDKoder no limitation.

FYI, from 1.2.0, SQLite version does not have 2mb limitation anymore.
