### ISSUE TITLE
ChangeTracker exception when replicating to CouchDB 1.2.0

### ISSUE THREAD

**Issue by cfmak** [couchbase/couchbase-lite-android#428]
I am using couhbase-lite-android version 1.0.2. I am replicating to a remote CouchDB server 1.2.0.
Whenever the ChangeTracker runs, it throws this exception and prints on the log, and since ChangeTracker is run periodically, this exception is printed periodically.

Upon inspecting the remote CouchDB, it seems that all contents in the mobile client is replicated to remote, and if I modify the remote, the mobile database also updates correctly.

fyi, the replication content size is small (hundreds of kB at most).
```
10-15 15:28:59.195    8887-8933/com.mangohealth.mango E/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@42a63ec0: Exception in change tracker
    org.codehaus.jackson.JsonParseException: Unexpected end-of-input: expected close marker for ARRAY (from [Source: org.apache.http.conn.EofSensorInputStream@4341b310; line: 1, column: 1])
            at [Source: org.apache.http.conn.EofSensorInputStream@4341b310; line: 2, column: 14]
            at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432)
            at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385)
            at org.codehaus.jackson.impl.JsonParserMinimalBase._reportInvalidEOF(JsonParserMinimalBase.java:318)
            at org.codehaus.jackson.impl.JsonParserBase._handleEOF(JsonParserBase.java:469)
            at org.codehaus.jackson.impl.Utf8StreamParser._skipWSOrEnd(Utf8StreamParser.java:2322)
            at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:438)
            at org.codehaus.jackson.map.deser.std.UntypedObjectDeserializer.mapArray(UntypedObjectDeserializer.java:157)
            at org.codehaus.jackson.map.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:51)
            at org.codehaus.jackson.map.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:319)
            at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:249)
            at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:33)
            at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2723)
            at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1900)
            at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:331)
            at java.lang.Thread.run(Thread.java:841)
```

**Comment by hideki** [comment]
user used CouchDB v1.2.0 and the ticket have not been updated for 2 years. I will close this.
