### ISSUE TITLE
Build issue with Android Studio 0.8.14

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-android#461]
Android Studio 0.8.14 requires to use gradle 2.1 then couchbase-lite-android is failed to built with gradle 2.1.

Changes:

gradle/wrapper/gradle-wrapper.properties
```
...
distributionUrl=https\://services.gradle.org/distributions/gradle-2.1-all.zip
```

build.gradle
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:0.13.2'
    }
}
```

Build result:
```
$ ./gradlew --stacktrace

Caused by: java.lang.NullPointerException
	at org.gradle.api.plugins.MavenPlugin$4.execute(MavenPlugin.java:133)
	at org.gradle.api.plugins.MavenPlugin$4.execute(MavenPlugin.java:124)
	at org.gradle.configuration.project.DelayedConfigurationActions.execute(DelayedConfigurationActions.java:27)
	at org.gradle.configuration.project.DelayedConfigurationActions.execute(DelayedConfigurationActions.java:22)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
	... 52 more


BUILD FAILED

Total time: 4.02 secs
```

**Comment by hideki** [comment]
Android Studio is already v1.0 now. So I believe this ticket is out-dated.
