### ISSUE TITLE
Couchbase sync replication fails on O2 3G data connection (non Wi-Fi)

### ISSUE THREAD

**Issue by dobridog** [couchbase/couchbase-lite-android#499]
Our sync replication setup is much like to-do sample app and does what it is suppose to over WiFi or Vodafone IE 3G network. However on a O2 network we keep seeing same issue every time. This issue is potentially related to: https://github.com/couchbaselabs/CouchCocoa/issues/22#issuecomment-5404773

Environment:
- Couchbase lite 1.0.4
- Couchbase server 3.0.1
- Sync Gateway 1.0.3

01-22 22:41:50.064 3415-6658/com.knedle.zoo E/RemoteRequest﹕ io exception. url: http://ec2-54-77-10-229.eu-west-1.compute.amazonaws.com:4984/sync_gateway/_revs_diff
org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: org.apache.http.conn.EofSensorInputStream@3069a43; line: 1, column: 2]
at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432)
at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385)
at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:306)
at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2084)
at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:600)
at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:486)
at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2761)
at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2709)
at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1900)
at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:227)
at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:101)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
01-22 22:41:50.064 3415-6658/com.knedle.zoo E/Sync﹕ com.couchbase.lite.replicator.PusherInternal@3910508: Progress: set error = org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: org.apache.http.conn.EofSensorInputStream@3069a43; line: 1, column: 2]
01-22 22:41:50.065 3415-6705/com.knedle.zoo E/Sync﹕ PusherInternal stopGraceful.run() finished
01-22 22:41:50.065 3415-3415/com.knedle.zoo E/UserDatabase﹕ Sync error: org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: org.apache.http.conn.EofSensorInputStream@3069a43; line: 1, column: 2]
org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: org.apache.http.conn.EofSensorInputStream@3069a43; line: 1, column: 2]
at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432)
at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385)
at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:306)
at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2084)
at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:600)
at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:486)
at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2761)
at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2709)
at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1900)
at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:227)
at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:101)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

**Comment by hideki** [comment]
@dobridog It seems JSON data from Sync Gateway is corrupted. Is it possible to capture the receiving data from Sync Gatweay by using network sniffing tool?

**Comment by dobridog** [comment]
We'll see what can be done. FWD: @urker can we get network trace from the sync gateway on our aws instance?

I wouldn't think there is a way for me to sniff the cell data on a device. Can we enable HTTP logging on couchbase lite?

**Comment by hideki** [comment]
We did not add Logging for incoming data.
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.0.3/src/main/java/com/couchbase/lite/support/RemoteRequest.java#L227

Can you build Couchbase Lite form source code? Build instruction is in README. https://github.com/couchbase/couchbase-lite-android

If you can try to build, you need to add logging code at Line 227 of RemoteRequest.java 

To logging, add Log.e("<TAG>", "<data>") in codes.

Hope this helps you!

**Comment by urker** [comment]
Hi Guys ,I have some thoughts on this issue ,  @hideki could it be that o2 provider is removing user name and pwd from headers since we are not using https , we can easily test this buy adding certs to conf file . I didn't see anything unusual in logs , except Login required trace

**Comment by tleyden** [comment]
@hideki what about adding a new logging category in the client that will log the entire response?  it would of course be turned off by default.  Then @dobridog and @urker could enable it and see what is being returned by the remote end.  (my guess is that is a captive portal error page or some other html)

**Comment by hideki** [comment]
@Jamiltz and @ajres are you using O2 network? If so, can you try ToDo  Lite sample app work with O2 network?

**Comment by hideki** [comment]
Hi @urker and @dobridog  
Following is sample modification to log the data from sync_gateway. This sample's code-base is current master branch. You can apply similar code to 1.0.3 (https://github.com/couchbase/couchbase-lite-android/tree/1.0.3). 

Code location >>  https://github.com/couchbase/couchbase-lite-java-core/blob/1226295a24c26a8bdc3946c35f43ce74c93e80ad/src/main/java/com/couchbase/lite/support/RemoteRequest.java#L213

sample code
```
                HttpEntity entity = response.getEntity();
                if (entity != null) {
                    InputStream inputStream = null;
                    try {
                        inputStream = entity.getContent();
                        // decompress if contentEncoding is gzip
                        if(Utils.isGzip(entity)){
                            inputStream = new GZIPInputStream(inputStream);
                        }

                        BufferedInputStream stream = new BufferedInputStream(inputStream);
                        stream.mark(10000000);
                        byte[] b = new byte[(int)entity.getContentLength()];
                        int len = stream.read(b);
                        String data = new String(b);
                        Log.e("<TAG>", data);

                        stream.reset();

                        fullBody = Manager.getObjectMapper().readValue(stream, Object.class);
                    } finally {
                        try {
                            inputStream.close();
                        } catch (IOException e) {
                        }
                    }
                }
```

**Comment by dobridog** [comment]
In the mean time I've reproduced this on Grocery sync sample application. @hideki as per your suggestion the block was added in com.couchbase.lite.support.RemoteRequest, seams like unexpected XML response. 

```
01-30 23:47:09.115  27618-27642/com.couchbase.grocerysync V/Sync﹕ com.couchbase.lite.support.RemoteRequest@4404b02: RemoteRequest called httpClient.execute, url: http://demo-mobile.couchbase.com/grocery-sync/_local/7fa778cdeb93fc4aea47bac12cb458fa892c7721
    [ 01-30 23:47:09.116 27618:27642 E/<TAG>
    ]
    <?xml version="1.0"?>
    <!DOCTYPE wml PUBLIC "-//WAPFORUM//DTD WML 1.1//EN" "http://www.wapforum.org/DTD/wml_1.1.xml">
    <wml>
    <card id="card1" title="ERROR">
    <p>
    The requested item could not be found!<br/>(Status Code: 404)
    <do type="prev" label="back">
    <prev/>
    </do>
    </p>
    </card>
    </wml>
01-30 23:47:09.129  27618-27642/com.couchbase.grocerysync E/RemoteRequest﹕ io exception.  url: http://demo-mobile.couchbase.com/grocery-sync/_local/7fa778cdeb93fc4aea47bac12cb458fa892c7721
    org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
            at [Source: java.io.BufferedInputStream@4683c7b; line: 1, column: 2]
            at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
            at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
            at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
            at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2090)
            at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:606)
            at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:492)
            at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2770)
            at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2718)
            at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1909)
            at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:231)
            at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:104)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
01-30 23:47:09.129  27618-27642/com.couchbase.grocerysync V/Sync﹕ com.couchbase.lite.support.RemoteRequest@4404b02: RemoteRequest finally block.  url: http://demo-mobile.couchbase.com/grocery-sync/_local/7fa778cdeb93fc4aea47bac12cb458fa892c7721
```

**Comment by tleyden** [comment]
This appears to be a problem with your data provider mangling the response.  Can you contact their support?

**Comment by tleyden** [comment]
Compare the resoonse in an http sniffer (wireshark, httpscoop) and you will see the problem.

**Comment by hideki** [comment]
@dobridog I wonder if provider blocks port 4984. For experiment, can you try to use port 80 for Sync-Gateway?
