### ISSUE TITLE
connectedAndroidTest failed to run to completion. Reason: 'Instrumentation run failed due to 'java.util.concurrent.RejectedExecutionException''. Check device logcat for details

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/couchbase-lite-android#559]
```
com.couchbase.lite.replicator.ReplicationTest > testContinuousPullEntersIdleState[hudson_en-US_160_WVGA_android-19_armeabi-v7a_param(AVD) - 4.4.2] [32mSUCCESS [0m
com.couchbase.lite.replicator.ReplicationTest > testContinuousPullReplicationGoesIdleTwice[hudson_en-US_160_WVGA_android-19_armeabi-v7a_param(AVD) - 4.4.2] [31mFAILED [0m
Test failed to run to completion. Reason: 'Instrumentation run failed due to 'java.util.concurrent.RejectedExecutionException''. Check device logcat for details
Tests on hudson_en-US_160_WVGA_android-19_armeabi-v7a_param(AVD) - 4.4.2 failed: Instrumentation run failed due to 'java.util.concurrent.RejectedExecutionException'
deleteDir(/home/couchbase/jenkins/workspace/couchbase-lite-android-build/build/outputs/reports/androidTests/connected) returned: true
:connectedAndroidTest FAILED
:connectedAndroidTest (Thread[main,5,main]) completed. Took 7 mins 32.741 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':connectedAndroidTest'.
> There were failing tests. See the report at: file:///home/couchbase/jenkins/workspace/couchbase-lite-android-build/build/outputs/reports/androidTests/connected/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED
```

http://172.23.113.52/job/couchbase-lite-android-build/105/console
http://172.23.113.52/job/couchbase-lite-android-build/lastSuccessfulBuild/artifact/logcat.txt

**Comment by hideki** [comment]
http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-build/105/artifact/logcat.txt

Additional Log message
```
03-29 19:36:27.826 E/AndroidRuntime( 1063): Process: com.couchbase.lite.test, PID: 1063
03-29 19:36:27.826 E/AndroidRuntime( 1063): java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@b32a5f08 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@b32ad3e8[Shutting down, pool size = 1, active threads = 0, queued tasks = 2, completed tasks = 27]
03-29 19:36:27.826 E/AndroidRuntime( 1063): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
03-29 19:36:27.826 E/AndroidRuntime( 1063): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
03-29 19:36:27.826 E/AndroidRuntime( 1063): 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:298)
03-29 19:36:27.826 E/AndroidRuntime( 1063): 	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:503)
03-29 19:36:27.826 E/AndroidRuntime( 1063): 	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:602)
03-29 19:36:27.826 E/AndroidRuntime( 1063): 	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:593)
03-29 19:36:27.826 E/AndroidRuntime( 1063): 	at com.couchbase.lite.replicator.ReplicationInternal.fireTrigger(ReplicationInternal.java:190)
03-29 19:36:27.826 E/AndroidRuntime( 1063): 	at com.couchbase.lite.replicator.PullerInternal$13.run(PullerInternal.java:985)
03-29 19:36:27.826 E/AndroidRuntime( 1063): 	at java.lang.Thread.run(Thread.java:841)
03-29 19:36:27.836 W/ActivityManager(  371): Error in app com.couchbase.lite.test running instrumentation ComponentInfo{com.couchbase.lite.test/android.test.InstrumentationTestRunner}:
03-29 19:36:27.836 W/ActivityManager(  371):   java.util.concurrent.RejectedExecutionException
03-29 19:36:27.836 D/AndroidRuntime( 1052): Shutting down VM
03-29 19:36:27.836 W/ActivityManager(  371):   java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@b32a5f08 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@b32ad3e8[Shutting down, pool size = 1, active threads = 0, queued tasks = 2, completed tasks = 27]
03-29 19:36:27.896 D/dalvikvm( 1052): GC_CONCURRENT freed 2386K, 81% free 571K/2960K, paused 2ms+4ms, total 34ms
03-29 19:36:28.136 I/ActivityManager(  371): Force stopping com.couchbase.lite.test appid=10052 user=0: finished inst
03-29 19:36:28.136 I/ActivityManager(  371): Killing 1063:com.couchbase.lite.test/u0a52 (adj 0): stop com.couchbase.lite.test
```
