### ISSUE TITLE
Crash reading documents with size 18Mb

### ISSUE THREAD

**Issue by jalinvi** [couchbase/couchbase-lite-android#635]
Hi! 

I wanted to test performance when reading a big document (18.7Mb). When I call the function:

```
Document document = ((GlobalAplication) getApplication()).getDatabase().getExistingDocument("DocID");
```

I get the following error:

```
Stack: 
I/REPORT  ( 5822): java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
I/REPORT  ( 5822): 	at android.database.CursorWindow.nativeGetString(Native Method)
I/REPORT  ( 5822): 	at android.database.CursorWindow.getString(CursorWindow.java:434)
I/REPORT  ( 5822): 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
I/REPORT  ( 5822): 	at com.couchbase.lite.android.AndroidSQLiteStorageEngine$SQLiteCursorWrapper.getString(AndroidSQLiteStorageEngine.java:205)
I/REPORT  ( 5822): 	at com.couchbase.lite.Database.getDocumentWithIDAndRev(Database.java:1899)
I/REPORT  ( 5822): 	at com.couchbase.lite.Database.getExistingDocument(Database.java:456)
I/REPORT  ( 5822): 	at com.ultimate.maxi.pedidos.virtualmarket.MenuVentasActivity$5.onClick(MenuVentasActivity.java:324)
```

I'm using the latest Android SDK. The document was created by a Server App and replicated to an Android Tablet.

Any idea about this crash? How can I read the document?

**Comment by jalinvi** [comment]
After debugging the app, I get the conclusion that is a RAM issue. On my device there is just 2Mb available when reading the doc, so the getDocument method can not retrieve it.
