### ISSUE TITLE
SSLPeerUnverifiedException talking to API protected by Cloudflare Universal SSL

### ISSUE THREAD

**Issue by sureshjoshi** [couchbase/couchbase-lite-android#638]
Hey all, just ran into the exceptions below. My workaround was to revert to regular HTTP, however, that's not a solution for production. 

Reading up on this, similar errors have popped up for users who are using CloudFlare's SSL (which I am right now). This is possibly due to an SNI issue or the cert chain.

I'm able to access this endpoint via iOS Couchbase, PouchDB, web pages on Mac/Windows/Android/iOS as well as with Retrofit REST calls - so it's not an actual SSL problem, per se. 

Has anyone seen this?

    07-16 01:59:38.506  19165-19235/com.myapp.android E/RemoteRequest﹕ io exception.  url: [MY_URL]
    javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
            at com.android.org.conscrypt.SSLNullSession.getPeerCertificates(SSLNullSession.java:104)
            at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:98)
            at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:393)
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:170)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
            at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:184)
            at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

    07-16 01:59:38.578  19165-19239/com.myapp.android E/RemoteRequest﹕ io exception.  [MY_URL]
    javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
            at com.android.org.conscrypt.SSLNullSession.getPeerCertificates(SSLNullSession.java:104)
            at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:98)
            at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:393)
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:170)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
            at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:184)
            at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by hideki** [comment]
Hi @sureshjoshi,
Some of users bundle certificate into the app. This solution might help you.
https://github.com/couchbase/couchbase-lite-android/issues/116
https://github.com/couchbase/couchbase-lite-java-core/pull/9

**Comment by sureshjoshi** [comment]
Hey @hideki, what certificate am I bundling though? I don't have one because Cloudflare provides free SSL.

**Comment by zgramana** [comment]
Please verify that the Cloudflare root CA is bundled with the version of Android you are experiencing the issue on.

**Comment by borrrden** [comment]
Also note that Cloudfare uses SNI, a relatively new TLS feature, which doesn't seem to be supported on Android versions less than Ice Cream Sandwich (see https://blog.cloudflare.com/introducing-universal-ssl/ under "solution")

**Comment by atentis** [comment]
@sureshjoshi I am having this issue with cloudflare. Did you find a decent resolution?

@borrrden This is an issue with Lollipop as well. Its fixed on my Marshmallow users though.

**Comment by sureshjoshi** [comment]
@atentis Not really, just used an actual SSL cert.
