### ISSUE TITLE
RemoteRequestCompletionBlock throw Exception --  java.lang.NullPointerException

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-android#643]
From @nraboy

```
07-31 15:11:26.888  28431-28558/com.couchbaselabs.maplite E/RemoteRequest﹕ RemoteRequestCompletionBlock throw Exception
java.lang.NullPointerException: Attempt to invoke virtual method 'com.couchbase.lite.internal.RevisionInternal com.couchbase.lite.Database.loadRevisionBody(com.couchbase.lite.internal.RevisionInternal, java.util.EnumSet)' on a null object reference
      at com.couchbase.lite.replicator.PusherInternal$3.onCompletion(PusherInternal.java:414)
      at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:213)
      at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:231)
      at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:300)
      at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:250)
      at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
      at java.lang.Thread.run(Thread.java:818)
```

> Can’t seem to destroy my app without getting errors.  This is the last one

**Comment by tleyden** [comment]
@nraboy can you read the https://github.com/couchbase/couchbase-lite-android/blob/master/CONTRIBUTING.md doc and update the bug accordingly.  The main things to add are:

* Version you are using
* Steps to reproduce

**Comment by zgramana** [comment]
@nraboy ping

**Comment by nraboy** [comment]
@zgramana pong

Here is the code:

```java
package com.couchbaselabs.maplite;

import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.os.Bundle;
import android.os.Handler;
import android.support.v4.app.FragmentActivity;
import android.util.Log;

import com.couchbase.lite.CouchbaseLiteException;
import com.couchbase.lite.Database;
import com.couchbase.lite.Document;
import com.couchbase.lite.LiveQuery;
import com.couchbase.lite.Manager;
import com.couchbase.lite.QueryEnumerator;
import com.couchbase.lite.android.AndroidContext;
import com.couchbase.lite.replicator.Replication;
import com.google.android.gms.common.ConnectionResult;
import com.google.android.gms.common.api.GoogleApiClient;
import com.google.android.gms.location.LocationServices;
import com.google.android.gms.maps.CameraUpdateFactory;
import com.google.android.gms.maps.GoogleMap;
import com.google.android.gms.maps.OnMapReadyCallback;
import com.google.android.gms.maps.SupportMapFragment;
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.Marker;
import com.google.android.gms.maps.model.MarkerOptions;

import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class MapsActivity extends FragmentActivity implements OnMapReadyCallback, LocationListener {

    public GoogleMap googleMap;
    public Marker myMarker;
    public String myDocId;
    public Manager couchbaseManager;
    public Database couchbaseDatabase;
    public ArrayList<String> allDocIds;
    public Replication pull;
    public Replication push;
    public LocationManager mLocationManager;
    public Map<String, Object> markerMap;
    public Handler h;
    public QueryEnumerator originalData;

    static class PersonTracker {
        LatLng location;
        Marker mapMarker;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_maps);
        SupportMapFragment mapFragment = (SupportMapFragment) getSupportFragmentManager()
                .findFragmentById(R.id.map);
        mapFragment.getMapAsync(this);
        googleMap = mapFragment.getMap();
        mLocationManager = (LocationManager) getSystemService(LOCATION_SERVICE);
        mLocationManager.requestLocationUpdates(LocationManager.PASSIVE_PROVIDER, 0, 0, this);

        markerMap = new HashMap<String, Object>();

        allDocIds = new ArrayList<String>();

        h = new Handler();

        try {
            this.couchbaseManager = new Manager(new AndroidContext(this), Manager.DEFAULT_OPTIONS);
            this.couchbaseDatabase = this.couchbaseManager.getDatabase("mydb");
            pull = this.couchbaseDatabase.createPullReplication(new URL("http://10.0.1.11:4984/couchbaseevents"));
            push = this.couchbaseDatabase.createPushReplication(new URL("http://10.0.1.11:4984/couchbaseevents"));
            pull.setContinuous(true);
            push.setContinuous(true);
            pull.start();
            push.start();
            LiveQuery allDocumentsQuery = couchbaseDatabase.createAllDocumentsQuery().toLiveQuery();
            allDocumentsQuery.addChangeListener(
                new LiveQuery.ChangeListener() {
                    @Override /* A notification listener method */
                    public void changed(LiveQuery.ChangeEvent changeEvent) {
                        Log.i("couchbaseevents", "Data changed in the Query…");
                        originalData = changeEvent.getRows();
                        while(originalData.hasNext()) {
                            Document doc = originalData.next().getDocument();
                            if(doc.isDeleted()) {
                                Log.i("couchbase", "The document " + doc.getId() + " was deleted");
                                Marker m = (Marker) markerMap.get(doc.getId());
                                m.remove();
                                markerMap.remove(doc.getId());
                            } else {
                                Marker m;
                                PersonTracker pt = new PersonTracker();
                                if(markerMap.get(doc.getId()) != null) {
                                    Log.i("couchbase", "Deleting document " + doc.getId());

                                    //m = (Marker) markerMap.get(doc.getId());
                                    //m.remove();
                                }
                                Log.i("couchbase", "Creating document " + doc.getId());
                                //pt.location = new LatLng((Double)doc.getProperty("latitude"), (Double)doc.getProperty("longitude"));
                                //markerMap.put(doc.getId(), pt);
                                //m = googleMap.addMarker(new MarkerOptions().position(new LatLng((Double)doc.getProperty("latitude"), (Double)doc.getProperty("longitude"))).title("Someone!"));
                                //markerMap.put(doc.getId(), m);
                                runOnUiThread(new Runnable() {
                                    @Override
                                    public void run() {
                                        googleMap.addMarker(new MarkerOptions().position(new LatLng(0, 0)).title("Someone!"));
                                    }
                                });
                            }
                        }
                            /* work with Query data */
                    }
                }
            );
            allDocumentsQuery.start();
        } catch(Exception e) {
            e.printStackTrace();
        }
    }

    final Runnable updateUI = new Runnable() {
      public void run() {
          PersonTracker pt = (PersonTracker) markerMap.get()

      }
    };

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if(myDocId != null) {
            deleteLatLng(couchbaseDatabase, myDocId);
        }
        if(mLocationManager != null) {
            mLocationManager.removeUpdates(this);
        }
        if(push != null) {
            push.stop();
        }
        if(pull != null) {
            pull.stop();
        }
        if(couchbaseDatabase != null) {
            couchbaseDatabase.close();
        }
        if(couchbaseManager != null) {
            couchbaseManager.close();
        }
    }

    private String saveLatLng(Database database, LatLng loc) {
        Document document = database.createDocument();
        String documentId = document.getId();
        Map<String, Object> map = new HashMap<String, Object>();
        map.put("latitude", loc.latitude);
        map.put("longitude", loc.longitude);
        try {
            // Save the properties to the document
            document.putProperties(map);
        } catch (CouchbaseLiteException e) {
            Log.e("couchbase", "Error putting", e);
        }
        return documentId;
    }

    private void deleteLatLng(Database database, String documentId) {
        try {
            Document retrievedDocument = database.getDocument(documentId);
            retrievedDocument.delete();
            Log.d("couchbase", "Deleted document, deletion status = " + retrievedDocument.isDeleted());
        } catch (CouchbaseLiteException e) {
            Log.e ("couchbase", "Cannot delete document", e);
        }
    }

    private void updateLatLng(Database database, String documentId, LatLng loc) {
        Document document = database.getDocument(documentId);
        try {
            // Update the document with more data
            if(document != null && document.getProperties() != null) {
                Map<String, Object> updatedProperties = new HashMap<String, Object>();
                updatedProperties.putAll(document.getProperties());
                updatedProperties.put("latitude", loc.latitude);
                updatedProperties.put("longitude", loc.longitude);
                // Save to the Couchbase local Couchbase Lite DB
                document.putProperties(updatedProperties);
            }
        } catch (CouchbaseLiteException e) {
            Log.e("couchbase", "Error putting", e);
        }
    }

    @Override
    public void onMapReady(GoogleMap map) {
        Location location = mLocationManager.getLastKnownLocation(LocationManager.GPS_PROVIDER);
        if(myMarker != null) {
            myMarker.remove();
        }
        LatLng myLoc = new LatLng(location.getLatitude(), location.getLongitude());
        myMarker = googleMap.addMarker(new MarkerOptions().position(myLoc).title("Thats Me!"));
        googleMap.moveCamera(CameraUpdateFactory.newLatLng(myLoc));
        googleMap.animateCamera(CameraUpdateFactory.zoomTo(15));
        if(myDocId == null) {
            myDocId = saveLatLng(couchbaseDatabase, myLoc);
        } else {
            updateLatLng(couchbaseDatabase, myDocId, myLoc);
        }
    }

    @Override
    public void onLocationChanged(final Location location) {
        System.out.println("LOCATION CHANGED");
        if(myMarker != null) {
            myMarker.remove();
        }
        LatLng myLoc = new LatLng(location.getLatitude(), location.getLongitude());
        myMarker = googleMap.addMarker(new MarkerOptions().position(myLoc).title("Thats Me!"));
        googleMap.moveCamera(CameraUpdateFactory.newLatLng(myLoc));
        googleMap.animateCamera(CameraUpdateFactory.zoomTo(15));
        if(myDocId == null) {
            myDocId = saveLatLng(couchbaseDatabase, myLoc);
        } else {
            updateLatLng(couchbaseDatabase, myDocId, myLoc);
        }
    }

    @Override
    public void onStatusChanged(String provider, int status, Bundle extras) { }

    @Override
    public void onProviderEnabled(String provider) { }

    @Override
    public void onProviderDisabled(String provider) { }

}
```

I'm using the following:

* Couchbase Lite 1.1.0
* ADK 22

The code I pasted is incredibly experimental, but what is happening is when I run the application and close it, it always throws that exception.  I figured maybe I needed to stop the replicators and close the database, but that didn't resolve it.

Let me know if you need further information.

Thanks,

**Comment by hideki** [comment]
@nraboy Can you share entire project? It is much easier to debug. Thanks!

**Comment by hideki** [comment]
This part of codes were re-written since v1.2.0. I believe this issue no longer occurs. I will close the ticket.
