### ISSUE TITLE
Fatal signal 11 on liteserv when run sg func tests with large revisions

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/couchbase-lite-android#675]
test from https://github.com/couchbaselabs/sync-gateway-tests/blob/master/tests/cbl-large-revisions-compact-revs-limit.js

test stuck and in logcat I see
```
W/Sync    (12707): com.couchbase.lite.replicator.PusherInternal@b1d3dfd8: removePending: sequence 3744 not in set, for rev {large-revisions-revslimit_3 #364-01b28e7b82366712b28b233544618a4dDEL}
W/Sync    (12707): com.couchbase.lite.replicator.PusherInternal@b1d3dfd8: removePending: sequence 3745 not in set, for rev {large-revisions-revslimit_4 #364-71300c807d85113f17c6dfbc3a5f2542DEL}
I/Batcher (12707): Exception from Future.get()
D/dalvikvm(12707): GC_CONCURRENT freed 531K, 53% free 4132K/8640K, paused 26ms+10ms, total 188ms
D/dalvikvm(12707): WAIT_FOR_CONCURRENT_GC blocked 81ms
D/dalvikvm(12707): WAIT_FOR_CONCURRENT_GC blocked 69ms
W/Listener(12707): authHeader is null
W/Listener(12707): authHeader is null
D/dalvikvm(12707): GC_CONCURRENT freed 481K, 52% free 4163K/8640K, paused 7ms+8ms, total 128ms
D/dalvikvm(12707): WAIT_FOR_CONCURRENT_GC blocked 67ms
D/dalvikvm(12707): WAIT_FOR_CONCURRENT_GC blocked 79ms
W/Listener(12707): authHeader is null
W/Sync    (12707): com.couchbase.lite.replicator.PullerInternal@b1e180e8 no new remote revisions to fetch.  add lastInboxSequence (5246) to pendingSequences (com.couchbase.lite.support.SequenceMap@b1f12da8)
D/dalvikvm(12707): GC_CONCURRENT freed 428K, 51% free 4247K/8640K, paused 8ms+9ms, total 145ms
D/dalvikvm(12707): WAIT_FOR_CONCURRENT_GC blocked 64ms
D/dalvikvm(12707): WAIT_FOR_CONCURRENT_GC blocked 55ms
D/dalvikvm(12707): WAIT_FOR_CONCURRENT_GC blocked 40ms
W/Listener(12707): authHeader is null
W/Listener(12707): authHeader is null
D/dalvikvm(12707): GC_CONCURRENT freed 525K, 51% free 4233K/8640K, paused 6ms+8ms, total 135ms
D/dalvikvm(12707): WAIT_FOR_CONCURRENT_GC blocked 109ms
D/dalvikvm(12707): WAIT_FOR_CONCURRENT_GC blocked 92ms
D/dalvikvm(12707): WAIT_FOR_CONCURRENT_GC blocked 51ms
D/dalvikvm(12707): WAIT_FOR_CONCURRENT_GC blocked 105ms
F/libc    (12707): Fatal signal 11 (SIGSEGV) at 0x00000030 (code=1), thread 12729 (CBLRequestWorke)
F/libc    (12707): Fatal signal 11 (SIGSEGV) at 0x0000003b (code=1), thread 15046 (0.0.2.2:9888/db)
W/Listener(12707): authHeader is null
I/DEBUG   (12537): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (12537): Build fingerprint: 'generic/sdk/generic:4.4.4/KK/1743154:eng/test-keys'
I/DEBUG   (12537): Revision: '0'
I/DEBUG   (12537): pid: 12707, tid: 12729, name: CBLRequestWorke  >>> com.couchbase.liteservandroid <<<
I/DEBUG   (12537): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000030
I/DEBUG   (12537):     r0 a0dc6220  r1 aefc6b62  r2 00000007  r3 00000000
I/DEBUG   (12537):     r4 aefc6b62  r5 a79d8acc  r6 b8ef4478  r7 0000caf4
I/DEBUG   (12537):     r8 b5a45d40  r9 00000001  sl a79d8ab8  fp 0000001e
I/DEBUG   (12537):     ip 0000002e  sp a79d4c40  lr 00000000  pc a7ffb3b0  cpsr 00000030
I/DEBUG   (12537):     d0  3f4000003f400000  d1  401c000000000000
I/DEBUG   (12537):     d2  3ff0000000000000  d3  0000000100000000
I/DEBUG   (12537):     d4  3ff0000000000000  d5  4018000000000000
I/DEBUG   (12537):     d6  0000000000000000  d7  3ff0000000000000
I/DEBUG   (12537):     d8  3f4000003f400000  d9  0000000000000000
I/DEBUG   (12537):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   (12537):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   (12537):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   (12537):     scr 60000010
I/DEBUG   (12537): 
I/DEBUG   (12537): backtrace:
I/DEBUG   (12537):     #00  pc 0000c3b0  /dev/ashmem/dalvik-jit-code-cache (deleted)
I/DEBUG   (12537): 
I/DEBUG   (12537): stack:
I/DEBUG   (12537):          a79d4c00  b213e528  /dev/ashmem/dalvik-heap (deleted)
I/DEBUG   (12537):          a79d4c04  b5ad71f0  /system/lib/libdvm.so
I/DEBUG   (12537):          a79d4c08  0000000c  
I/DEBUG   (12537):          a79d4c0c  b5a51dc0  /system/lib/libdvm.so (dvmMalloc(unsigned int, int)+68)
I/DEBUG   (12537):          a79d4c10  b6f0dfd8  /system/lib/libc.so
I/DEBUG   (12537):          a79d4c14  b6f0e06c  /system/lib/libc.so
I/DEBUG   (12537):          a79d4c18  b5ad76c8  /system/lib/libdvm.so
I/DEBUG   (12537):          a79d4c1c  39f835c9  
I/DEBUG   (12537):          a79d4c20  00005601  
I/DEBUG   (12537):          a79d4c24  aefc6b62  /system/framework/core.odex
I/DEBUG   (12537):          a79d4c28  a79d8acc  
I/DEBUG   (12537):          a79d4c2c  b8ef4478  [heap]
I/DEBUG   (12537):          a79d4c30  0000caf4  
I/DEBUG   (12537):          a79d4c34  b5a45d40  /system/lib/libdvm.so
I/DEBUG   (12537):          a79d4c38  00000001  
I/DEBUG   (12537):          a79d4c3c  b5a4ede0  /system/lib/libdvm.so
I/DEBUG   (12537):     #00  a79d4c40  00000000  
I/DEBUG   (12537):          a79d4c44  b8ef4478  [heap]
I/DEBUG   (12537):          a79d4c48  b5a55ee8  /system/lib/libdvm.so (dvmMterpStd(Thread*))
I/DEBUG   (12537):          a79d4c4c  00000000  
I/DEBUG   (12537):          a79d4c50  a79d4d78  [stack:12729]
I/DEBUG   (12537):          a79d4c54  b8ef4478  [heap]
I/DEBUG   (12537):          a79d4c58  a79d4c94  [stack:12729]
I/DEBUG   (12537):          a79d4c5c  af24feb0  /dev/ashmem/dalvik-LinearAlloc (deleted)
I/DEBUG   (12537):          a79d4c60  b1dd4968  /dev/ashmem/dalvik-heap (deleted)
I/DEBUG   (12537):          a79d4c64  b5a55f38  /system/lib/libdvm.so (dvmMterpStd(Thread*)+80)
I/DEBUG   (12537):          a79d4c68  00000000  
I/DEBUG   (12537):          a79d4c6c  00000000  
I/DEBUG   (12537):          a79d4c70  00000000  
I/DEBUG   (12537):          a79d4c74  00000000  
I/DEBUG   (12537):          a79d4c78  00000000  
I/DEBUG   (12537):          a79d4c7c  fffffea0  
I/DEBUG   (12537): 
I/DEBUG   (12537): memory near r0:
I/DEBUG   (12537):     a0dc6200 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     a0dc6210 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     a0dc6220 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     a0dc6230 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     a0dc6240 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     a0dc6250 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     a0dc6260 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     a0dc6270 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     a0dc6280 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     a0dc6290 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     a0dc62a0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     a0dc62b0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     a0dc62c0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     a0dc62d0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     a0dc62e0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     a0dc62f0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537): 
I/DEBUG   (12537): memory near r1:
I/DEBUG   (12537):     aefc6b40 c3f2f628 d5f20010 caf20010 cbf20010  
I/DEBUG   (12537):     aefc6b50 02900014 d7f40b0a 56010008 24353401  
I/DEBUG   (12537):     aefc6b60 caf4ffe7 03d80008 00490104 05d8040a  
I/DEBUG   (12537):     aefc6b70 01490106 10320607 2070000e 000c0bb1  
I/DEBUG   (12537):     aefc6b80 20700a0a 001c0bb1 ba320b0a 98010004  
I/DEBUG   (12537):     aefc6b90 5601ce28 e4283401 0005000a 00010004  
I/DEBUG   (12537):     aefc6ba0 00236399 0000002e 0028063a 00267636  
I/DEBUG   (12537):     aefc6bb0 001453f2 00223736 001053f2 53f237b0  
I/DEBUG   (12537):     aefc6bc0 00900010 92010603 001d7035 010209d8  
I/DEBUG   (12537):     aefc6bd0 000853f4 00030349 034f338d 00d80208  
I/DEBUG   (12537):     aefc6be0 92010100 010df228 04918321 40700607  
I/DEBUG   (12537):     aefc6bf0 49350baf 0327030c 0bd33070 030c0765  
I/DEBUG   (12537):     aefc6c00 000e0327 0000000b 00010010 01df0101  
I/DEBUG   (12537):     aefc6c10 0000001f 00010002 00000002 002363e0  
I/DEBUG   (12537):     aefc6c20 00000009 18e10071 000c0000 001c20f8  
I/DEBUG   (12537):     aefc6c30 000c0001 00000011 00020003 00000002  
I/DEBUG   (12537): 
I/DEBUG   (12537): memory near r4:
I/DEBUG   (12537):     aefc6b40 c3f2f628 d5f20010 caf20010 cbf20010  
I/DEBUG   (12537):     aefc6b50 02900014 d7f40b0a 56010008 24353401  
I/DEBUG   (12537):     aefc6b60 caf4ffe7 03d80008 00490104 05d8040a  
I/DEBUG   (12537):     aefc6b70 01490106 10320607 2070000e 000c0bb1  
I/DEBUG   (12537):     aefc6b80 20700a0a 001c0bb1 ba320b0a 98010004  
I/DEBUG   (12537):     aefc6b90 5601ce28 e4283401 0005000a 00010004  
I/DEBUG   (12537):     aefc6ba0 00236399 0000002e 0028063a 00267636  
I/DEBUG   (12537):     aefc6bb0 001453f2 00223736 001053f2 53f237b0  
I/DEBUG   (12537):     aefc6bc0 00900010 92010603 001d7035 010209d8  
I/DEBUG   (12537):     aefc6bd0 000853f4 00030349 034f338d 00d80208  
I/DEBUG   (12537):     aefc6be0 92010100 010df228 04918321 40700607  
I/DEBUG   (12537):     aefc6bf0 49350baf 0327030c 0bd33070 030c0765  
I/DEBUG   (12537):     aefc6c00 000e0327 0000000b 00010010 01df0101  
I/DEBUG   (12537):     aefc6c10 0000001f 00010002 00000002 002363e0  
I/DEBUG   (12537):     aefc6c20 00000009 18e10071 000c0000 001c20f8  
I/DEBUG   (12537):     aefc6c30 000c0001 00000011 00020003 00000002  
I/DEBUG   (12537): 
I/DEBUG   (12537): memory near r5:
I/DEBUG   (12537):     a79d8aac b1de74c8 00000000 00000004 a79d8b18  
I/DEBUG   (12537):     a79d8abc aec372ae af24e7e0 aefc6b62 00000000  
I/DEBUG   (12537):     a79d8acc 00000074 00000074 0000000e 00000007  
I/DEBUG   (12537):     a79d8adc 00000007 00000007 00000007 b1c75ba8  
I/DEBUG   (12537):     a79d8aec 00000001 00000000 b2287ad8 0000000e  
I/DEBUG   (12537):     a79d8afc b1def628 b1c75b88 a79d8b40 aec1cbac  
I/DEBUG   (12537):     a79d8b0c af58e640 aec372ae 00000000 b1ec6240  
I/DEBUG   (12537):     a79d8b1c 00000000 b1def628 b2141888 b1c75b88  
I/DEBUG   (12537):     a79d8b2c a79d8b60 aec32384 af43e4c0 aec1cbac  
I/DEBUG   (12537):     a79d8b3c 00000000 b2141888 b1d343a0 b1c75b88  
I/DEBUG   (12537):     a79d8b4c a79d8bc4 aec3218c af58a050 aec32384  
I/DEBUG   (12537):     a79d8b5c 00000000 b1d343a0 a79d8b94 aefe3152  
I/DEBUG   (12537):     a79d8b6c af28ee70 aefc8338 00000000 a79d8ba4  
I/DEBUG   (12537):     a79d8b7c aec222cc af439680 aefb6eb0 00000000  
I/DEBUG   (12537):     a79d8b8c b213e528 a79d8bc4 00000000 00000000  
I/DEBUG   (12537):     a79d8b9c b1c75b88 00000000 ffffffff b1db4ee0  
I/DEBUG   (12537): 
I/DEBUG   (12537): memory near r6:
I/DEBUG   (12537):     b8ef4458 af561318 00000028 00000000 00000000  
I/DEBUG   (12537):     b8ef4468 00000001 a63e5000 00000020 0000045b  
I/DEBUG   (12537):     b8ef4478 aefc6b92 a79d8acc af24e7e0 aeeea000  
I/DEBUG   (12537):     b8ef4488 b1def628 54b494ec a79d4c40 00000000  
I/DEBUG   (12537):     b8ef4498 a79d4c94 00000014 00020010 b5a4ac00  
I/DEBUG   (12537):     b8ef44a8 00000001 00000000 aec1bb70 a79d5300  
I/DEBUG   (12537):     b8ef44b8 00000000 00000000 00000001 00004000  
I/DEBUG   (12537):     b8ef44c8 00000000 b8ef48d0 b5a45d40 b5a4ac00  
I/DEBUG   (12537):     b8ef44d8 00000000 b5a4ecfc b5a4ed70 b5a4ec20  
I/DEBUG   (12537):     b8ef44e8 b5a4ec40 b5a4ec9c 00000000 a7ffb369  
I/DEBUG   (12537):     b8ef44f8 b8e92190 00000028 00000000 a79d4c40  
I/DEBUG   (12537):     b8ef4508 aec29cc8 00000006 00002000 b5ad791c  
I/DEBUG   (12537):     b8ef4518 b1a37420 af281748 00000000 b8ef4d20  
I/DEBUG   (12537):     b8ef4528 00000001 00000040 00000200 00000000  
I/DEBUG   (12537):     b8ef4538 00000001 aefe30fe aefe30fe 00000002  
I/DEBUG   (12537):     b8ef4548 aefe313e af35d468 3990b943 751a1889  
I/DEBUG   (12537): 
I/DEBUG   (12537): memory near r7:
I/DEBUG   (12537):     0000cad4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     0000cae4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     0000caf4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     0000cb04 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     0000cb14 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     0000cb24 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     0000cb34 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     0000cb44 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     0000cb54 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     0000cb64 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     0000cb74 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     0000cb84 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     0000cb94 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     0000cba4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     0000cbb4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     0000cbc4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537): 
I/DEBUG   (12537): memory near r8:
I/DEBUG   (12537):     b5a45d20 e320f000 e320f000 e320f000 e320f000  
I/DEBUG   (12537):     b5a45d30 e320f000 e320f000 e320f000 e320f000  
I/DEBUG   (12537):     b5a45d40 e1f470b2 e207c0ff e088f30c e92d4ff0  
I/DEBUG   (12537):     b5a45d50 e24dd004 e320f000 e320f000 e320f000  
I/DEBUG   (12537):     b5a45d60 e320f000 e320f000 e320f000 e320f000  
I/DEBUG   (12537):     b5a45d70 e320f000 e320f000 e320f000 e320f000  
I/DEBUG   (12537):     b5a45d80 e1a01627 e7e30457 e1f470b2 e7952101  
I/DEBUG   (12537):     b5a45d90 e207c0ff e7852100 e088f30c e320f000  
I/DEBUG   (12537):     b5a45da0 e320f000 e320f000 e320f000 e320f000  
I/DEBUG   (12537):     b5a45db0 e320f000 e320f000 e320f000 e320f000  
I/DEBUG   (12537):     b5a45dc0 e1d410b2 e1a00427 e1f470b4 e7952101  
I/DEBUG   (12537):     b5a45dd0 e207c0ff e7852100 e088f30c e320f000  
I/DEBUG   (12537):     b5a45de0 e320f000 e320f000 e320f000 e320f000  
I/DEBUG   (12537):     b5a45df0 e320f000 e320f000 e320f000 e320f000  
I/DEBUG   (12537):     b5a45e00 e1d410b4 e1d400b2 e1f470b6 e7952101  
I/DEBUG   (12537):     b5a45e10 e207c0ff e7852100 e088f30c e320f000  
I/DEBUG   (12537): 
I/DEBUG   (12537): memory near sl:
I/DEBUG   (12537):     a79d8a98 af256b70 00000000 00000000 b1f02568  
I/DEBUG   (12537):     a79d8aa8 00000000 b1de74c8 00000000 00000004  
I/DEBUG   (12537):     a79d8ab8 a79d8b18 aec372ae af24e7e0 aefc6b62  
I/DEBUG   (12537):     a79d8ac8 00000000 00000074 00000074 0000000e  
I/DEBUG   (12537):     a79d8ad8 00000007 00000007 00000007 00000007  
I/DEBUG   (12537):     a79d8ae8 b1c75ba8 00000001 00000000 b2287ad8  
I/DEBUG   (12537):     a79d8af8 0000000e b1def628 b1c75b88 a79d8b40  
I/DEBUG   (12537):     a79d8b08 aec1cbac af58e640 aec372ae 00000000  
I/DEBUG   (12537):     a79d8b18 b1ec6240 00000000 b1def628 b2141888  
I/DEBUG   (12537):     a79d8b28 b1c75b88 a79d8b60 aec32384 af43e4c0  
I/DEBUG   (12537):     a79d8b38 aec1cbac 00000000 b2141888 b1d343a0  
I/DEBUG   (12537):     a79d8b48 b1c75b88 a79d8bc4 aec3218c af58a050  
I/DEBUG   (12537):     a79d8b58 aec32384 00000000 b1d343a0 a79d8b94  
I/DEBUG   (12537):     a79d8b68 aefe3152 af28ee70 aefc8338 00000000  
I/DEBUG   (12537):     a79d8b78 a79d8ba4 aec222cc af439680 aefb6eb0  
I/DEBUG   (12537):     a79d8b88 00000000 b213e528 a79d8bc4 00000000  
I/DEBUG   (12537): 
I/DEBUG   (12537): memory near sp:
I/DEBUG   (12537):     a79d4c20 00005601 aefc6b62 a79d8acc b8ef4478  
I/DEBUG   (12537):     a79d4c30 0000caf4 b5a45d40 00000001 b5a4ede0  
I/DEBUG   (12537):     a79d4c40 00000000 b8ef4478 b5a55ee8 00000000  
I/DEBUG   (12537):     a79d4c50 a79d4d78 b8ef4478 a79d4c94 af24feb0  
I/DEBUG   (12537):     a79d4c60 b1dd4968 b5a55f38 00000000 00000000  
I/DEBUG   (12537):     a79d4c70 00000000 00000000 00000000 fffffea0  
I/DEBUG   (12537):     a79d4c80 b5a55ee8 b5a535d0 00000000 00000000  
I/DEBUG   (12537):     a79d4c90 00000000 00000000 a79d8fe4 00000000  
I/DEBUG   (12537):     a79d4ca0 00000000 00000000 00000000 00000000  
I/DEBUG   (12537):     a79d4cb0 00000000 00000000 00000000 00000000  
I/DEBUG   (12537):     a79d4cc0 00000000 00000000 00000000 00000000  
I/DEBUG   (12537):     a79d4cd0 00000000 00000000 00000000 00000000  
I/DEBUG   (12537):     a79d4ce0 00000000 00000000 00000000 00000000  
I/DEBUG   (12537):     a79d4cf0 00000000 00000000 a79d4d78 00000000  
I/DEBUG   (12537):     a79d4d00 b8ef4478 a79d8fec af24feb0 af1192e0  
I/DEBUG   (12537):     a79d4d10 00000000 b5a88319 0000001d 0000001c  
I/DEBUG   (12537): 
I/DEBUG   (12537): code around pc:
I/DEBUG   (12537):     a7ffb390 0a01f209 0f00f1bb a014f8c5 8000f8c5  
I/DEBUG   (12537):     a7ffb3a0 f8dbd014 f20b4008 45a10c10 800ef080  
I/DEBUG   (12537):     a7ffb3b0 7019f83c 606f45b8 8012f000 de00e00a  
I/DEBUG   (12537):     a7ffb3c0 0048f8df f8dfe004 e0010040 0034f8df  
I/DEBUG   (12537):     a7ffb3d0 47886ef1 4300e000 47806e70 aefc6b7a  
I/DEBUG   (12537):     a7ffb3e0 4300e000 47806e70 aefc6b92 00000002  
I/DEBUG   (12537):     a7ffb3f0 b8e80000 af24e7e0 001f0106 00000001  
I/DEBUG   (12537):     a7ffb400 00000000 aefc6b72 aefc6b6a aefc6b62  
I/DEBUG   (12537):     a7ffb410 b8e92f4c f85f0034 68010008 60013101  
I/DEBUG   (12537):     a7ffb420 207a68e9 61a84281 8008f340 1c2de000  
I/DEBUG   (12537):     a7ffb430 4300e000 47806e70 af0152c8 fd6ef7f7  
I/DEBUG   (12537):     a7ffb440 47806e70 af0152d8 00000002 b8e80000  
I/DEBUG   (12537):     a7ffb450 af3e1d10 002e0102 00000001 00000000  
I/DEBUG   (12537):     a7ffb460 b8e92f50 f85f0044 68010008 60013101  
I/DEBUG   (12537):     a7ffb470 005cf8df 680168ea b1716029 f201688c  
I/DEBUG   (12537):     a7ffb480 42a20310 8009f080 1022f853 61371c0f  
I/DEBUG   (12537): 
I/DEBUG   (12537): code around lr:
I/DEBUG   (12537):     00000000 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     00000010 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     00000020 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     00000030 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     00000040 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     00000050 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     00000060 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     00000070 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     00000080 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     00000090 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     000000a0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     000000b0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     000000c0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     000000d0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     000000e0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (12537):     000000f0 ffffffff ffffffff ffffffff ffffffff  
D/AndroidRuntime(20729): 
D/AndroidRuntime(20729): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime(20729): CheckJNI is ON
D/dalvikvm(20729): Trying to load lib libjavacore.so 0x0
D/dalvikvm(20729): Added shared lib libjavacore.so 0x0
D/dalvikvm(20729): Trying to load lib libnativehelper.so 0x0
D/dalvikvm(20729): Added shared lib libnativehelper.so 0x0
D/dalvikvm(20729): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
D/AndroidRuntime(20733): 
D/AndroidRuntime(20733): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime(20733): CheckJNI is ON
D/dalvikvm(20733): Trying to load lib libjavacore.so 0x0
D/dalvikvm(20733): Added shared lib libjavacore.so 0x0
D/dalvikvm(20733): Trying to load lib libnativehelper.so 0x0
D/dalvikvm(20733): Added shared lib libnativehelper.so 0x0
D/dalvikvm(20733): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
D/dalvikvm(20729): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
E/NativeCrashListener(  350): Exception dealing with report
E/NativeCrashListener(  350): libcore.io.ErrnoException: read failed: EAGAIN (Try again)
E/NativeCrashListener(  350): 	at libcore.io.Posix.readBytes(Native Method)
E/NativeCrashListener(  350): 	at libcore.io.Posix.read(Posix.java:128)
E/NativeCrashListener(  350): 	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:149)
E/NativeCrashListener(  350): 	at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
E/NativeCrashListener(  350): 	at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)
D/dalvikvm(20733): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
E/memtrack(20729): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug(20729): failed to load memtrack module: -2
I/BootReceiver(  350): Copying /data/tombstones/tombstone_08 to DropBox (SYSTEM_TOMBSTONE)
D/dalvikvm(12707): JIT unchain all for threadid=27
E/memtrack(20733): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug(20733): failed to load memtrack module: -2
I/DEBUG   (12537): unexpected waitpid response: n=15046, status=0000000b
I/DEBUG   (12537): ptrace detach from 15046 failed: No such process
I/DEBUG   (12537): debuggerd committing suicide to free the zombie!
I/DEBUG   (20748): debuggerd: Feb 19 2015 02:21:57
I/ActivityManager(  350): Process com.couchbase.liteservandroid (pid 12707) has died.
```

Please tell me how to provide more useful information for such issues for android/java

**Comment by hideki** [comment]
Hi @andreibaranouski,
Did you use emulator? Can you write emulator configuration? And also what is document size?
Thanks,
Hideki

**Comment by andreibaranouski** [comment]
![image](https://cloud.githubusercontent.com/assets/1714151/10185761/469c5b7e-6754-11e5-83fc-f5b72e2d5927.png)

doc example:

curl http://localhost:9889/db/large-revisions-compact_0
{"_id":"large-revisions-compact_0","_rev":"121-8d4f8909f408946a2dd787d7c5b42e5a","at":"2015-09-30T06:20:28.187Z","data":"20141411332240002210000121241223014420243343230124142110040111404112013101424240002304342242022104312014411423230431334224313340133420030124344111032200111300322030342022024132042422411001230412230204324034113443402143203130320132310343130332230411341131340204401300430404124203424033242441032001143033224143042001131121022112000104123120412101044013434000013031444314410444214012140132440432334122403434303012042401204042132340331433340032401001221320104304120240002431131414341130400204224244023300341340022024132103031233203134042143324423431201410302012103422031302400230402332340042234233122010424222220114014033401000320140333410021030044102034422223132012341022040122044111013121312011314420031112223440220404423320421020422203104014221422323113002332230020002342420121123213112440324242004412032322232444143314303130204140333042304010320210210333432032112413410132411122223043002220243333012311004321223230341210344424211321144134134010424110143324411324202430211242403430112311212211442331444201032313403223034310212411140034233032232430240131242004120301320313000211430320304243203211334"}

**Comment by hideki** [comment]
Is it possible to run SG functional test on my mac?

**Comment by hideki** [comment]
Revision size is not too large.  
Can I run SG functional test on my Mac?

**Comment by zgramana** [comment]
@andreibaranouski has this reoccurred since then?

**Comment by hideki** [comment]
We should check cache of Database. In case Document has many revisions, it might cause memory leak.

**Comment by hideki** [comment]
Currently we don't observe SIGSEGV for a while. http://uberjenkins.sc.couchbase.com:8080/job/mac-sync-gateway-android-node-js-tests-cb/10/consoleFull
I will close this. But need to keep eye open to this issue.

**Comment by hideki** [comment]
could be duplicated with https://github.com/couchbase/couchbase-lite-android/issues/651
