### ISSUE TITLE
Can't find SQLiteConnection.mConnectionPtr

### ISSUE THREAD

**Issue by vkumar568** [couchbase/couchbase-lite-android#704]
Hi i am using eclipse for developing android application. and using the code in android lollypop 5.0 is not working for me. i have been already use this jar file couchbase-lite-android-0.0.0-463-sources.jar, but not working. please provide me some solution. It seems like.

Process: com.innotion.protean, PID: 12678
java.lang.NoSuchFieldError: no "I" field "mConnectionPtr" in class "Landroid/database/sqlite/SQLiteConnection;" or its superclasses
at com.couchbase.touchdb.TDCollateJSON.nativeRegisterCustomCollators(Native Method)
at com.couchbase.touchdb.TDCollateJSON.registerCustomCollators(TDCollateJSON.java:11)
at com.couchbase.lite.android.AndroidSQLiteStorageEngine.open(AndroidSQLiteStorageEngine.java:46)
at com.couchbase.lite.Database.open(Database.java:911)
at com.couchbase.lite.Manager.getDatabase(Manager.java:227)

**Comment by hideki** [comment]
Hi @vkumar568,
For Eclipse, could you please download SDK from http://www.couchbase.com/nosql-databases/downloads?  Select `Couchbase Mobile`,  `Couchbase LIte`, then `Android`. Version number should be 1.1.0.
Thanks!

**Comment by vkumar568** [comment]
Hi @hideki ,
This is not working. after this process there are some problems come. its like:

1. The method updateActive() is undefined for the type Replication
 2. The import org.codehaus cannot be resolved

**Comment by hideki** [comment]
Hi @vkumar568,

>The method updateActive() is undefined for the type Replication

Could you please use all jar or aar files that have XXX-1.1.0.jar/aar files.

> The import org.codehaus cannot be resolved

I guess Jackson, which is CBL depends, is in app's class path.

**Comment by vkumar568** [comment]
Hi @hideki ,

1. The method updateActive() is undefined for the type Replication
      
     Yes i was use all xxx-1.1.0 jar files.

**Comment by hideki** [comment]
HI @vkumar568,
Could you please paste stacktrace? Which method does call `updateActive()`?

**Comment by vkumar568** [comment]
Hi @hideki ,

i am using this method for check the replication status.
#notifyReplicationStatusChange(com.couchbase.lite.replicator.Replication.ReplicationStatus)

public void notifyReplicationStatusChange(Replication replication,
			long lastSeqNumber) {

		replication.updateActive();
		mCurrentReplicationStatus = replication.getStatus();
		boolean done = false;

		if (replication.isRunning() || started) {
			started = true;
		}
		final boolean statusIsDone = (replication.getStatus() == Replication.ReplicationStatus.REPLICATION_STOPPED || replication
				.getStatus() == Replication.ReplicationStatus.REPLICATION_IDLE);
		if (started && statusIsDone) {
			done = true;
			Log.i(TAG, "Replication has been completed.");
		}

		if (replication.getStatus() == ReplicationStatus.REPLICATION_STOPPED) {
			Log.i(TAG, "Replication Stopped");
		} else if (replication.getStatus() == ReplicationStatus.REPLICATION_ACTIVE) {
			Log.i(TAG, "Replication Active");
		} else if (replication.getStatus() == ReplicationStatus.REPLICATION_IDLE) {
			Log.i(TAG, "Replication Idle");
		} else if (replication.getStatus() == ReplicationStatus.REPLICATION_OFFLINE) {
			Log.i(TAG, "Replication Offline");
		}
	}

**Comment by hideki** [comment]
Hi @vkumar568,

`Replication.updateActive()` is not supported by v1.1.0.
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.1.0/src/main/java/com/couchbase/lite/replicator/Replication.java

And also `Replication.updateActive()` is not official API.
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/couchbase-lite/replication/replication/index.html

I understand your codes could work with CBL v1.0.x. However, CBL v1.1.0 no longer provides `Replication.updateActive()`. Could you please update your codes? I think you don't need to call `Replication.updateActive()` in `Replication Change Event`.

Thanks!
Hideki

**Comment by vkumar568** [comment]
HI @hideki ,

i have been upgrade the couchbase lite latest version like 1.1.0
but my previous problem is not solve. i have been already added couchbase-lite-android-0.0.0-463-sources.jar 
 please give me the some solution.

**Comment by vkumar568** [comment]
Hi @hideki ,

Any progress of this issue. please provide me some solution for urgent basis.

Thanks,
Vinay

**Comment by hideki** [comment]
Hi @vkumar568,
We fixed some issue with custom collators with v1.2.0.
Could you please try 1.2.0?
Thanks!
Hideki

**Comment by zgramana** [comment]
@vkumar568 closing due to inactivity. Please refile if it still exists with 1.2.0.
