### ISSUE TITLE
testOneShotPullReplBulkGet failed on jenkins: Expected: <null> but was: org.apache.http.client.HttpResponseException: NOT ACCEPTABLE

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/couchbase-lite-android#745]
http://mobile.jenkins.couchbase.com/view/Couchbase_Lite/job/couchbase-lite-android-build/517/console
http://mobile.jenkins.couchbase.com/view/Couchbase_Lite/job/couchbase-lite-android-build/517/artifact/logcat.txt

```
01-10 12:09:01.651 I/TestRunner( 1058): failed: testOneShotPullReplBulkGet(com.couchbase.lite.replicator.ReplicationInternalTest)
01-10 12:09:01.651 I/TestRunner( 1058): ----- begin exception -----
01-10 12:09:01.661 I/TestRunner( 1058): 
01-10 12:09:01.661 I/TestRunner( 1058): junit.framework.AssertionFailedError: Expected: <null> but was: org.apache.http.client.HttpResponseException: NOT ACCEPTABLE
01-10 12:09:01.661 I/TestRunner( 1058): 	at junit.framework.Assert.fail(Assert.java:50)
01-10 12:09:01.661 I/TestRunner( 1058): 	at junit.framework.Assert.assertTrue(Assert.java:20)
01-10 12:09:01.661 I/TestRunner( 1058): 	at junit.framework.Assert.assertNull(Assert.java:237)
01-10 12:09:01.661 I/TestRunner( 1058): 	at junit.framework.Assert.assertNull(Assert.java:230)
01-10 12:09:01.661 I/TestRunner( 1058): 	at com.couchbase.lite.replicator.ReplicationInternalTest.testOneShotPullReplBulkGet(ReplicationInternalTest.java:104)
01-10 12:09:01.661 I/TestRunner( 1058): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-10 12:09:01.661 I/TestRunner( 1058): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-10 12:09:01.661 I/TestRunner( 1058): 	at junit.framework.TestCase.runTest(TestCase.java:168)
01-10 12:09:01.661 I/TestRunner( 1058): 	at junit.framework.TestCase.runBare(TestCase.java:134)
01-10 12:09:01.661 I/TestRunner( 1058): 	at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
01-10 12:09:01.661 I/TestRunner( 1058): 	at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:88)
01-10 12:09:01.661 I/TestRunner( 1058): 	at junit.framework.TestResult$1.protect(TestResult.java:115)
01-10 12:09:01.661 I/TestRunner( 1058): 	at junit.framework.TestResult.runProtected(TestResult.java:133)
01-10 12:09:01.661 I/TestRunner( 1058): 	at junit.framework.TestResult.run(TestResult.java:118)
01-10 12:09:01.661 I/TestRunner( 1058): 	at junit.framework.TestCase.run(TestCase.java:124)
01-10 12:09:01.661 I/TestRunner( 1058): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
01-10 12:09:01.661 I/TestRunner( 1058): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
01-10 12:09:01.661 I/TestRunner( 1058): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
01-10 12:09:01.661 I/TestRunner( 1058): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

**Comment by hideki** [comment]
I did not see this issue for a while. Recent our fix might fix this issue too.
