### ISSUE TITLE
testInvokeProcessorAfterReachingCapacity failed on jenkins

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/couchbase-lite-android#746]
http://mobile.jenkins.couchbase.com/view/Couchbase_Lite/job/couchbase-lite-android-build/518/artifact/logcat.txt
```
01-10 13:18:18.574 I/TestRunner( 1088): failed: testInvokeProcessorAfterReachingCapacity(com.couchbase.lite.support.BatcherTest)
01-10 13:18:18.574 I/TestRunner( 1088): ----- begin exception -----
01-10 13:18:18.584 I/TestRunner( 1088): 
01-10 13:18:18.584 I/TestRunner( 1088): junit.framework.AssertionFailedError
01-10 13:18:18.584 I/TestRunner( 1088): 	at junit.framework.Assert.fail(Assert.java:48)
01-10 13:18:18.584 I/TestRunner( 1088): 	at junit.framework.Assert.assertTrue(Assert.java:20)
01-10 13:18:18.584 I/TestRunner( 1088): 	at junit.framework.Assert.assertTrue(Assert.java:27)
01-10 13:18:18.584 I/TestRunner( 1088): 	at com.couchbase.lite.support.BatcherTest.testInvokeProcessorAfterReachingCapacity(BatcherTest.java:402)
01-10 13:18:18.584 I/TestRunner( 1088): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-10 13:18:18.584 I/TestRunner( 1088): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-10 13:18:18.584 I/TestRunner( 1088): 	at junit.framework.TestCase.runTest(TestCase.java:168)
01-10 13:18:18.584 I/TestRunner( 1088): 	at junit.framework.TestCase.runBare(TestCase.java:134)
01-10 13:18:18.584 I/TestRunner( 1088): 	at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
01-10 13:18:18.584 I/TestRunner( 1088): 	at junit.framework.TestResult$1.protect(TestResult.java:115)
01-10 13:18:18.584 I/TestRunner( 1088): 	at junit.framework.TestResult.runProtected(TestResult.java:133)
01-10 13:18:18.584 I/TestRunner( 1088): 	at junit.framework.TestResult.run(TestResult.java:118)
01-10 13:18:18.584 I/TestRunner( 1088): 	at junit.framework.TestCase.run(TestCase.java:124)
01-10 13:18:18.584 I/TestRunner( 1088): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
01-10 13:18:18.584 I/TestRunner( 1088): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
01-10 13:18:18.584 I/TestRunner( 1088): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
01-10 13:18:18.584 I/TestRunner( 1088): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
01-10 13:18:18.584 I/TestRunner( 1088): ----- end exception -----
01-10 13:18:18.604 I/TestRunner( 1088): finished: testInvokeProcessorAfterReachingCapacity(com.couchbase.lite.support.BatcherTest)
01-10 13:18:18.644 I/TestRunner( 1088): started: testWaitForPendingFutures(com.couchbase.lite.support.BatcherTest)
```

**Comment by hideki** [comment]
I did not see this issue for a while. Our fix for Batcher might fix this issue too.
