### ISSUE TITLE
testPullReplicatonWithManyAttachmentRevisions falied on jenkins

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/couchbase-lite-android#747]
http://mobile.jenkins.couchbase.com/view/Couchbase_Lite/job/couchbase-lite-android-build/520/artifact/logcat.txt
```
01-10 15:01:02.584 D/Sync    ( 1080): State transition: IDLE -> STOPPING (via STOP_GRACEFUL).  this: com.couchbase.lite.replicator.PullerInternal@b42cf840
01-10 15:01:02.584 D/Database( 1080): Closed com.couchbase.lite.Manager@b43b9570
01-10 15:01:02.584 I/TestRunner( 1080): failed: testPullReplicatonWithManyAttachmentRevisions(com.couchbase.lite.replicator.ReplicationTest)
01-10 15:01:02.584 I/TestRunner( 1080): ----- begin exception -----
01-10 15:01:02.584 I/TestRunner( 1080): 
01-10 15:01:02.584 I/TestRunner( 1080): junit.framework.AssertionFailedError
01-10 15:01:02.584 I/TestRunner( 1080): 	at junit.framework.Assert.fail(Assert.java:48)
01-10 15:01:02.584 I/TestRunner( 1080): 	at junit.framework.Assert.assertTrue(Assert.java:20)
01-10 15:01:02.584 I/TestRunner( 1080): 	at junit.framework.Assert.assertTrue(Assert.java:27)
01-10 15:01:02.584 I/TestRunner( 1080): 	at com.couchbase.lite.LiteTestCaseWithDB.stopReplication(LiteTestCaseWithDB.java:526)
01-10 15:01:02.584 I/TestRunner( 1080): 	at com.couchbase.lite.replicator.ReplicationTest.testPullReplicatonWithManyAttachmentRevisions(ReplicationTest.java:4621)
01-10 15:01:02.584 I/TestRunner( 1080): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-10 15:01:02.584 I/TestRunner( 1080): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-10 15:01:02.584 I/TestRunner( 1080): 	at junit.framework.TestCase.runTest(TestCase.java:168)
01-10 15:01:02.584 I/TestRunner( 1080): 	at junit.framework.TestCase.runBare(TestCase.java:134)
01-10 15:01:02.584 I/TestRunner( 1080): 	at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
01-10 15:01:02.584 I/TestRunner( 1080): 	at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:84)
01-10 15:01:02.584 I/TestRunner( 1080): 	at junit.framework.TestResult$1.protect(TestResult.java:115)
01-10 15:01:02.584 I/TestRunner( 1080): 	at junit.framework.TestResult.runProtected(TestResult.java:133)
01-10 15:01:02.584 I/TestRunner( 1080): 	at junit.framework.TestResult.run(TestResult.java:118)
01-10 15:01:02.584 I/TestRunner( 1080): 	at junit.framework.TestCase.run(TestCase.java:124)
01-10 15:01:02.584 I/TestRunner( 1080): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
01-10 15:01:02.584 I/TestRunner( 1080): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
01-10 15:01:02.584 I/TestRunner( 1080): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
01-10 15:01:02.584 I/TestRunner( 1080): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
01-10 15:01:02.594 I/TestRunner( 1080): ----- end exception -----
```

**Comment by hideki** [comment]
We did not see this test failure for a while. Recent our bug fixes might fix this issue too.
