### ISSUE TITLE
ReplicationTest.testStop failed on jenkins

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/couchbase-lite-android#748]
http://mobile.jenkins.couchbase.com/view/Couchbase_Lite/job/couchbase-lite-android-build/520/artifact/logcat.txt

```
 15:02:51.194 I/TestRunner( 1080): failed: testStop(com.couchbase.lite.replicator.ReplicationTest)
01-10 15:02:51.194 I/TestRunner( 1080): ----- begin exception -----
01-10 15:02:51.204 I/TestRunner( 1080): 
01-10 15:02:51.204 I/TestRunner( 1080): junit.framework.AssertionFailedError: expected:<-1> but was:<0>
01-10 15:02:51.204 I/TestRunner( 1080): 	at junit.framework.Assert.fail(Assert.java:50)
01-10 15:02:51.204 I/TestRunner( 1080): 	at junit.framework.Assert.failNotEquals(Assert.java:287)
01-10 15:02:51.204 I/TestRunner( 1080): 	at junit.framework.Assert.assertEquals(Assert.java:67)
01-10 15:02:51.204 I/TestRunner( 1080): 	at junit.framework.Assert.assertEquals(Assert.java:199)
01-10 15:02:51.204 I/TestRunner( 1080): 	at junit.framework.Assert.assertEquals(Assert.java:205)
01-10 15:02:51.204 I/TestRunner( 1080): 	at com.couchbase.lite.replicator.ReplicationTest.testStop(ReplicationTest.java:4852)
01-10 15:02:51.204 I/TestRunner( 1080): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-10 15:02:51.204 I/TestRunner( 1080): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-10 15:02:51.204 I/TestRunner( 1080): 	at junit.framework.TestCase.runTest(TestCase.java:168)
01-10 15:02:51.204 I/TestRunner( 1080): 	at junit.framework.TestCase.runBare(TestCase.java:134)
01-10 15:02:51.204 I/TestRunner( 1080): 	at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
01-10 15:02:51.204 I/TestRunner( 1080): 	at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:84)
01-10 15:02:51.204 I/TestRunner( 1080): 	at junit.framework.TestResult$1.protect(TestResult.java:115)
01-10 15:02:51.204 I/TestRunner( 1080): 	at junit.framework.TestResult.runProtected(TestResult.java:133)
01-10 15:02:51.204 I/TestRunner( 1080): 	at junit.framework.TestResult.run(TestResult.java:118)
01-10 15:02:51.204 I/TestRunner( 1080): 	at junit.framework.TestCase.run(TestCase.java:124)
01-10 15:02:51.204 I/TestRunner( 1080): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
01-10 15:02:51.204 I/TestRunner( 1080): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
01-10 15:02:51.204 I/TestRunner( 1080): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
01-10 15:02:51.204 I/TestRunner( 1080): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

**Comment by hideki** [comment]
This issue have not been reproduced on jenkins for a while. I assume recent our bug fixes also fixed this issue.
