### ISSUE TITLE
with buildAndroidWithArtifacts: Execution failed for task ':libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders'.

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/couchbase-lite-android#749]
http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-create-zip-release/28/console

steps from jenkins( please set correct path for your env):
```
export buildAndroidWithArtifacts=True
export ANDROID_NDK_HOME=/home/andrei/Android/android-ndk-r10e/
export ANDROID_SDK_HOME=/home/andrei/Android/Sdk/
export ANDROID_HOME=/home/andrei/Android/Sdk/
export PATH=$PATH:$ANDROID_SDK_HOME/tools:$ANDROID_SDK_HOME/platform-tools:/usr/lib/llvm-3.6/bin

export branch=master
export VERSION=0.0.0
export BLD_NUM='519'
export ACTUAL_BLD_NUM=519

export MAVEN_UPLOAD_VERSION=${VERSION}-${ACTUAL_BLD_NUM}
export MAVEN_UPLOAD_REPO_URL="http://files.couchbase.com/maven2/"


git clone https://github.com/couchbase/couchbase-lite-android.git
 cd couchbase-lite-android
 git checkout ${branch}
 git pull
 git log -3
 git status
 git submodule init && git submodule update
 cp settings.gradle.example settings.gradle

 # set correct version 
 sed -i -e "s/%VERSION_NAME%/${VERSION}/" libraries/couchbase-lite-java-core/src/main/java/com/couchbase/lite/support/Version.java
 sed -i -e "s/%VERSION_CODE%/${BLD_NUM}/" libraries/couchbase-lite-java-core/src/main/java/com/couchbase/lite/support/Version.java
 git status


 ./gradlew build  --debug --stacktrace

```

result:
```
21:43:48.927 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders (Thread[main,5,main]) started.
21:43:48.927 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders
21:43:48.927 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders'
21:43:48.927 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders' is up-to-date
21:43:48.927 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
21:43:48.928 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders'.
21:43:48.928 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command 'javah''. Working directory: /home/couchbase/jenkins/workspace/couchbase-lite-android-create-zip-release/couchbase-lite-android/libraries/couchbase-lite-java-forestdb Command: javah -d vendor/cbforest/Java/jni -classpath vendor/cbforest/Java/src com.couchbase.cbforest.Database com.couchbase.cbforest.Document com.couchbase.cbforest.DocumentIterator com.couchbase.cbforest.ForestException com.couchbase.cbforest.Indexer com.couchbase.cbforest.Logger com.couchbase.cbforest.QueryIterator com.couchbase.cbforest.View
21:43:48.929 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Environment for process 'command 'javah'': {JENKINS_HOME=/var/jenkins_home, MAVEN_UPLOAD_USERNAME=tleyden, BLD_NUM=519, ROOT_BUILD_CAUSE=MANUALTRIGGER, SHLVL=1, NODE_LABELS=android java mobile-android ubuntu-14.04, SSH_CLIENT=172.17.42.1 59269 22, HUDSON_URL=http://mobile.jenkins.couchbase.com/, MAIL=/var/mail/couchbase, JOB_URL=http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-create-zip-release/, MAVEN_UPLOAD_VERSION=0.0.0-519, PWD=/home/couchbase/jenkins/workspace/couchbase-lite-android-create-zip-release/couchbase-lite-android, BUILD_ID=28, BUILD_CAUSE=MANUALTRIGGER, LOGNAME=couchbase, VERSION=0.0.0, BUILD_TAG=jenkins-couchbase-lite-android-create-zip-release-28, BUILD_URL=http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-create-zip-release/28/, NODE_NAME=mobile-android, buildAndroidWithArtifacts=True, BUILD_NUMBER=28, SSH_CONNECTION=172.17.42.1 59269 172.17.0.24 22, EXECUTOR_NUMBER=0, OLDPWD=/home/couchbase/jenkins/workspace/couchbase-lite-android-create-zip-release/couchbase-lite-android, SHELL=/bin/bash, JENKINS_SERVER_COOKIE=2982a819cf2db79b, ROOT_BUILD_CAUSE_MANUALTRIGGER=true, BUILD_DISPLAY_NAME=#28, WORKSPACE=/home/couchbase/jenkins/workspace/couchbase-lite-android-create-zip-release, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games, JENKINS_URL=http://mobile.jenkins.couchbase.com/, USER=couchbase, JOB_NAME=couchbase-lite-android-create-zip-release, HOME=/home/couchbase, MAVEN_UPLOAD_REPO_URL=http://files.couchbase.com/maven2/, BUILD_CAUSE_MANUALTRIGGER=true, HUDSON_SERVER_COOKIE=2982a819cf2db79b, MAVEN_UPLOAD_PASSWORD=d2bz08MWfIBDat8h4Wpgb1HhV+oc1KVIoCVgPF54ypM=, HUDSON_COOKIE=51326e63-b504-4909-9f86-96285a28d8d6, HUDSON_HOME=/var/jenkins_home, branch=master, ANDROID_HOME=/home/couchbase/jenkins/tools/android-sdk}
21:43:48.929 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
21:43:48.929 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'javah'.
21:43:48.931 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
21:43:48.932 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
21:43:48.932 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command 'javah''
21:43:49.553 [ERROR] [system.err] Error: Could not find class file for 'com.couchbase.cbforest.Database'.
21:43:49.554 [ERROR] [system.err] Error: Could not find class file for 'com.couchbase.cbforest.Document'.
21:43:49.554 [ERROR] [system.err] Error: Could not find class file for 'com.couchbase.cbforest.DocumentIterator'.
21:43:49.554 [ERROR] [system.err] Error: Could not find class file for 'com.couchbase.cbforest.ForestException'.
21:43:49.554 [ERROR] [system.err] Error: Could not find class file for 'com.couchbase.cbforest.Indexer'.
21:43:49.554 [ERROR] [system.err] Error: Could not find class file for 'com.couchbase.cbforest.Logger'.
21:43:49.555 [ERROR] [system.err] Error: Could not find class file for 'com.couchbase.cbforest.QueryIterator'.
21:43:49.555 [ERROR] [system.err] Error: Could not find class file for 'com.couchbase.cbforest.View'.
21:43:49.573 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
21:43:49.574 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'javah'' finished with exit value 1 (state: FAILED)
21:43:49.575 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders'
21:43:49.575 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders FAILED
21:43:49.576 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders (Thread[main,5,main]) completed. Took 0.649 secs.
21:43:49.576 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 6.721 secs, idle: 0.006 secs
21:43:49.584 [ERROR] [org.gradle.BuildExceptionReporter] 
21:43:49.585 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
21:43:49.586 [ERROR] [org.gradle.BuildExceptionReporter] 
21:43:49.586 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
21:43:49.586 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders'.
21:43:49.586 [ERROR] [org.gradle.BuildExceptionReporter] > Process 'command 'javah'' finished with non-zero exit value 1
21:43:49.587 [ERROR] [org.gradle.BuildExceptionReporter] 
21:43:49.587 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
21:43:49.588 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders'.
21:43:49.588 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
21:43:49.588 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
21:43:49.588 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
21:43:49.588 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
21:43:49.588 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
21:43:49.589 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
21:43:49.589 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
21:43:49.589 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
21:43:49.589 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
21:43:49.589 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
21:43:49.589 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
21:43:49.590 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
21:43:49.590 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
21:43:49.590 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
21:43:49.590 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
21:43:49.590 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
21:43:49.590 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
21:43:49.591 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
21:43:49.591 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
21:43:49.591 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
21:43:49.591 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
21:43:49.591 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
21:43:49.591 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
21:43:49.592 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
21:43:49.592 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
21:43:49.592 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
21:43:49.592 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
21:43:49.592 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
21:43:49.592 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
21:43:49.592 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
21:43:49.593 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
21:43:49.593 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
21:43:49.593 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
21:43:49.593 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
21:43:49.593 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
21:43:49.593 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
21:43:49.594 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
21:43:49.594 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
21:43:49.594 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
21:43:49.594 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
21:43:49.594 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
21:43:49.595 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
21:43:49.595 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.Main.doAction(Main.java:33)
21:43:49.595 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
21:43:49.595 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
21:43:49.595 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
21:43:49.595 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
21:43:49.595 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
21:43:49.596 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
21:43:49.596 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
21:43:49.596 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.process.internal.ExecException: Process 'command 'javah'' finished with non-zero exit value 1
21:43:49.596 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:365)
21:43:49.596 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
21:43:49.596 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.tasks.AbstractExecTask.exec(AbstractExecTask.java:54)
21:43:49.597 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
21:43:49.597 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
21:43:49.597 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
21:43:49.597 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
21:43:49.597 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:589)
21:43:49.597 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:572)
21:43:49.598 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
21:43:49.598 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
21:43:49.598 [ERROR] [org.gradle.BuildExceptionReporter] 	... 49 more
21:43:49.598 [ERROR] [org.gradle.BuildExceptionReporter] 
21:43:49.599 [LIFECYCLE] [org.gradle.BuildResultLogger] 
21:43:49.599 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
```

**Comment by hideki** [comment]
@andreibaranouski fixed this issue in scripts on jenkins
http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-create-zip-release/
