### ISSUE TITLE
ClassCastException when upgrading from 1.1 to 1.2

### ISSUE THREAD

**Issue by biokys** [couchbase/couchbase-lite-android#790]
I am getting this stacktrace when i trying to migrate from 1.1.0-536 to 1.2.0:

`Process: com.droid4you.application.wallet, PID: 24368
                                                   java.lang.RuntimeException: Unable to create application com.droid4you.application.wallet.Application: java.lang.RuntimeException: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4798)
                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:157)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5525)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                    Caused by: java.lang.RuntimeException: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
                                                       at com.couchbase.lite.store.SQLiteStore.runInTransaction(SQLiteStore.java:676)
                                                       at com.couchbase.lite.Database.runInTransaction(Database.java:552)
                                                       at com.couchbase.lite.DatabaseUpgrade.importData(DatabaseUpgrade.java:104)
                                                       at com.couchbase.lite.Manager.upgradeDatabase(Manager.java:830)
                                                       at com.couchbase.lite.Manager.upgradeOldDatabaseFiles(Manager.java:808)
                                                       at com.couchbase.lite.Manager.<init>(Manager.java:130)
                                                       at com.yablohn.internal.CouchDbProvider.init(CouchDbProvider.java:271)`

on line 271 is this code: `mManager = new Manager(new AndroidContext(mContext), Manager.DEFAULT_OPTIONS);`

and

`Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
                                                       at com.couchbase.lite.store.SQLiteStore.forceInsert(SQLiteStore.java:1610)
                                                       at com.couchbase.lite.Database.forceInsert(Database.java:1826)
                                                       at com.couchbase.lite.DatabaseUpgrade.importDoc(DatabaseUpgrade.java:252)
                                                       at com.couchbase.lite.DatabaseUpgrade.access$000(DatabaseUpgrade.java:31)
                                                       at com.couchbase.lite.DatabaseUpgrade$1.run(DatabaseUpgrade.java:111)
                                                       at com.couchbase.lite.store.SQLiteStore.runInTransaction(SQLiteStore.java:672)
                                                       at com.couchbase.lite.Database.runInTransaction(Database.java:552) 
                                                       at com.couchbase.lite.DatabaseUpgrade.importData(DatabaseUpgrade.java:104) 
                                                       at com.couchbase.lite.Manager.upgradeDatabase(Manager.java:830) 
                                                       at com.couchbase.lite.Manager.upgradeOldDatabaseFiles(Manager.java:808) 
                                                       at com.couchbase.lite.Manager.<init>(Manager.java:130) 
                                                       at com.yablohn.internal.CouchDbProvider.init(CouchDbProvider.java:271) 
                                                       at com.yablohn.internal.CouchDbProvider.<init>(CouchDbProvider.java:63) 
                                                       at com.yablohn.internal.Yablohn.initialize(Yablohn.java:17) 
                                                       at com.droid4you.application.wallet.Application.onCreate(Application.java:178) 
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4795) 
                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:157) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5525) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) `

**Comment by biokys** [comment]
I found out where is problem probably. I am using 'type' keyword in one of my documents :( and as i see you are using it for something different here in SqliteStore class. Here: docType = (String) rev.getObject("type");

What can I do now? Hundreds of thousand of our clients are already using this.

**Comment by hideki** [comment]
Hi @biokys,

Duplicated with: https://github.com/couchbase/couchbase-lite-java-core/issues/1041

We already fixed this issue. If you can use build from master branch, please try to use 0.0.0-586? http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-586/

Thanks,
Hideki

**Comment by biokys** [comment]
I am using the latest version: 0.0.0-616 and it still uses ```(String) rev.getObject("type")``` in SQLiteStore:1635 that is in conflict with one of my custom document attributes. What can I do?

**Comment by hideki** [comment]
@biokys we will fix this soon.

**Comment by biokys** [comment]
@hideki do you have idea when?

**Comment by hideki** [comment]
We plan to release 1.2.1 which is bug fix release in few weeks. I will put the fix in 1.2.1 release.

**Comment by hideki** [comment]
@biokys could you please verify the bug fix with using  0.0.0-618 build which was build from master branch? http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-618/

**Comment by biokys** [comment]
Yes, it is working now. How stable is this version? Can we use it for production?

**Comment by hideki** [comment]
current version of master branch is equal with 1.2.0 + many bug fixes. So it is stable. but QE is not tested. So I can not guarantee.

**Comment by biokys** [comment]
Ok, thx
