### ISSUE TITLE
CouchBase crashes at Android N preview

### ISSUE THREAD

**Issue by condesales** [couchbase/couchbase-lite-android#801]
### Version
couchbase-lite-android:1.2.0
### Steps
Simply running the app
### Explanation
Trying to run my app at N preview I'm getting the following exception:
```java
java.lang.UnsatisfiedLinkError: No implementation found for long com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeOpen(java.lang.String, int, java.lang.String, boolean, boolean) (tried Java_com_couchbase_lite_internal_database_sqlite_SQLiteConnection_nativeOpen and Java_com_couchbase_lite_internal_database_sqlite_SQLiteConnection_nativeOpen__Ljava_lang_String_2ILjava_lang_String_2ZZ)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:178)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:461)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:191)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:183)
at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:814)
at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:798)
at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:693)
at com.couchbase.lite.storage.SQLiteStorageEngineBase.open(SQLiteStorageEngineBase.java:62)
at com.couchbase.lite.store.SQLiteStore.open(SQLiteStore.java:180)
at com.couchbase.lite.Database.open(Database.java:1150)
at com.couchbase.lite.Manager.openDatabase(Manager.java:335)
at com.couchbase.lite.Manager.getDatabase(Manager.java:299)
```
I know that N preview just got released few hours ago and it will take few months before it hits any nexus phone officially but I though it worths raising the flag.

**Comment by hideki** [comment]
@condesales,
Could you please provide test device architecture? armeavi-v7a?

**Comment by plusCubed** [comment]
I was encountering this error on 5.1 and 6.0 in the Android Studio 2.0 betas. It probably had to do with the changes in deploying only the resources a specific device needs. In either case, disabling Instant Run works in 2.0 beta6. The newest Android Studio 2.1 alpha fixed running with Instant Run for as well.

See: https://code.google.com/p/android/issues/detail?id=200897

**Comment by condesales** [comment]
@hideki x86_64
@plusCubed Instant Run is disabled for me. I looks like it's a different issue.

**Comment by plusCubed** [comment]
@condesales I misspoke - don't know where I got that idea from. I had Instant Run off as well - I just started using :installDebug, which adds the native libraries correctly.

Again, in either case, as I said, 2.1.0 alpha fixes it.

**Comment by biokys** [comment]
Same issue

**Comment by condesales** [comment]
I got users complaining today about the app crashing on Android N preview.
Probably not a deploy issue after all @plusCubed?

**Comment by plusCubed** [comment]
Hmmm... this appears to be happening for me in release builds, but not debug builds.

**Comment by splatte** [comment]
I am having the same issue with a stacktrace that begins only slightly different. I tried various combinations of N Preview x86/x86_64, gradle plugin 2.1.0-alpha4/alpha5, couchbase-lite-android 1.2.0/1.2.1, instant run on/off. always debug builds.

stacktrace:
```
java.lang.UnsatisfiedLinkError: No implementation found for long com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeOpen(java.lang.String, int, java.lang.String, boolean, boolean) (tried Java_com_couchbase_lite_internal_database_sqlite_SQLiteConnection_nativeOpen and Java_com_couchbase_lite_internal_database_sqlite_SQLiteConnection_nativeOpen__Ljava_lang_String_2ILjava_lang_String_2ZZ)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:178)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:461)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:191)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:183)
at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:814)
at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:798)
at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:693)
at com.couchbase.lite.storage.SQLiteStorageEngineBase.open(SQLiteStorageEngineBase.java:62)
at com.couchbase.lite.DatabaseUpgrade.importData(DatabaseUpgrade.java:81)
at com.couchbase.lite.Manager.upgradeDatabase(Manager.java:831)
at com.couchbase.lite.Manager.upgradeOldDatabaseFiles(Manager.java:809)
at com.couchbase.lite.Manager.<init>(Manager.java:131)
```

**Comment by hideki** [comment]
Android N does not allow to use non public APIs (including SQLite)
https://developer.android.com/preview/behavior-changes.html#ndk

**Comment by hideki** [comment]
Solutions:
- Make custom SQLite as default storage engine
- Make forestdb as default storage engine.

**Comment by condesales** [comment]
Is it possible to easily migrate an existing DB from SQLite to ForestDB?

**Comment by hideki** [comment]
@condesales 

> Is it possible to easily migrate an existing DB from SQLite to ForestDB?

yes

Just open the database with ForestDB configuration.

**Comment by hideki** [comment]
TODOs:

Test following storage types with Android N
- [ ] default SQLite
- [ ] custom SQLite
- [ ] SQLCipher
- [ ] ForestDB
- [ ] ForestDB with encryption

**Comment by condesales** [comment]
@hideki when opening DB with ForestDB setup my views can find the documents, but `document.getProperties()` return `null`. Any ideias?

**Comment by hideki** [comment]
For v1.3, make custom SQLite (couchbase provided SQLite) as a default storage type.

**Comment by hideki** [comment]
Hi All,
if you have time, could you please try the latest build from master branch which includes fix of this issue? 
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-727/
Thanks!

**Comment by tikimcfee** [comment]
Hey there guys, +1'ing this thread to see if there's been any official word on the compatibility of CBLite with Android N. Is it currently SQL only? If so, what dependency must be set to compile correctly without the error of 'improper library open'?
