### ISSUE TITLE
Exceptions on push replication -  open failed: EMFILE (Too many open files) ?!

### ISSUE THREAD

**Issue by orenyodfat** [couchbase/couchbase-lite-android#808]
Android  0.0.600
ForestDB
While trying to push a lot of docs and attachments...
Here is the logcat
03-14 16:25:47.271 ? D/SPARKUP: Push Replicator processed 0 / 48
03-14 16:25:47.304 ? E/Database: BlobStore: Unexpected file not found in blob store
                                 java.io.FileNotFoundException: /data/data/com.sparkup.device/files/spkdb_v80.cblite2/attachments/1109E5D87A8449A304E58940091873F7163D3AD3.blob: open failed: EMFILE (Too many open files)
                                     at libcore.io.IoBridge.open(IoBridge.java:456)
                                     at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                     at com.couchbase.lite.BlobStore.blobStreamForKey(BlobStore.java:466)
                                     at com.couchbase.lite.replicator.PusherInternal.uploadMultipartRevision(PusherInternal.java:612)
                                     at com.couchbase.lite.replicator.PusherInternal.access$600(PusherInternal.java:53)
                                     at com.couchbase.lite.replicator.PusherInternal$5.onCompletion(PusherInternal.java:458)
                                     at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:213)
                                     at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:231)
                                     at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:299)
                                     at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:248)
                                     at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:102)
                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                     at java.lang.Thread.run(Thread.java:818)
                                  Caused by: android.system.ErrnoException: open failed: EMFILE (Too many open files)
                                     at libcore.io.Posix.open(Native Method)
                                     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                     at libcore.io.IoBridge.open(IoBridge.java:442)
                                     at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                     at com.couchbase.lite.BlobStore.blobStreamForKey(BlobStore.java:466) 
                                     at com.couchbase.lite.replicator.PusherInternal.uploadMultipartRevision(PusherInternal.java:612) 
                                     at com.couchbase.lite.replicator.PusherInternal.access$600(PusherInternal.java:53) 
                                     at com.couchbase.lite.replicator.PusherInternal$5.onCompletion(PusherInternal.java:458) 
                                     at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:213) 
                                     at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:231) 
                                     at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:299) 
                                     at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:248) 
                                     at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:102) 
                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                     at java.lang.Thread.run(Thread.java:818) 
Unable to load the blob stream for blobKey: 1109E5D87A8449A304E58940091873F7163D3AD3 - Skipping upload of multipart revision.

**Comment by orenyodfat** [comment]
I susspect the root cause of that is commit  91bc3027a191d42f32a98d27b3546b4964a7a403 at couchbase-lite-java .

**Comment by hideki** [comment]
Hi @orenyodfat,
Thank you very much for your bug report.
It seems InputStream is not closed() in some cases.
Thanks a lot!

**Comment by hideki** [comment]
Duplicate: https://github.com/couchbase/couchbase-lite-java-core/issues/1108
We will track the issue by couchbase/couchbase-lite-java-core/issues/1108. I will close this ticket.
