### ISSUE TITLE
com.couchbase.lite.util.SimpleLogger.e(SimpleLogger.java:69) MISSING msg

### ISSUE THREAD

**Issue by orenyodfat** [couchbase/couchbase-lite-android#811]
```
03-15 17:12:01.122 7344-7344/com.sparkup.device E/AndroidRuntime: FATAL EXCEPTION: main
  Process: com.sparkup.device, PID: 7344
  java.lang.NullPointerException: println needs a message
      at android.util.Log.println_native(Native Method)
      at android.util.Log.e(Log.java:232)
      at com.couchbase.lite.util.SimpleLogger.e(SimpleLogger.java:69)
      at com.couchbase.lite.util.Log.e(Log.java:371)
      at com.couchbase.lite.store.ForestDBStore.add(ForestDBStore.java:816)
      at com.couchbase.lite.Database.put(Database.java:1748)
      at com.couchbase.lite.Database.putRevision(Database.java:1701)
      at com.couchbase.lite.Database.putRevision(Database.java:1692)
      at com.couchbase.lite.Document.putProperties(Document.java:427)
      at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:105)
      at com.sparkup.device.database_utils.DatabaseWrapper.writeAttachment
```

**Comment by hideki** [comment]
PR: https://github.com/couchbaselabs/couchbase-lite-java-forestdb/pull/50
