### ISSUE TITLE
sync gateway connection lost

### ISSUE THREAD

**Issue by miltgrin** [couchbase/couchbase-lite-android#818]
I am testing the connection between an android app and the sync-gateway.  If I turnoff the sync gateway after the app has connected (continuous pull and push).  I see the following error in the log which seems to be caught in the couchbase lite code and is not reflected back to the "changed" method of the ChangeListener.   Is there any way to catch this error in my code to reflect that the sync-gateway is now offline.  The status of the replicator object doesn't ever seem to get set to OFFLINE.  I am running sync-gateway 1.2 along with android couchbase lite 1.2
```
W/ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@7f107c6: Exception in change tracker
org.apache.http.conn.HttpHostConnectException: Connection to http://192.168.1.89:4984 refused
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:193)
    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
    at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:327)
    at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:228)
    at java.lang.Thread.run(Thread.java:818)
 Caused by: java.net.ConnectException: failed to connect to /192.168.1.89 (port 4984) after 60000ms: isConnected failed: ECONNREFUSED (Connection refused)
    at libcore.io.IoBridge.isConnected(IoBridge.java:234)
    at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
    at libcore.io.IoBridge.connect(IoBridge.java:122)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
    at java.net.Socket.connect(Socket.java:884)
    at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149)
    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169) 
    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124) 
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366) 
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560) 
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492) 
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470) 
    at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:327) 
    at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:228) 
    at java.lang.Thread.run(Thread.java:818) 
 Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
    at libcore.io.IoBridge.isConnected(IoBridge.java:223)
    at libcore.io.IoBridge.connectErrno(IoBridge.java:171) 
    at libcore.io.IoBridge.connect(IoBridge.java:122) 
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452) 
    at java.net.Socket.connect(Socket.java:884) 
    at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124) 
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149) 
    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169) 
    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124) 
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366) 
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560) 
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492) 
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470) 
    at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:327) 
    at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:228) 
    at java.lang.Thread.run(Thread.java:818) 
```

**Comment by hideki** [comment]
Hi @miltgrin,

Sorry for slow response.

To catch the error, please use `ChangeListener`.
http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/couchbase-lite/replication/replication/index.html
To obtain Exception from ChangeEvent, please use `ChangeEvent.getError()`
https://github.com/couchbase/couchbase-lite-java-core/blob/5da9e5ba7f0830cf60623de11ae15385f64a7a3c/src/main/java/com/couchbase/lite/replicator/Replication.java#L611

`OFFLINE` state indicates that the mobile device is offline (out of connection), it does not indicate Sync Gateway.

In case sync gateway is OFFLINE, CBL Android/Java fails to connect to SG. But we categorize this error as transient error. So CBL keeps to try to connect after 60sec.

Hope this helps you.

Thanks!
Hideki
