### ISSUE TITLE
ConcurrentModificationException when try to update object

### ISSUE THREAD

**Issue by mtrakal** [couchbase/couchbase-lite-android#834]
Hello I get this error when try to update object.
We are using version 1.2.1-14

```
04-07 14:57:16.004 12778-12778/com.our.app.name E/Database: Unknown Exception: com.couchbase.lite.Database[/data/data/com.our.app.name/files/local-08be73d8-8498-4312-b7f8-10107ac23d65.cblite2] got exception posting change notifications
 java.util.ConcurrentModificationException
     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
     at java.util.HashMap$KeyIterator.next(HashMap.java:814)
     at com.couchbase.lite.Database.postChangeNotifications(Database.java:2229)
     at com.couchbase.lite.Database.databaseStorageChanged(Database.java:707)
     at com.couchbase.lite.store.SQLiteStore.add(SQLiteStore.java:1535)
     at com.couchbase.lite.Database.put(Database.java:1721)
     at com.couchbase.lite.Database.putRevision(Database.java:1674)
     at com.couchbase.lite.Database.putRevision(Database.java:1665)
     at com.couchbase.lite.Document.putProperties(Document.java:430)
     at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:105)
     at com.couchbase.lite.Document.update(Document.java:289)
```

```
public synchronized boolean delete(String id) {
        Document doc = getDatabase().getDocument(id);
        try {
            doc.update(new Document.DocumentUpdater() {
                @Override
                public boolean update(UnsavedRevision newRevision) {
                    newRevision.setIsDeletion(true);
                    Map<String, Object> properties = newRevision.getUserProperties();
                    properties.put("deletedAt", DateTime.now(DateTimeZone.UTC).toString());
                    newRevision.setUserProperties(properties);
                    return true;
                }
            });
        } catch (CouchbaseLiteException e) {
            YablohnLogger.e(TAG, "error while deleting", e);
        }
        return true;
    }
```

**Comment by hideki** [comment]
Hi @mtrakal,

I have a question. Does your codes call  `Database.removeChangeListener(ChangeListener)` or `Database.addChangeListener(ChangeListener listener)` method in callback of `ChangeListener.changed(ChangeEvent event)`?

**Comment by mtrakal** [comment]
I was calling `removeChangeListener` in onDestroy activity method immediately after call `delete` method (finish activity after `delete` call) and multiple call `addChangeListener ` in parent activity which go to front after finish previous activity.
But I'm not sure about calling somewhere in our code `removeChangeListener/addChangeListener` inside  `ChangeListener.changed(ChangeEvent event)`

**Comment by hideki** [comment]
### Note to Self:

#### Current implementation
`changeListeners` is thread safe, and it is synchronized for iteration. It should not cause `ConcurrentModificationException` except add/delete items from `changeListeners` in iteration.

In constructor:
```java
this.changeListeners = Collections.synchronizedSet(new HashSet<ChangeListener>());
```
In private boolean postChangeNotifications()
```java
synchronized (changeListeners) {
    for (ChangeListener changeListener : changeListeners) {
        if (changeListener != null) {
            try {
                changeListener.changed(changeEvent);
            } catch (Exception ex) {
                // Implementation of ChangeListener might throw RuntimeException,
                // ignore it.
                Log.e(TAG, "%s got exception posting change notification: %s",
                        ex, this, changeListener);
            }
        }
    }
}
```

#### Potential solution
However there is possibility application or CBL codes could call `addChangeListener()` or `removeChangeListener()` in-directly in iteration.
To avoid this, `CopyOnWriteArraySet` and `CopyOnWriteArrayList` which is thread-safe by making a fresh copy of the underlying array.

##### Class CopyOnWriteArrayList<E>
https://docs.oracle.com/javase/7/docs/api/index.html?java/util/concurrent/CopyOnWriteArrayList.html
```
A thread-safe variant of ArrayList in which all mutative operations (add, set, and so on) are implemented by making a fresh copy of the underlying array.

This is ordinarily too costly, but may be more efficient than alternatives when traversal operations vastly outnumber mutations, and is useful when you cannot or don't want to synchronize traversals, yet need to preclude interference among concurrent threads. The "snapshot" style iterator method uses a reference to the state of the array at the point that the iterator was created. This array never changes during the lifetime of the iterator, so interference is impossible and the iterator is guaranteed not to throw ConcurrentModificationException. The iterator will not reflect additions, removals, or changes to the list since the iterator was created. Element-changing operations on iterators themselves (remove, set, and add) are not supported. These methods throw UnsupportedOperationException.
```

**Comment by hideki** [comment]
Fixed in couchbase-lite-java-core, PR: https://github.com/couchbase/couchbase-lite-java-core/pull/1197
