### ISSUE TITLE
Android sync stops working

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#859]
I've got a situation where 2 separate android apps have stopped being able to sync in either direction.

There are no error messages in the logs that I can see.  The only noticeable message is this:

    W/Router: com.couchbase.lite.router.Router$4@2122d903 finished inserting 8 revisions in bulk

I've tried restarting both apps, and the sync gateway but without luck.  It doesn't not happen in IOS.

Any ideas?

**Comment by hideki** [comment]
Hi @npomfret,

Does your app sync between Android and Android? or Android, Sync Gateway, and Android?
If Android to Android, there might be bug in Router.

With current information you provided, I don't know what cause the problem. Could you please enable logging with additing following code before creating Manager instance?
```java
Manager.enableLogging(Log. TAG_ROUTER, Log.VERBOSE);
Manager.enableLogging(Log. TAG_LISTENER, Log.VERBOSE);
Manager.enableLogging(Log. TAG_CHANGE_TRACKER, Log.VERBOSE);
Manager.enableLogging(Log.TAG_SYNC, Log.VERBOSE);
Manager.enableLogging(Log.TAG_DATABASE, Log.VERBOSE);
```

Thanks!
Hideki

**Comment by npomfret** [comment]
Thanks.

My app syncs between android and the Sync gateway.  What does it mean to sync between android and android?

All those logging options are already on.  in android studio I am filtering for log messages containing _couchbase_ .  What should I be looking for?  At the point when a document is written to the Android device there's no logging at all at any level and there's no activity in the sync gateway.  I do have 1 android device connected that does work, as well as an iOS device.

**Comment by hideki** [comment]
> What does it mean to sync between android and android?

Android <-> Android: We called Peer to Peer.

> All those logging options are already on. in android studio I am filtering for log messages containing couchbase . What should I be looking for? At the point when a document is written to the Android device there's no logging at all at any level and there's no activity in the sync gateway. I do have 1 android device connected that does work, as well as an iOS device.

As you wrote, no synchronization happens. Could you please confirm replicators are running?

With current information, I don't know what happens with your environment. Could you please provide more detail information?

**Comment by npomfret** [comment]
Where can I learn more about Peer to Peer couchbase lite?  

Yes, the replication tasks are running:

```
{
  completed_change_count: 11533,
  source: 'http://192.168.1.185:4986/sync_gateway',
  task: 'repl002',
  status: 'Processed 11533 / 11733 changes',
  progress: 98,
  continuous: true,
  target: 'pomochat_330b2fb7-efde-420e-a704-6df7d5f89f9a',
  change_count: 11733,
  type: 'Replication'
}
, {completed_change_count: 68,
source: 'pomochat_330b2fb7-efde-420e-a704-6df7d5f89f9a',
task: 'repl001',
status: 'Processed 68 / 68 changes',
progress: 100,
continuous: true,
target: 'http://192.168.1.185:4984/sync_gateway',
change_count: 68,
type: 'Replication'
}

```

I don't have any more info.  Basically, I have an android app.  One device that it's installed on is no longer replicating.  There are no obvious errors in the logs, I'm not sure what to do.  I can try a debug it - is there an obvious class or method call that I should look at?

**Comment by hideki** [comment]
> Where can I learn more about Peer to Peer couchbase lite?

Following blog could be good starting point
http://blog.couchbase.com/photodrop

> I don't have any more info. Basically, I have an android app. One device that it's installed on is no longer replicating. There are no obvious errors in the logs, I'm not sure what to do. I can try a debug it - is there an obvious class or method call that I should look at?

As first step, could you please capture all log files? Also could you please provide what version of CBL app is using. Is app a native app? PhoneGap app? etc...

**Comment by npomfret** [comment]
Hi.  I don't know what happened but the sync started working again.  If it fails again I'll capture the logs but for now I'll close this ticket.

Thanks for the peer-to-peer info.

**Comment by npomfret** [comment]
The problem has returned and I have all the logs (below).  I've tried restarting and reinstalling the app, but leaving the data untouched.  Can't get it to work.  Sync is reported to be running in both directions.

There's an exception at the bottom `E/Router: IOException writing to internal streams` that looks like the cause.  

```
05-11 11:23:40.925 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-hPr_bedUlUMtx1kzO_Bnce #2-2ef8f96255d8cbebb25a721432578f90}
05-11 11:23:40.925 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-qZL2vVHeqUn00-FoQ6vPrN #1-87006091ba7869b547905ae7b2f3deb4}
05-11 11:23:40.925 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-btDNKahs6hFdN6zXafgzXf #1-e1d03759b264ca4fd212e784b4bd841e}
05-11 11:23:40.925 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-VDQ4ELKPHH0nTUljIfFej_ #2-1cc22816c92628f182966b375edda2c6}
05-11 11:23:40.925 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-M3GS287jXQTqXpZim5w3F9 #17-b9aea0489951a01905c54d9b9a816e64}
05-11 11:23:40.926 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-_j-w2yxIhB71ED5CVYDmgS #1-d036441b8f065ee1a79e0da71b1d2039}
05-11 11:23:40.926 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-u67jqUotFPV9oHeXpdsiA- #1-da062ddab5c0eee186c0e80a18cb868d}
05-11 11:23:40.926 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-vkGk1rcZ0YwI2ogyVFZsBV #2-d37e61dbaa3f18890e0b1c57883d415d}
05-11 11:23:40.926 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {1a32dd65-4aa1-4ac7-bb46-ba1e73ccc4de #2-45375525d6ab4783d1b70ed27cb1b721}
05-11 11:23:40.926 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-9L3vMJbDyYFSC5BZvchM6T #2-e8f794d7667710c66ba6efa206d01d21}
05-11 11:23:40.926 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {9659a2e1-5b4e-48ac-bf25-0fcce27d15e7 #2-c23040e767e08f88a0dcb9b7932d48b5}
05-11 11:23:40.926 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {469c940a-b5e2-4c16-b10c-548ccc2acd2a #2-e4dc2e67791ac95b4326939df60bc1ca}
05-11 11:23:40.926 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-tqGuzpZ-41i4ugxTLrF0vE #2-8cf187fd424a60447fc28e69e52e6de1}
05-11 11:23:40.926 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-DKYPwzycZoMQ-c4EPcoD-N #1-9a571f4ec80acbb51bca3404e6857856}
05-11 11:23:40.926 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-9aaUCv7ABVvdUZbrm1f9Jr #1-497b9f2cab9f2723eb5b260e015882de}
05-11 11:23:40.927 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-a2s16JqyIf8mBN2ogZ8s-X #2-d2491fe9a176dd22b51d595462ec8548}
05-11 11:23:40.927 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-ad3nqTtAeFy9bOMBKugtFD #2-db39632478a6df1c99b5cde53809dc3a}
05-11 11:23:40.927 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-8AwDF0Ccptbhe7siXCm3f7 #1-641533f5ac6269ca1215153a0b1e0fec}
05-11 11:23:40.927 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-oETYP6IG12fKbxRXUDsGbo #1-04dda3f8a9bef587dbadbece73ce4e10}
05-11 11:23:40.927 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-y8sFLCMcifyF433O1TyXNU #2-f321120f46c6f04f86f87e58f08ecde2}
05-11 11:23:40.927 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-ncH8PvUVlQ5Sq5h03Y8Eqg #1-b76e72221d5f9e48dc356b65aae51d30}
05-11 11:23:40.927 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-7-8OhMlrtEEG70AhLO5mob #1-378446977ea27ca61e84e8bb416d3b16}
05-11 11:23:40.927 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-e4jUGlLWB1tOmS5hRPHAap #9-394e2ef6070c8f1211aaa64a1bccfe0b}
05-11 11:23:40.927 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-gnqNxdvu1_wY6iMBfSw_qA #2-58751595cb9b6668b19ab689d6577b47}
05-11 11:23:40.927 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-JUD4_VS8pY7zaWwFGcwXGp #1-9adf4005a7fc437a018d947575c439ba}
05-11 11:23:40.927 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-BapaaASLKTLgtWVsG-tEIU #1-cb4b887bd1765f00bd8ed738aa0785f1}
05-11 11:23:40.928 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-T2lrfiI_lbi7wbIRVgzK2V #2-c38ea90b7e6f9c73b408dc0a091c6c01}
05-11 11:23:40.928 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-aPX28EFoWANgYSmBYwc02M #2-024f4c05619fe886781cd5e0e2ec6d1e}
05-11 11:23:40.928 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {-PRamdZhlsX02aiMjp7twfe #2-926d5b4fa7c09a972db62c7b2ce56514}
05-11 11:23:40.928 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {4605192772e13b378950ef79651a4f3c #30-a70ae877c80ef82501f7d480c3a5a973}
05-11 11:23:40.928 4896-5037/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 0 not in set, for rev {ping #7878-dc7ec156135a2cd3ac157ef3b5cd1e76}
05-11 11:23:45.350 4896-5064/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending() called w/ rev: {498cef41-18a3-485b-82f8-bd9348ea58e0 #2-d1df5dbe85a51d819d36232bdf293d4c}, but pendingSequences empty
05-11 11:23:45.350 4896-5064/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending() called w/ rev: {8f40cae1-12a4-44f8-97ec-5cc2a6105ef1 #2-3bbecda13726599acfd7eb6b03abeb13}, but pendingSequences empty
05-11 11:23:47.003 4896-5055/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending() called w/ rev: {33fa2eb8-ca2e-47a4-be8c-d20a42ba9c12 #2-8912144e4c1df44be9750a4ff925e24f}, but pendingSequences empty
05-11 11:23:47.003 4896-5055/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending() called w/ rev: {-0LLYxBiYccYddlX0h13EBP #2-500b05de0db71bea1cf768ef327863fe}, but pendingSequences empty
05-11 11:23:47.315 4896-4950/com.pomochat W/ReactNativeJS: Warning: ReactNative.createElement is deprecated. Use React.createElement from the "react" package instead.
05-11 11:23:47.639 4896-5091/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending() called w/ rev: {fbf9d1024fae33e4ccdde31e0c49b478 #20-dc989016cd6051144fcd4f1b1a4da023}, but pendingSequences empty
05-11 11:23:49.782 4896-5013/com.pomochat W/Sync: com.couchbase.lite.replicator.PusherInternal@9a14405: removePending: sequence 38506 not in set, for rev {f58a2498e0d3e160c5903e4eba211f32 #22-1a827724fad44461121646d65db501e0}
05-11 11:23:50.929 4896-5012/com.pomochat E/Router: IOException writing to internal streams
                                                    java.io.IOException: Pipe not connected
                                                        at java.io.PipedOutputStream.write(PipedOutputStream.java:174)
                                                        at java.io.OutputStream.write(OutputStream.java:106)
                                                        at java.io.PipedOutputStream.write(PipedOutputStream.java:147)
                                                        at java.io.OutputStream.write(OutputStream.java:82)
                                                        at com.couchbase.lite.router.Router.changed(Router.java:1509)
                                                        at com.couchbase.lite.Database.postChangeNotifications(Database.java:2287)
                                                        at com.couchbase.lite.Database.storageExitedTransaction(Database.java:717)
                                                        at com.couchbase.lite.store.SQLiteStore.endTransaction(SQLiteStore.java:2124)
                                                        at com.couchbase.lite.store.SQLiteStore.runInTransaction(SQLiteStore.java:678)
                                                        at com.couchbase.lite.replicator.PullerInternal.insertDownloads(PullerInternal.java:565)
                                                        at com.couchbase.lite.replicator.PullerInternal$1.process(PullerInternal.java:115)
                                                        at com.couchbase.lite.support.Batcher.processNow(Batcher.java:372)
                                                        at com.couchbase.lite.support.Batcher.access$200(Batcher.java:16)
                                                        at com.couchbase.lite.support.Batcher$2.run(Batcher.java:306)
                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                        at java.lang.Thread.run(Thread.java:818)

```

**Comment by hideki** [comment]
@npomfret What version of Couchbase Lite Android are you using?

**Comment by npomfret** [comment]
I've using com.couchbase.lite:couchbase-lite-android:1.2.0-17

**Comment by hideki** [comment]
@npomfret, Please use v1.2.1

**Comment by hideki** [comment]
As we did not receive any additional comment, I will close this ticket. If issue is still reproducible, please reopen the ticket. Thanks!
