### ISSUE TITLE
Livequery is blocked by replicator

### ISSUE THREAD

**Issue by biokys** [couchbase/couchbase-lite-android#863]
We are using the latest stable 1.2.1-14 version. When our couchdb server is down, livequery is blocked by replicator, which is trying to get to server. After connection timeout, livequery continue to return back local data. I have following question. Is there any possibility to adjust connection timeout, or is there any better solution? As i looked into the code, there is one singlethreaded executor, which is used by replicators as well as by livequery.

**Comment by hideki** [comment]
Hi @biokys,

> Is there any possibility to adjust connection timeout

This is not recommended solution. but it might work as workaround.
You could overwrite following values.
```java
public static int DEFAULT_CONNECTION_TIMEOUT_SECONDS = 60;
public static int DEFAULT_SO_TIMEOUT_SECONDS = 60 * 5;
```
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/support/CouchbaseLiteHttpClientFactory.java#L45-L46

> As i looked into the code, there is one singlethreaded executor, which is used by replicators as well as by livequery.

Methods that access the sync gateway does not use SingleThread Executor. It uses other ExecutorService. I don't think the method access to SG blocks LiveQuery directly. But, as you report, replicator might block LiveQuery.

I believe LiveQuery and Replicator uses Single-Thread ExecutorService to avoid multi-threading issue to access the database. We might need to consider to use other thread for LiveQuery.

To debug this issue, could you please capture thread-dump? I wonder what operation/method blocks LiveQuery.

Thanks!
Hideki

**Comment by hideki** [comment]
I recommend to use `1.2.1`(release version) instead of `1.2.1-14`. If you previously installed 1.2.1, please delete the cache in .gradle.

**Comment by mtrakal** [comment]
I try to upgrade to 1.2.1 (release) (after delete gradle cache) and behaviour is same.

There is trace from two blocking operations
[threads.txt](https://github.com/couchbase/couchbase-lite-android/files/248406/threads.txt)
[threads2.txt](https://github.com/couchbase/couchbase-lite-android/files/248405/threads2.txt)

**Comment by hideki** [comment]
Hi @mtrakal,

Thank you very much for sharing thread-dump. It helps me understand what happening.

From thread dump:

1. Two threads that accesses to CouchDB/SG are waiting the response from the server. These threads are executed from ScheduledExecutorService which is per replication.
1. Some reason app tries to stop replication. (intentionally or permanent error)
1. Replicator tries to shutdown ScheduledExecutorService from `CBLManagerWorkExecutor` which is single thread and its instance is per a Manager.
1. Because of connectivity issue, shutdown takes 60 sec. 60sec is timeout for shutting down ExecutorService.


WorkExecutor thread which is single thread.
```
"CBLManagerWorkExecutor@14561" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks CBLManagerWorkExecutor@14561
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor(Thread.java:1220)
	  - locked <0x3907> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2055)
	  at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1431)
	  at com.couchbase.lite.util.Utils.shutdownAndAwaitTermination(Utils.java:294)
	  at com.couchbase.lite.replicator.ReplicationInternal.close(ReplicationInternal.java:297)
	  at com.couchbase.lite.replicator.ReplicationInternal$20.doIt(ReplicationInternal.java:1324)
	  at com.couchbase.lite.replicator.ReplicationInternal$20.doIt(ReplicationInternal.java:1304)
	  at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:135)
	  at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:133)
	  at com.github.oxo42.stateless4j.StateRepresentation.executeEntryActions(StateRepresentation.java:118)
	  at com.github.oxo42.stateless4j.StateRepresentation.enter(StateRepresentation.java:97)
	  at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:199)
	  at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:126)
	  at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:209)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	  at java.lang.Thread.run(Thread.java:818)
```

Thread which accesses to CouchDB/SG
```
"CBLRequestWorker-https://<hostname>/bb-c72a9940-a142-4061-850e-1fa9c11f6eca/-push-574b1-0@14562" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at com.android.org.conscrypt.NativeCrypto.SSL_read(NativeCrypto.java:-1)
	  at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:689)
	  - locked <0x3908> (a java.lang.Object)
	  at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:103)
	  at org.apache.http.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:134)
	  at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:174)
	  at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:159)
	  at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:489)
	  at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:126)
	  at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:215)
	  at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1191)
	  at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:753)
	  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2646)
	  at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:217)
	  at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:98)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	  at java.lang.Thread.run(Thread.java:818)
```

**Comment by hideki** [comment]
Tasks to fix this issue:
- [ ] step 1: cancel HttpClient request
- [ ] step 2: replicator own own executor service instead of using workexecutor
