### ISSUE TITLE
Warning from latest master branch

### ISSUE THREAD

**Issue by orenyodfat** [couchbase/couchbase-lite-android#879]
I get a lot of warnings like below ...using the latest master branch
???

```
05-22 12:04:08.421 7844-7963/com.sparkup.device W/Database: ForestDB Error: getDocument(docID, true) docID=[ba181d77-0fcb-4990-a38a-f68788879904] error=[com.couchbase.cbforest.ForestException: key not found]

05-22 12:06:37.550 7844-7964/com.sparkup.device E/Query: Exception caught in runAsyncInternal
   com.couchbase.lite.CouchbaseLiteException, Status: 590 (HTTP 500 Database error!)
       at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:257)
       at com.couchbase.lite.View.updateIndexes(View.java:321)
       at com.couchbase.lite.View.updateIndex(View.java:294)
       at com.couchbase.lite.Database.queryViewNamed(Database.java:2067)
       at com.couchbase.lite.Query$2.run(Query.java:483)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by hideki** [comment]
Hi @orenyodfat,
Sorry for super slow reply. Do you have any additional information for this ticket? How can we reproduce this issue? And CBL version number, etc...

**Comment by hideki** [comment]
Hi @orenyodfat , Do you still observe this issue with v1.3.1? Thanks!

**Comment by djpongh** [comment]
We can't reproduce. Without more info, nothing we can do.
