### ISSUE TITLE
SQLiteException: no such table: maps_١ (code 1)

### ISSUE THREAD

**Issue by mtrakal** [couchbase/couchbase-lite-android#880]
Hello,

we get Exceptions from couchbase for some users. It looks that's just Arabic/Persian users generate this crash.

```
compile 'com.couchbase.lite:couchbase-lite-android:1.2.1'
compile 'com.couchbase.lite:couchbase-lite-android-forestdb:1.2.1'
```
You can see, there is some special character on end of: `maps_١`
```
Caused by com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: no such table: maps_١ (code 1): , while compiling: SELECT key, value, docid, revs.sequence FROM 'maps_١', revs, docs WHERE 1 AND revs.sequence = 'maps_١'.sequence AND docs.doc_id = revs.doc_id ORDER BY key, docid LIMIT ? OFFSET ?
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:713)
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:426)
       at com.couchbase.lite.internal.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:595)
       at com.couchbase.lite.internal.database.sqlite.SQLiteProgram.(SQLiteProgram.java:64)
       at com.couchbase.lite.internal.database.sqlite.SQLiteQuery.(SQLiteQuery.java:37)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:48)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1295)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1234)
       at com.couchbase.lite.storage.SQLiteStorageEngineBase.rawQuery(SQLiteStorageEngineBase.java:172)
       at com.couchbase.lite.store.SQLiteViewStore.runQuery(SQLiteViewStore.java:1012)
       at com.couchbase.lite.store.SQLiteViewStore.regularQuery(SQLiteViewStore.java:625)
       at com.couchbase.lite.View.query(View.java:358)
       at com.couchbase.lite.Database.queryViewNamed(Database.java:2073)
       at com.couchbase.lite.Query.run(Query.java:433)
```

http://crashes.to/s/fa605cc8295

**Comment by mtrakal** [comment]
I can reproduce it on Nexus 5 with language: فارسی

**Comment by hideki** [comment]
Hi @mtrakal,

I set Android emulator's Language setting to Persian. However, I could not reproduce the problem just changing the Language setting. Could you please explain how did you test this?

Note to Self:
Persian character `١` means `1` for English. It seems following line of code generate this. `getViewID() ` returned 1, but it seems `1` automatically translated to `١`.
```java
_mapTableName = String.format("%d", getViewID());
```

**Comment by hideki** [comment]
Hi @mtrakal,
 I could not reproduce this issue. If you have time, could you please verify the fix with the build http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-735/ ?

**Comment by mtrakal** [comment]
Hi @hideki,

thanks. It's fixed! :) :+1: 

Test scenario:
- I run app in English/Czech which create valid maps_1 table
- kill app
- change lang to Persian 
- try to start app. It crash on invalid table.

**Comment by mtrakal** [comment]
Got the almost same problem in another place /_revs_diff. Not sure, that name is from couchDB or our app yet. But FYI.
۵ is number 5 (as google translator said)
```
06-08 11:20:20.592 7599-21100/com.myapp D/com.myapp/Application.java:241: CBLReplicationExecutor-https://myapp.com/bb-06007556-814d-4ffd-ad4e-9de6c34d2cf7/-push-87d88 ReplicationStartedEvent{}
06-08 11:20:21.406 7599-21151/com.myapp W/RemoteRequest: RemoteRequest{POST, https://myapp.com/bb-06007556-814d-4ffd-ad4e-9de6c34d2cf7/_revs_diff}: Got error status: ۵۰۰ for https://myapp.com/bb-06007556-814d-4ffd-ad4e-9de6c34d2cf7/_revs_diff. Reason: Internal Server Error
06-08 11:20:23.319 7599-21188/com.myapp W/ChangeTracker: ChangeTracker{https://myapp.com/bb-06007556-814d-4ffd-ad4e-9de6c34d2cf7/, OneShot, @a9516dc}: Change tracker got error ۵۰۰
06-08 11:20:23.319 7599-21101/com.myapp W/Sync: Change tracker stopped during continuous replication
```

**Comment by hideki** [comment]
Hi @mtrakal,
Thank you for verifying the fix and also another report.

From the log message you provided, at least error codes are translated to Persian. But I am not sure this error could be caused by CBL Android or something else. If you can, please check CouchDB log file.

I filed new ticket for error code translated issue for log message.
https://github.com/couchbase/couchbase-lite-java-core/issues/1260

**Comment by hideki** [comment]
As CBL uses `String.format(...)` in many places, any  codes that calls `String.format(...)` could make variety of problems.

**Comment by hideki** [comment]
By using Genymotion Emulator, I could reproduce the issue of `maps_١`

**Comment by hideki** [comment]
Hi @mtrakal,

I also fixed all potential problems that could cause Persian language issue. Could you please test latest build from master branch?
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-738/

Thanks!

**Comment by mtrakal** [comment]
Everything looks work like a charm in our app with `0.0.0-738` version :). Sync, new revisions, ... :+1: 

I tried to switch between langs Persian/English and still stable and without errors in logcat. Looks really great

Thanks :)

**Comment by hideki** [comment]
Hi @mtrakal,
Thank you very much for verifying the fix and all your contributions to the product.
