### ISSUE TITLE
[CouchDB 1.6.1] ver. 1.2.1 has Exception uploading multipart request org.apache.http.client.ClientProtocolException

### ISSUE THREAD

**Issue by agapaymarlo** [couchbase/couchbase-lite-android#884]
hi, just want to ask if you encountered also this issue on 1.2.1? it always occur on saving doc with attachment, and sync to web couchdb. it tried to fix or find ways to solve it, but i found no luck.

**Comment by hideki** [comment]
Hi @agapaymarlo,
Could you please provide more detailed information? Stacktrace, CouchDB version, etc..

**Comment by agapaymarlo** [comment]
sorry for late reply..
- CouchDB ver 1.5
- Couch lite ver 1.2.1

 E/RemoteRequest: RemoteRequest{PUT, http://<ip here>/thirteen/9c41acd1-22c4-4d29-96bb-336ebec30374?new_edits=false}: executeRequest() Exception: org.apache.http.client.ClientProtocolException.  url: http://<ip here>/thirteen/9c41acd1-22c4-4d29-96bb-336ebec30374?new_edits=false


and then after three times... i got this 

 E/Sync: Exception uploading multipart request
       org.apache.http.client.ClientProtocolException
                                                                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:562)
                                                                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
                                                                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
                                                                at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:174)
                                                                at com.couchbase.lite.support.RemoteMultipartRequest.run(RemoteMultipartRequest.java:48)
                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                             Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
                                                                at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:426)
                                                                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
                                                                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492) 
                                                                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470) 
                                                                at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:174) 
                                                                at com.couchbase.lite.support.RemoteMultipartRequest.run(RemoteMultipartRequest.java:48) 
                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                at java.lang.Thread.run(Thread.java:818) 
05-30 13:14:40.430 31404-31472/com.example.a13lucky E/Sync: PusherInternal{http://<ip here>/thirteen, push, 55a1b}: Progress: set error = org.apache.http.client.ClientProtocolException


sorry im new at this..

**Comment by hideki** [comment]
@agapaymarlo 

We switched to use OkHttp from HttpClient from 1.3.  This issue could be fixed with master branch.

Could you please try to test with the build from master branch?
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/

**Comment by hideki** [comment]
I will close this ticket. If you are still encountering this issue, please reopen.

**Comment by iCRG** [comment]
Hi @hideki,

I think bug still there in v1.3.0-12, here is logs
https://friendpaste.com/4QukUWwshJrm5inW8A63kM

Use Cases:
1) When i create document with attachment
2) For update exiting document also

Please let me know if you need any information

Thanks
Prasanna

**Comment by hideki** [comment]
Hi @iCRG,

Could you please provide followings:
1. sync_gateway version
2. where did you deploy sync_gateway. Please confirm your sync_gateway is accessible form Android phone's browser (http://<ip>:<port>/<dbname>).
3. Is push replication is continuous mode?
4. Attachment size and how many attachments each doc have?
5. How did you update document? only document or also update attachment?

If you could write really simple sample app to reproduce this issue, it is really appreciated. 

Thanks!
Hideki

**Comment by iCRG** [comment]
Hi @hideki,

**1. sync_gateway version**
    We are not using any sync_gateway, we are using CouchDB with v1.6.1

**2. where did you deploy sync_gateway. Please confirm your sync_gateway is accessible form Android phone's browser (http://:/).**

We are using CouchDB with v1.6.1, I am testing using local server

**3. Is push replication is continuous mode?**
Yes, We are you using continuous mode replication for both pull and push
 ```
URL syncUrl;
        try {
            syncUrl = new URL(targetUrl);
        } catch (MalformedURLException e) {
            throw new RuntimeException(e);
        }
        pullReplication = database.createPullReplication(syncUrl);
        pullReplication.setContinuous(true);

        Replication pushReplication = database.createPushReplication(syncUrl);
        pushReplication.setContinuous(true);
```

**4. Attachment size and how many attachments each doc have?**
       Each attachment size it would be 280KB, it may be more also assume for now at least 12 attachments

**5. How did you update document? only document or also update attachment?**
       Yes, I am updating document along with attachments, Let me give some sample example here.

This code is for create new ticket

> https://friendpaste.com/5XWnjp88yEMbz48EjyobFU

Update exiting document, its almost like create new document only

> https://friendpaste.com/5XWnjp88yEMbz48EjzOzwT

Please let me know it you any clarification.

Thanks
Prasanna

**Comment by hideki** [comment]
CouchDB: Connection hangs on document update for multipart/related and transfer encoding chunked request
https://issues.apache.org/jira/browse/COUCHDB-2295

As described in the ticket, CouchDB does not support chunked transfer with multipart/related. So need to specify the file size.
