### ISSUE TITLE
Exception inserting revisions in bulk

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#889]
Hi - I just got the exception below during an update:
```
E/Router: com.couchbase.lite.router.Router$4@11a56e39: Exception inserting revisions in bulk
  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.couchbase.lite.internal.RevisionInternal.getDocID()' on a null object reference
      at com.couchbase.lite.router.Router$4.run(Router.java:1328)
      at com.couchbase.lite.store.SQLiteStore.runInTransaction(SQLiteStore.java:705)
      at com.couchbase.lite.router.Router.do_POST_Document_bulk_docs(Router.java:1286)
      at java.lang.reflect.Method.invoke(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:372)
      at com.couchbase.lite.router.Router.start(Router.java:555)
      at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
```
Looks like my app got a 409 response from the rest api.

Using version 0.0.0-710

**Comment by hideki** [comment]
@npomfret, Do you still observe this issue?

**Comment by npomfret** [comment]
I haven't seen it in a while

**Comment by hideki** [comment]
I will close this ticket. If you observe this issue again, please reopen the ticket. Thanks!
