### ISSUE TITLE
NPE when doc saved

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#901]
Using v0.0.0-710:

Saw this when saving a doc:

```
E/Router: com.couchbase.lite.router.Router$4@528f7e58: Exception inserting revisions in bulk
  java.lang.NullPointerException
      at com.couchbase.lite.router.Router$4.run(Router.java:1328)
      at com.couchbase.lite.store.SQLiteStore.runInTransaction(SQLiteStore.java:705)
      at com.couchbase.lite.router.Router.do_POST_Document_bulk_docs(Router.java:1286)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:525)
      at com.couchbase.lite.router.Router.start(Router.java:555)
      at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
      at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
      at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
      at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
      at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
      at java.lang.Thread.run(Thread.java:841)
```

Something here:

![screen shot 2016-06-12 at 09 52 39](https://cloud.githubusercontent.com/assets/5489469/15990174/7094a7ee-3083-11e6-93c6-2eda839d0322.png)

**Comment by hideki** [comment]
It could be `rev` is `null` in case of error scenario. I think it should use `docID` for 'id' field.
