### ISSUE TITLE
Forest Init replication show error in logcat

### ISSUE THREAD

**Issue by mtrakal** [couchbase/couchbase-lite-android#908]
Testing https://github.com/couchbase/couchbase-lite-android/issues/907#issuecomment-226263628 with latest forest
```
compile 'com.couchbase.lite:couchbase-lite-android:1.2.1'
compile 'com.couchbase.lite:couchbase-lite-android-forestdb:0.0.0-610'
```

It doesn't crash, just log in console:

init replication or record create
```
06-16 08:12:29.933 3028-3581/com.myapp E/Query: Exception caught in runAsyncInternal
 com.couchbase.lite.CouchbaseLiteException: ForestException{domain=2, code=-39}, Status: -39 (HTTP 500 Internal error)
     at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:283)
     at com.couchbase.lite.View.updateIndexes(View.java:321)
     at com.couchbase.lite.View.updateIndex(View.java:294)
     at com.couchbase.lite.Database.queryViewNamed(Database.java:2057)
     at com.couchbase.lite.Query$2.run(Query.java:483)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
     at java.lang.Thread.run(Thread.java:761)
  Caused by: ForestException{domain=2, code=-39}
     at com.couchbase.cbforest.Indexer.iterateDocuments(Native Method)
     at com.couchbase.cbforest.Indexer.iterateDocuments(Indexer.java:18)
     at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:250)
     at com.couchbase.lite.View.updateIndexes(View.java:321) 
     at com.couchbase.lite.View.updateIndex(View.java:294) 
     at com.couchbase.lite.Database.queryViewNamed(Database.java:2057) 
     at com.couchbase.lite.Query$2.run(Query.java:483) 
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
     at java.lang.Thread.run(Thread.java:761) 
```

**Comment by mtrakal** [comment]
```
06-16 08:20:12.325 3028-3650/com.myapp E/Database: Error in loadRevisionBody()
                                                                          ForestException{domain=2, code=-39}
                                                                              at com.couchbase.cbforest.Document.init(Native Method)
                                                                              at com.couchbase.cbforest.Document.<init>(Document.java:87)
                                                                              at com.couchbase.cbforest.Database.getDocument(Database.java:36)
                                                                              at com.couchbase.lite.store.ForestDBStore.loadRevisionBody(ForestDBStore.java:327)
                                                                              at com.couchbase.lite.Database.loadRevisionBody(Database.java:1345)
                                                                              at com.couchbase.lite.replicator.PusherInternal$3.onCompletion(PusherInternal.java:380)
                                                                              at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:206)
                                                                              at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:223)
                                                                              at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:297)
                                                                              at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:218)
                                                                              at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:98)
                                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)                                                                              
```

**Comment by hideki** [comment]
Hi @mtrakal,

Error code: `-39` indicates multiple threads access forestdb concurrently. 
```
/**
 * DB handle is being used by another thread. Forestdb handles must not be
 * shared among multiple threads.
 */
int FDB_RESULT_HANDLE_BUSY = -39;
```

I see you are using different version between android and forestdb. Could you please re-test with using latest master build?

Thanks!

**Comment by hideki** [comment]
Hi @mtrakal,

If you have time, could you please test `0.0.0-753`? I just would like to verify if this issue still exists with latest master branch.
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-753/
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android-forestdb/0.0.0-753/

Thanks,

**Comment by hideki** [comment]
This issue is duplicated with https://github.com/couchbase/couchbase-lite-android/issues/909. I will close this ticket. We should track with #909
