### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by lukasw44** [couchbase/couchbase-lite-android#911]
Hi

I use couchbase lite v 1.2.1 and forestdb i start my replicatin but i do not touch couchbse broadcast receiver so i do not know whats gooing now ...

`06-23 03:17:27.279 10940-11009/com.xxx.kkkkkkkk E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb99959c0
06-23 03:17:27.308 10940-10940/com.elt.passsystem E/ActivityThread: Activity com.xx.kkkkkkkkkk.activity.synchronization.DocumentActivity has leaked IntentReceiver com.couchbase.lite.android.AndroidNetworkReachabilityManager$ConnectivityBroadcastReceiver@2440ae9 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                    android.app.IntentReceiverLeaked: Activity com.xxx.kkkkkk.activity.synchronization.DocumentActivity has leaked IntentReceiver com.couchbase.lite.android.AndroidNetworkReachabilityManager$ConnectivityBroadcastReceiver@2440ae9 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:918)
                                                                        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:719)
                                                                        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1172)
                                                                        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1152)
                                                                        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1146)
                                                                        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:554)
                                                                        at com.couchbase.lite.android.AndroidNetworkReachabilityManager.startListening(AndroidNetworkReachabilityManager.java:29)
                                                                        at com.couchbase.lite.NetworkReachabilityManager.addNetworkReachabilityListener(NetworkReachabilityManager.java:26)
                                                                        at com.couchbase.lite.replicator.ReplicationInternal.startNetworkReachabilityManager(ReplicationInternal.java:329)
                                                                        at com.couchbase.lite.replicator.ReplicationInternal.start(ReplicationInternal.java:264)
                                                                        at com.couchbase.lite.replicator.ReplicationInternal$13.doIt(ReplicationInternal.java:1227)
                                                                        at com.couchbase.lite.replicator.ReplicationInternal$13.doIt(ReplicationInternal.java:1223)
                                                                        at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:135)
                                                                        at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:133)
                                                                        at com.github.oxo42.stateless4j.StateRepresentation.executeEntryActions(StateRepresentation.java:118)
                                                                        at com.github.oxo42.stateless4j.StateRepresentation.enter(StateRepresentation.java:97)
                                                                        at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:199)
                                                                        at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:126)
                                                                        at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:209)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                        at java.lang.Thread.run(Thread.java:818)`

**Comment by hideki** [comment]
Hi @lukasw44,
It seems `ConnectivityBroadcastReceiver` is not unregistered in couchbase lite code. We will look into it.

**Comment by lukasw44** [comment]
I think i have got that error when i try login using the same user on two devices so maybe thats may be problem.

**Comment by lukasw44** [comment]
Is there any problem with reproduce this bug ?
