### ISSUE TITLE
Router unable to route request to do_POST_DesignDocument

### ISSUE THREAD

**Issue by israelidanny** [couchbase/couchbase-lite-android#924]
I'm trying to do something that works great on iOS, but fails on Android with:
```
{ 
  error: 'not_found',
  status: 404,
  reason: 'Router unable to route request to do_POST_DesignDocumentjava.lang.reflect.InvocationTargetException' 
}
```

I tried both version `1.2.1` and `0.0.0-766`

What I'm trying to do is POST to `${dbURL}/_design/metaderm/_view/by_type?include_docs=true` to load a certain view. This same exact view with the same exact documents works just fine in an identical app on iOS.

Any clue on why this might be happening? 

@urbanvikingr

**Comment by hideki** [comment]
Hi @israelidanny,
I guess `Exception` is thrown in the handler. Could you please capture log message from logcat?
Thanks!

**Comment by israelidanny** [comment]
logcat doesn't return something too different:
```
06-30 19:42:23.499  2073  2285 D InitAlarmsService: Clearing and rescheduling alarms.
06-30 19:42:46.682  1521  1532 I MediaFocusControl:  AudioFocus  abandonAudioFocus() from android.media.AudioManager@7aeb53dcom.android.music.MediaPlaybackService$3@ac9f132
^@06-30 19:42:55.999  2238  2238 W ViewRootImpl: Cancelling event due to no window focus: MotionEvent { action=ACTION_CANCEL, actionButton=0, id[0]=0, x[0]=151.11694, y[0]=1570.7227, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=80190, downTime=27291, deviceId=0, source=0x1002 }
06-30 19:42:55.999  2238  2238 W ViewRootImpl: Cancelling event due to no window focus: MotionEvent { action=ACTION_CANCEL, actionButton=0, id[0]=0, x[0]=151.11694, y[0]=1570.7227, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=80190, downTime=27291, deviceId=0, source=0x1002 }
06-30 19:42:55.999  2238  2238 W ViewRootImpl: Cancelling event due to no window focus: MotionEvent { action=ACTION_CANCEL, actionButton=0, id[0]=0, x[0]=151.11694, y[0]=1570.7227, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=80190, downTime=27291, deviceId=0, source=0x1002 }
06-30 19:42:55.999  2238  2238 W ViewRootImpl: Cancelling event due to no window focus: MotionEvent { action=ACTION_CANCEL, actionButton=0, id[0]=0, x[0]=151.11694, y[0]=1570.7227, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=80190, downTime=27291, deviceId=0, source=0x1002 }
06-30 19:42:56.150  2329  2339 W art     : Suspending all threads took: 10.571ms
06-30 19:42:56.153  2329  2360 W Router  : Router unable to route request to do_POST_DesignDocument
06-30 19:42:56.153  2329  2360 W Router  : java.lang.reflect.InvocationTargetException
06-30 19:42:56.153  2329  2360 W Router  : 	at java.lang.reflect.Method.invoke(Native Method)
06-30 19:42:56.153  2329  2360 W Router  : 	at com.couchbase.lite.router.Router.start(Router.java:570)
06-30 19:42:56.153  2329  2360 W Router  : 	at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
06-30 19:42:56.153  2329  2360 W Router  : 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
06-30 19:42:56.153  2329  2360 W Router  : 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
06-30 19:42:56.153  2329  2360 W Router  : 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
06-30 19:42:56.153  2329  2360 W Router  : 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
06-30 19:42:56.153  2329  2360 W Router  : 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
06-30 19:42:56.153  2329  2360 W Router  : 	at java.lang.Thread.run(Thread.java:818)
06-30 19:42:56.153  2329  2360 W Router  : Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.couchbase.lite.Mapper com.couchbase.lite.ViewCompiler.compileMap(java.lang.String, java.lang.String)' on a null object reference
06-30 19:42:56.153  2329  2360 W Router  : 	at com.couchbase.lite.router.Router.compileView(Router.java:2338)
06-30 19:42:56.153  2329  2360 W Router  : 	at com.couchbase.lite.router.Router.queryDesignDoc(Router.java:2380)
06-30 19:42:56.153  2329  2360 W Router  : 	at com.couchbase.lite.router.Router.do_POST_DesignDocument(Router.java:2443)
06-30 19:42:56.153  2329  2360 W Router  : 	... 9 more
06-30 19:42:56.153  2329  2360 W Router  : Cannot add Content-Type header because getResHeader() returned null
06-30 19:42:56.175  2329  2339 I art     : Background sticky concurrent mark sweep GC freed 4668(195KB) AllocSpace objects, 8(160KB) LOS objects, 5% free, 5MB/5MB, paused 11.576ms total 35.531ms
06-30 19:42:56.180  2329  2350 I ReactNativeJS: 'res', { error: 'not_found',
06-30 19:42:56.180  2329  2350 I ReactNativeJS:   status: 404,
06-30 19:42:56.180  2329  2350 I ReactNativeJS:   reason: 'Router unable to route request to do_POST_DesignDocumentjava.lang.reflect.InvocationTargetException' }
```

This is on `D` level of verbosity.

**Comment by hideki** [comment]
Did you register view? or view name does not match? can you check?
```
06-30 19:42:56.153  2329  2360 W Router  : Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.couchbase.lite.Mapper com.couchbase.lite.ViewCompiler.compileMap(java.lang.String, java.lang.String)' on a null object reference
06-30 19:42:56.153  2329  2360 W Router  :  at com.couchbase.lite.router.Router.compileView(Router.java:2338)
06-30 19:42:56.153  2329  2360 W Router  :  at com.couchbase.lite.router.Router.queryDesignDoc(Router.java:2380)
06-30 19:42:56.153  2329  2360 W Router  :  at com.couchbase.lite.router.Router.do_POST_DesignDocument(Router.java:2443)
```

**Comment by israelidanny** [comment]
I created the view and got 201 status on the PUT request.

**Comment by hideki** [comment]
I believe NPE happens by  `View.getCompiler() return null`. I believe JavaScript compiler is not registered. How did you setup CBL with React-Native?
```
        Mapper mapBlock = View.getCompiler().compileMap(mapSource, language);
        if (mapBlock == null) {
            Log.w(TAG, "View %s has unknown map function: %s", viewName, mapSource);
            return null;
        }
```

**Comment by israelidanny** [comment]
I didn't have a registered compiler indeed. I added now, as inspired from your react native component:
```
    private void launchCouchbaseLite() {
        try {
            View.setCompiler(new JavaScriptViewCompiler());
            Database.setFilterCompiler(new JavaScriptReplicationFilterCompiler());
            Manager manager = new Manager(new AndroidContext(this), Manager.DEFAULT_OPTIONS);
            LiteListener listener = new LiteListener(manager, 5800, null);
            int boundPort = listener.getListenPort();

            Thread thread = new Thread(listener);
            thread.start();

            String url = String.format(
                "http://localhost:%d/",
                boundPort
            );

            Log.i("ReactNativeJS", "CBLite init completed successfully with: " + url);
        } catch (final Exception e) {
            Log.e("ReactNativeJS", "Couchbase init failed", e);
        }
    }
```

Still no luck getting the view to work.

This is the error logcat now:
```
06-30 21:16:42.993  1190  1757 D NuPlayerDriver: reset(0xf6159f00)
06-30 21:16:42.993  1190  1757 D NuPlayerDriver: notifyListener_l(0xf6159f00), (8, 0, 0)
06-30 21:16:42.999  1190  2780 D NuPlayerDriver: notifyResetComplete(0xf6159f00)
06-30 21:16:43.002  1190  1757 D NuPlayerDriver: reset(0xf615a260)
06-30 21:16:43.002  1190  1757 D NuPlayerDriver: notifyListener_l(0xf615a260), (8, 0, 0)
06-30 21:16:43.015  1190  2782 D NuPlayerDriver: notifyResetComplete(0xf615a260)
06-30 21:16:43.015  1190  1757 E CameraService: disconnect: Disconnect called on already disconnected client for device 0
06-30 21:16:44.244  2730  2761 E View    : Error emitting
06-30 21:16:44.244  2730  2761 E View    : com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class org.mozilla.javascript.Undefined and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )
06-30 21:16:44.244  2730  2761 E View    : 	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:59)
06-30 21:16:44.244  2730  2761 E View    : 	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:26)
06-30 21:16:44.244  2730  2761 E View    : 	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
06-30 21:16:44.244  2730  2761 E View    : 	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3383)
06-30 21:16:44.244  2730  2761 E View    : 	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2777)
06-30 21:16:44.244  2730  2761 E View    : 	at com.couchbase.lite.store.SQLiteViewStore.emit(SQLiteViewStore.java:588)
06-30 21:16:44.244  2730  2761 E View    : 	at com.couchbase.lite.store.SQLiteViewStore$2.emit(SQLiteViewStore.java:372)
06-30 21:16:44.244  2730  2761 E View    : 	at com.couchbase.lite.javascript.scopes.MapGlobalScope.emit(MapGlobalScope.java:39)
06-30 21:16:44.244  2730  2761 E View    : 	at java.lang.reflect.Method.invoke(Native Method)
06-30 21:16:44.244  2730  2761 E View    : 	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
06-30 21:16:44.244  2730  2761 E View    : 	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:476)
06-30 21:16:44.244  2730  2761 E View    : 	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1701)
06-30 21:16:44.244  2730  2761 E View    : 	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
06-30 21:16:44.244  2730  2761 E View    : 	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
06-30 21:16:44.244  2730  2761 E View    : 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
06-30 21:16:44.244  2730  2761 E View    : 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
06-30 21:16:44.244  2730  2761 E View    : 	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:162)
06-30 21:16:44.244  2730  2761 E View    : 	at com.couchbase.lite.javascript.ViewMapBlockRhino.map(ViewMapBlockRhino.java:66)
06-30 21:16:44.244  2730  2761 E View    : 	at com.couchbase.lite.store.SQLiteViewStore.updateIndexes(SQLiteViewStore.java:545)
06-30 21:16:44.244  2730  2761 E View    : 	at com.couchbase.lite.View.updateIndexes(View.java:321)
06-30 21:16:44.244  2730  2761 E View    : 	at com.couchbase.lite.View.updateIndex(View.java:294)
06-30 21:16:44.244  2730  2761 E View    : 	at com.couchbase.lite.router.Router.queryDesignDoc(Router.java:2401)
06-30 21:16:44.244  2730  2761 E View    : 	at com.couchbase.lite.router.Router.do_POST_DesignDocument(Router.java:2443)
06-30 21:16:44.244  2730  2761 E View    : 	at java.lang.reflect.Method.invoke(Native Method)
06-30 21:16:44.244  2730  2761 E View    : 	at com.couchbase.lite.router.Router.start(Router.java:570)
06-30 21:16:44.244  2730  2761 E View    : 	at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
06-30 21:16:44.244  2730  2761 E View    : 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
06-30 21:16:44.244  2730  2761 E View    : 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
06-30 21:16:44.244  2730  2761 E View    : 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
06-30 21:16:44.244  2730  2761 E View    : 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
06-30 21:16:44.244  2730  2761 E View    : 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
06-30 21:16:44.244  2730  2761 E View    : 	at java.lang.Thread.run(Thread.java:818)
06-30 21:16:44.251  2730  2761 E View    : Error emitting
06-30 21:16:44.251  2730  2761 E View    : com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class org.mozilla.javascript.Undefined and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )
06-30 21:16:44.251  2730  2761 E View    : 	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:59)
06-30 21:16:44.251  2730  2761 E View    : 	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:26)
06-30 21:16:44.251  2730  2761 E View    : 	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
06-30 21:16:44.251  2730  2761 E View    : 	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3383)
06-30 21:16:44.251  2730  2761 E View    : 	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2777)
06-30 21:16:44.251  2730  2761 E View    : 	at com.couchbase.lite.store.SQLiteViewStore.emit(SQLiteViewStore.java:588)
06-30 21:16:44.251  2730  2761 E View    : 	at com.couchbase.lite.store.SQLiteViewStore$2.emit(SQLiteViewStore.java:372)
06-30 21:16:44.251  2730  2761 E View    : 	at com.couchbase.lite.javascript.scopes.MapGlobalScope.emit(MapGlobalScope.java:39)
06-30 21:16:44.251  2730  2761 E View    : 	at java.lang.reflect.Method.invoke(Native Method)
06-30 21:16:44.251  2730  2761 E View    : 	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
06-30 21:16:44.251  2730  2761 E View    : 	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:476)
06-30 21:16:44.251  2730  2761 E View    : 	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1701)
06-30 21:16:44.251  2730  2761 E View    : 	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
06-30 21:16:44.251  2730  2761 E View    : 	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
06-30 21:16:44.251  2730  2761 E View    : 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
06-30 21:16:44.251  2730  2761 E View    : 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
06-30 21:16:44.251  2730  2761 E View    : 	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:162)
06-30 21:16:44.251  2730  2761 E View    : 	at com.couchbase.lite.javascript.ViewMapBlockRhino.map(ViewMapBlockRhino.java:66)
06-30 21:16:44.251  2730  2761 E View    : 	at com.couchbase.lite.store.SQLiteViewStore.updateIndexes(SQLiteViewStore.java:545)
06-30 21:16:44.251  2730  2761 E View    : 	at com.couchbase.lite.View.updateIndexes(View.java:321)
06-30 21:16:44.251  2730  2761 E View    : 	at com.couchbase.lite.View.updateIndex(View.java:294)
06-30 21:16:44.251  2730  2761 E View    : 	at com.couchbase.lite.router.Router.queryDesignDoc(Router.java:2401)
06-30 21:16:44.251  2730  2761 E View    : 	at com.couchbase.lite.router.Router.do_POST_DesignDocument(Router.java:2443)
06-30 21:16:44.251  2730  2761 E View    : 	at java.lang.reflect.Method.invoke(Native Method)
06-30 21:16:44.251  2730  2761 E View    : 	at com.couchbase.lite.router.Router.start(Router.java:570)
06-30 21:16:44.251  2730  2761 E View    : 	at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
06-30 21:16:44.251  2730  2761 E View    : 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
06-30 21:16:44.251  2730  2761 E View    : 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
06-30 21:16:44.251  2730  2761 E View    : 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
06-30 21:16:44.251  2730  2761 E View    : 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
06-30 21:16:44.251  2730  2761 E View    : 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
06-30 21:16:44.251  2730  2761 E View    : 	at java.lang.Thread.run(Thread.java:818)
06-30 21:16:44.266  2730  2761 W Router  : Cannot add Content-Type header because getResHeader() returned null
06-30 21:16:45.361  2730  2762 W Router  : Cannot add Content-Type header because getResHeader() returned null
06-30 21:16:45.814  2730  2740 I art     : Background sticky concurrent mark sweep GC freed 17420(891KB) AllocSpace objects, 17(436KB) LOS objects, 12% free, 8MB/9MB, paused 8.910ms total 29.567ms
06-30 21:16:46.514  2730  2761 W Router  : Cannot add Content-Type header because getResHeader() returned null
06-30 21:17:11.752  2730  2762 W Router  : Cannot add Content-Type header because getResHeader() returned null
06-30 21:17:12.848  2730  2761 W Router  : Cannot add Content-Type header because getResHeader() returned null
```

**Comment by israelidanny** [comment]
This is my code for creating the view (it's identical to what I use on ios and works great there):
```javascript
const url = `${dbURL}/_design/metaderm`

  return fetch(url, {
    method: 'PUT',
    headers,
    body: JSON.stringify({
      'language': 'javascript',
      'views': {
        'by_type' : {
          'map' : 'function(doc) { if(doc.type){ emit(doc.type) } }'
        }
      }
    })
  })
```

And I'm fetching the docs by calling:
`${dbURL}/_design/metaderm/_view/by_type?include_docs=true`

And passing this to it:
```
    {
      keys: [ 'sometype' ]
    }
```

**Comment by hideki** [comment]
above error is caused by emitting `undfined`. In you JavaScript mapper, can you check `doc.type` is not `undfined`?

**Comment by israelidanny** [comment]
Yes, I can confirm that none of the documents have type undefined. All documents we save have type. Also please note our code:
`if(doc.type){ emit(doc.type) }`

It would be impossible for undefined to be emitted due to the if. 

This exact code works on ios.

Any clue to what else it could be?

**Comment by hideki** [comment]
CBL java expect two parameters for `emit` method. First one is key, and second one is value.
I believe you emit only key. So you could give `null` to second parameter.

**Comment by israelidanny** [comment]
Thanks, it works! Would this 2 parameter call be cross-compatible with ios?

I was hoping for this part of the app to be shared between the platforms since it's just simple REST calls.

**Comment by hideki** [comment]
I believe iOS should work with two parameters.
