### ISSUE TITLE
NPE and RemoteRequestCompletionBlock in 1.3.0-12

### ISSUE THREAD

**Issue by mtrakal** [couchbase/couchbase-lite-android#933]
Android API 16
When edit a lot of records in transaction (10000).

In our code we run a transaction. We update one entry in every Document.

Maybe related to: https://github.com/couchbase/couchbase-lite-android/issues/909
```
07-06 14:48:23.051 30213-20680/com.myapp D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 276ms
07-06 14:48:25.624 30213-30217/com.myapp D/dalvikvm: GC_CONCURRENT freed 1847K, 5% free 58314K/60871K, paused 31ms+76ms, total 1875ms
07-06 14:48:25.624 30213-20679/com.myapp D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 1816ms
07-06 14:48:25.624 30213-30219/com.myapp D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 1396ms
07-06 14:48:25.624 30213-30265/com.myapp D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 1818ms
07-06 14:48:25.624 30213-20680/com.myapp D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 1551ms
07-06 14:48:27.115 30213-20679/com.myapp D/dalvikvm: GC_FOR_ALLOC freed 1834K, 5% free 58443K/60999K, paused 477ms, total 477ms
07-06 14:48:28.106 30213-20863/com.myapp D/dalvikvm: GC_FOR_ALLOC freed 1647K, 4% free 58757K/61127K, paused 468ms, total 469ms
07-06 14:48:28.206 30213-20863/com.myapp E/RemoteRequest: RemoteRequestCompletionBlock throw Exception
             java.lang.NullPointerException
                 at com.couchbase.lite.Database.getRevisionHistoryDictStartingFromAnyAncestor(Database.java:1478)
                 at com.couchbase.lite.replicator.PusherInternal$5.onCompletion(PusherInternal.java:462)
                 at com.couchbase.lite.replicator.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:342)
                 at com.couchbase.lite.replicator.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:301)
                 at com.couchbase.lite.replicator.RemoteRequest.respondWithResult(RemoteRequest.java:300)
                 at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:288)
                 at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
                 at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
                 at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                 at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                 at java.lang.Thread.run(Thread.java:856)
07-06 14:48:28.276 30213-30265/com.myapp E/Database: Error in saveForest()
            com.couchbase.cbforest.ForestException: Forestdb Handle is being used by another thread
                at com.couchbase.cbforest.Document.save(Native Method)
                at com.couchbase.cbforest.Document.save(Document.java:87)
                at com.couchbase.lite.store.ForestDBStore.saveForest(ForestDBStore.java:1270)
                at com.couchbase.lite.store.ForestDBStore.add(ForestDBStore.java:912)
                at com.couchbase.lite.Database.put(Database.java:1840)
                at com.couchbase.lite.Database.putRevision(Database.java:1790)
                at com.couchbase.lite.Database.putRevision(Database.java:1781)
                at com.couchbase.lite.Document.putProperties(Document.java:523)
                at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:118)
                at com.couchbase.lite.Document.update(Document.java:379)
                at com.yablohn.internal.YablohnBaseDao.createOrUpdateDocument(YablohnBaseDao.java:134)
                at com.yablohn.internal.YablohnBaseDao.createOrUpdateDocument(YablohnBaseDao.java:115)
                at com.myapp.v3.db.BaseCustomDao.createOrUpdateDocument(BaseCustomDao.java:36)
                at com.myapp.v3.misc.RecordsModifyTask$1.run(RecordsModifyTask.java:94)
                at com.couchbase.lite.store.ForestDBStore.runInTransaction(ForestDBStore.java:297)
                at com.couchbase.lite.Database.runInTransaction(Database.java:565)
                at com.myapp.v3.misc.RecordsModifyTask.doInBackground(RecordsModifyTask.java:45)
                at com.myapp.v3.misc.RecordsModifyTask.doInBackground(RecordsModifyTask.java:22)
                at android.os.AsyncTask$2.call(AsyncTask.java:287)
                at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                at java.lang.Thread.run(Thread.java:856)
07-06 14:48:28.407 30213-30265/com.myapp E/Database: ForestDB Error: getDocument(docID, false) docID=[Record_d330496d-da92-4f66-a8db-a270c9dc4a98]
            com.couchbase.cbforest.ForestException: Forestdb Handle is being used by another thread
                at com.couchbase.cbforest.Document.init(Native Method)
                at com.couchbase.cbforest.Document.<init>(Document.java:97)
                at com.couchbase.cbforest.Database.getDocument(Database.java:46)
                at com.couchbase.lite.store.ForestDBStore.add(ForestDBStore.java:828)
                at com.couchbase.lite.Database.put(Database.java:1840)
                at com.couchbase.lite.Database.putRevision(Database.java:1790)
                at com.couchbase.lite.Database.putRevision(Database.java:1781)
                at com.couchbase.lite.Document.putProperties(Document.java:523)
                at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:118)
                at com.couchbase.lite.Document.update(Document.java:379)
                at com.yablohn.internal.YablohnBaseDao.createOrUpdateDocument(YablohnBaseDao.java:134)
                at com.yablohn.internal.YablohnBaseDao.createOrUpdateDocument(YablohnBaseDao.java:115)
                at com.myapp.v3.db.BaseCustomDao.createOrUpdateDocument(BaseCustomDao.java:36)
                at com.myapp.v3.misc.RecordsModifyTask$1.run(RecordsModifyTask.java:94)
                at com.couchbase.lite.store.ForestDBStore.runInTransaction(ForestDBStore.java:297)
                at com.couchbase.lite.Database.runInTransaction(Database.java:565)
                at com.myapp.v3.misc.RecordsModifyTask.doInBackground(RecordsModifyTask.java:45)
                at com.myapp.v3.misc.RecordsModifyTask.doInBackground(RecordsModifyTask.java:22)
                at android.os.AsyncTask$2.call(AsyncTask.java:287)
                at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                at java.lang.Thread.run(Thread.java:856)
07-06 14:48:28.447 30213-30265/com.myapp E/Database: java.lang.NullPointerException
            java.lang.NullPointerException
                at com.myapp.v3.misc.RecordsModifyTask$1.run(RecordsModifyTask.java:74)
                at com.couchbase.lite.store.ForestDBStore.runInTransaction(ForestDBStore.java:297)
                at com.couchbase.lite.Database.runInTransaction(Database.java:565)
                at com.myapp.v3.misc.RecordsModifyTask.doInBackground(RecordsModifyTask.java:45)
                at com.myapp.v3.misc.RecordsModifyTask.doInBackground(RecordsModifyTask.java:22)
                at android.os.AsyncTask$2.call(AsyncTask.java:287)
                at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                at java.lang.Thread.run(Thread.java:856)
07-06 14:48:28.477 30213-30265/com.myapp W/dalvikvm: threadid=13: thread exiting with uncaught exception (group=0x4103a2a0)
07-06 14:48:28.567 30213-20861/com.myapp E/RemoteRequest: RemoteRequestCompletionBlock throw Exception
           java.lang.NullPointerException
               at com.couchbase.lite.Database.getRevisionHistoryDictStartingFromAnyAncestor(Database.java:1478)
               at com.couchbase.lite.replicator.PusherInternal$5.onCompletion(PusherInternal.java:462)
               at com.couchbase.lite.replicator.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:342)
               at com.couchbase.lite.replicator.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:301)
               at com.couchbase.lite.replicator.RemoteRequest.respondWithResult(RemoteRequest.java:300)
               at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:288)
               at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
               at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
               at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
               at java.util.concurrent.FutureTask.run(FutureTask.java:137)
               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
               at java.lang.Thread.run(Thread.java:856)
07-06 14:48:28.577 30213-30213/com.myapp D/ProgressBar: setProgress = 0
07-06 14:48:28.577 30213-30213/com.myapp D/ProgressBar: setProgress = 0, fromUser = false
07-06 14:48:28.577 30213-30213/com.myapp D/ProgressBar: mProgress = 0mIndeterminate = false, mMin = 0, mMax = 0
07-06 14:48:28.587 30213-30213/com.myapp D/ProgressBar: setProgress = 0
07-06 14:48:28.587 30213-30213/com.myapp D/ProgressBar: setProgress = 0, fromUser = false
07-06 14:48:28.587 30213-30213/com.myapp D/ProgressBar: mProgress = 0mIndeterminate = false, mMin = 0, mMax = 0
07-06 14:48:29.418 30213-30282/com.myapp D/dalvikvm: GC_FOR_ALLOC freed 3388K, 7% free 57309K/61447K, paused 491ms, total 499ms
07-06 14:48:30.499 30213-30217/com.myapp D/dalvikvm: GC_CONCURRENT freed 1819K, 7% free 57537K/61447K, paused 17ms+30ms, total 553ms
07-06 14:48:30.499 30213-30282/com.myapp D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 493ms
07-06 14:48:30.499 30213-30219/com.myapp D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 264ms
07-06 14:48:30.499 30213-30330/com.myapp D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 498ms
07-06 14:48:30.499 30213-20680/com.myapp D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 80ms
07-06 14:48:30.719 30213-30265/com.myapp E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
          java.lang.RuntimeException: An error occured while executing doInBackground()
              at android.os.AsyncTask$3.done(AsyncTask.java:299)
              at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
              at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
              at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
              at java.util.concurrent.FutureTask.run(FutureTask.java:137)
              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
              at java.lang.Thread.run(Thread.java:856)
           Caused by: java.lang.RuntimeException: java.lang.NullPointerException
              at com.couchbase.lite.store.ForestDBStore.runInTransaction(ForestDBStore.java:301)
              at com.couchbase.lite.Database.runInTransaction(Database.java:565)
              at com.myapp.v3.misc.RecordsModifyTask.doInBackground(RecordsModifyTask.java:45)
              at com.myapp.v3.misc.RecordsModifyTask.doInBackground(RecordsModifyTask.java:22)
              at android.os.AsyncTask$2.call(AsyncTask.java:287)
              at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
              at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
              at java.lang.Thread.run(Thread.java:856) 
           Caused by: java.lang.NullPointerException
              at com.myapp.v3.misc.RecordsModifyTask$1.run(RecordsModifyTask.java:74)
              at com.couchbase.lite.store.ForestDBStore.runInTransaction(ForestDBStore.java:297)
              at com.couchbase.lite.Database.runInTransaction(Database.java:565) 
              at com.myapp.v3.misc.RecordsModifyTask.doInBackground(RecordsModifyTask.java:45) 
              at com.myapp.v3.misc.RecordsModifyTask.doInBackground(RecordsModifyTask.java:22) 
              at android.os.AsyncTask$2.call(AsyncTask.java:287) 
              at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305) 
              at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
              at java.lang.Thread.run(Thread.java:856)

```

**Comment by hideki** [comment]
Hi @mtrakal,

Thank you for another bug report.

1) In general, with the transaction, database operation is faster. So I recommend to use it. However it stores data into the memory. If your app operates a lot of records in the transaction, it could cause memory issue (out-of-memory). From your log message, it seems GC is busy. I recommend you to not process too much data in the transaction. It seems 1000 is too much.

2) I will add the null check for NPE. This NPE is caused by failing to create `new HashMap()` in the method. This is caused by out-of-memory.
```
 java.lang.NullPointerException
   at com.couchbase.lite.Database.getRevisionHistoryDictStartingFromAnyAncestor(Database.java:1478)
```

3) following error indicates there are un-covered scenario for #909 issue. Could you please explain what your app is doing? I will write unit test for this. I needs number of threads and what each thread is doing.
```
07-06 14:48:28.276 30213-30265/com.myapp E/Database: Error in saveForest()
  com.couchbase.cbforest.ForestException: Forestdb Handle is being used by another thread
    at com.couchbase.cbforest.Document.save(Native Method)
    at com.couchbase.cbforest.Document.save(Document.java:87)
    at com.couchbase.lite.store.ForestDBStore.saveForest(ForestDBStore.java:1270)
```

Thanks!

**Comment by hideki** [comment]
NOTE: `releae-prep` for adding `null` check

**Comment by hideki** [comment]
Note to self:
- first NPE could be caused by SQLite

**Comment by hideki** [comment]
Hi @mtrakal,

I guess NPE is caused by Out-Of-Memory. It seems API 16 return `null` for failing `new` instead of throwing `OutOfMemoryException`. I strongly recommend to reduce the number of processing documents in the transaction.

Also I have considered that `Forestdb Handle is being used by another thread` issue could be caused with low memory availability. 

Thanks!

**Comment by mtrakal** [comment]
Hi @hideki,

it's report from our tester, so I have not complete info what he was doing, but he edit on every document description (one column from document).

1) it was 10 000, not just 1000 :). Our tester is a "hardcore" tester, so he try on a lot of documents and on lowest supported devices. So it's really possible that it's caused by OOM.

2) thanks :)

3) In this test: 
- Create a lot of documents (10 000 user documents + about 50 maintain documents)
- edit every document in transaction.
- We have every record stored parallel in sqlite (just few columns from document and link (document id) on original document) for faster querying with indexes.
- Select all rows from sqlite and for this records (not all documents from CBL, but almost all)
- in transaction update this documents
- end transaction
