### ISSUE TITLE
do_GET_Document_all_docs NullPointerException in 1.3.0-45

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#957]
I saw the following error today.  Not sure what caused it but I think my app was added attachments to a document.

```
W/Router: Router unable to route request to do_GET_Document_all_docs
                                                    java.lang.reflect.InvocationTargetException
                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                        at com.couchbase.lite.router.Router.start(Router.java:571)
                                                        at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
                                                        at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
                                                        at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
                                                        at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
                                                        at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
                                                        at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
                                                        at java.lang.Thread.run(Thread.java:818)
                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replace(java.lang.CharSequence, java.lang.CharSequence)' on a null object reference
                                                        at com.couchbase.lite.util.TextUtils.quote(TextUtils.java:129)
                                                        at com.couchbase.lite.util.TextUtils.joinQuoted(TextUtils.java:109)
                                                        at com.couchbase.lite.util.TextUtils.joinQuotedObjects(TextUtils.java:125)
                                                        at com.couchbase.lite.store.SQLiteStore.getAllDocs(SQLiteStore.java:1144)
                                                        at com.couchbase.lite.Database.getAllDocs(Database.java:1519)
                                                        at com.couchbase.lite.router.Router.do_GET_Document_all_docs(Router.java:1183)
                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                        at com.couchbase.lite.router.Router.start(Router.java:571) 
                                                        at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141) 
                                                        at javax.servlet.http.HttpServlet.service(HttpServlet.java:802) 
                                                        at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251) 
                                                        at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176) 
                                                        at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988) 
                                                        at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223) 
                                                        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by pasin** [comment]
I think there is a bug that doesn't handle null object when trying to add quotes to a string.

Do you have the all_docs query request (parameters and all) that causes this issue?

**Comment by npomfret** [comment]
Unfortunately i don't have the exact query, but the only call my app makes to that endpoint is one that specifies `keys=[...some array]`, `include_docs=true` and `conflicts=true`. You think its possible I'm passing a `null` in as one of the keys?

**Comment by pasin** [comment]
Yes, I'm thinking that there could be null in one of the keys. CBL should be able to handle that though. While we are working on this, can you double check if it's possible to put null in the keys?

**Comment by pasin** [comment]
I could reproduce the issue when one of the keys is null (e.g. keys=["id1", null, "id2"]). I don't think null value is expected.

**Comment by npomfret** [comment]
Ok, thats likely to be it i guess. There shouldn't be nulls in my program but I dare say its buggy enough that sometimes they happen
