### ISSUE TITLE
attempt to write a readonly database

### ISSUE THREAD

**Issue by pawanchauhan05** [couchbase/couchbase-lite-android#962]
Error inserting doc_id=1 revid=1-0f058b7ad9cd099c28e2bddc995aa456 no_attachments=false deleted=false current=true json=[B@5576742
                                                                     android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
                                                                         at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                         at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:780)
                                                                         at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                         at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                         at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
                                                                         at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
                                                                         at com.couchbase.lite.android.AndroidSQLiteStorageEngine.insert(AndroidSQLiteStorageEngine.java:116)
                                                                         at com.couchbase.lite.Database.insertRevision(Database.java:3443)
                                                                         at com.couchbase.lite.Database.putRevision(Database.java:3634)
                                                                         at com.couchbase.lite.Database.putRevision(Database.java:3465)
                                                                         at com.couchbase.lite.Document.putProperties(Document.java:415)
                                                                         at com.couchbase.lite.Document.putProperties(Document.java:250)

**Comment by pasin** [comment]
@pawanchauhan05 Can you explain more about the issue that can help us understand the issue?

**Comment by pawanchauhan05** [comment]
whenever i create a document , created successfuly.
then i delete it, deleted successfuly.
but then i create document again it throw me exception mentioned above.

**Comment by pasin** [comment]
Thanks for more info. I will test the scenario.
