### ISSUE TITLE
1.3.1-16 - Replicator error: java.lang.Exception: Change tracker stopped during continuous replication.

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#986]
I noticed the following in my app when it was running in the background.  The app crashed completely just a few seconds after.

```
W/Router: Replicator error: java.lang.Exception: Change tracker stopped during continuous replication.  Repl: Replication{http://192.168.1.185:4986/sync_gateway, pull}.  Source: http://192.168.1.185:4986/sync_gateway, Target: pc_macmini_0_a29cde2d-7456-4536-94cf-6c829af7fbaf
```
I didn't see any other stack trace and no other error messages in logcat.  I was filtering log messages at the info level.

**Comment by npomfret** [comment]
Hmm, I'm not sure the crash is released to the error now.  Its happened again, on android 5.1 on a physical device.  This time no error message at all, only this in the logs:

```
NativeCrashListener: Exception dealing with report
                                                    android.system.ErrnoException: read failed: EAGAIN (Try again)
                                                        at libcore.io.Posix.readBytes(Native Method)
                                                        at libcore.io.Posix.read(Posix.java:165)
                                                        at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
                                                        at android.system.Os.read(Os.java:350)
                                                        at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
                                                        at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138
```

**Comment by hideki** [comment]
Hi @npomfret 
Do you have any additional information about this issue?

**Comment by npomfret** [comment]
I'm afraid not.  I just saw the error in my log and posted all the information I had at the time.  I'll look out for it again.

**Comment by djpongh** [comment]
Sorry, we can't report in home either.
